### ISSUE TITLE
Provide real fish eye for rankings

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1001]
Example see in 

http://www.informatik.uni-rostock.de/~ct/software/TreeView/TreeView.html

Of course we want to distort only the height. 

Initial focus on first element in list

**Comment by sgratzl** [comment]
r6041

see {{{FishEyeRowHeightLayout}}}

current mapping function
{{{
MAX_ROW_HEIGHT = 40;
float MIN_ROW_HEIGHT = 3;

float rowHeightFor(int distance) {
if (distance == 0)
    return MAX_ROW_HEIGHT;
if (distance > 25)
    return MIN_ROW_HEIGHT;
float ratio = distance / 25.f;
float hi = 30 \* (float) (1 - Math.sqrt(ratio));
return MIN_ROW_HEIGHT + hi;
}
}}}

changes and better strategies are welcome
