### ISSUE TITLE
Re-design of Buttons

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1002]
The buttons are very tiny. Maybe it would be better to let them appear under the histograms (as in StratomeX), covering the first line in the list and make them about 30-50% bigger?

I don't like the following buttons 
- remove - that's actually "do not enter" - replace with X
- toggle calssic - multiscore - it's to tiny to recognize, it looks cool though, so maybe good with larger icons

**Comment by sgratzl** [comment]
r6019 and before

notes: 
- new delete icon (red cross)
- button size: 16px

> Maybe it would be better to let them appear under the histograms (as in StratomeX)
> I would prefer to have the button at the top, as on the one hand the user expects to have the remove button similar to the close window button location + currently in the stuck implementation shows the individual histogram on mouse over
