### ISSUE TITLE
Handle interaction with low-weighted attributes (short histograms)

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1004]
In the university use case for the internationalization, for example, buttons are on top of each other. Maybe this can be addressed together with #1089

Also, showing the labels of the attribute on tool-tip if it needs to be truncated will help.

**Comment by sgratzl** [comment]
Replying to [ticket:1091 lex1]:

> Also, showing the labels of the attribute on tool-tip if it needs to be truncated will help.
> should be already the case

**Comment by sgratzl** [comment]
r6049

button bar will now be stretched to the their min size
