### ISSUE TITLE
Re-consider interface for aligning stacks.

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1008]
The arrow and the dragging is sometimes cumbersome. I suggest the following convention:
- clicking on the overall histogram: align to far  left
- clicking on an attribute: align this attribute to the far left (and show a "selected" state in the attribute histogram.

**Comment by sgratzl** [comment]
Replying to [ticket:1095 lex1]:

> The arrow and the dragging is sometimes cumbersome. I suggest the following convention:
> - clicking on the overall histogram: align to far  left
> - clicking on an attribute: align this attribute to the far left (and show a "selected" state in the attribute histogram.
>   the problem with clicking on a histogram is, that this element is already cluttered with other interactions.

currently in a float score, you will set a filter by clicking on the histogram. in a string score you will edit the filter, ...

Furthermore I don't know how intuitive it would be

**Comment by mstreit** [comment]
Alternatively we could add another "align by" button. But we don't really have the space for all the buttons.

I would prefer the click histogram variant, as we already removed the filter interaction for the heatmaps and we do not need to align string scores. But I agree that this is not optimal in terms of UI design.

**Comment by sgratzl** [comment]
what is still missing in the summary approach is that you are currently able to align the combined to the right side -> therefore there are n+1 align positions

**Comment by sgratzl** [comment]
r6073

double click to align on a child histogram + still the arrow
