### ISSUE TITLE
Define custom mapping functions

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1010]
Allow users to define functions using a JavaScript syntax. 

We decided to have thre modes for defining mapping functions:
- the interactive function drawing mode
- the pre-defined functions (log, invert) (see #1061)
- the manual, script-based mapping

For 1 and 2 we show the interface as it is now, for 3 we only show the result.

(I know this is already in the works, opening ticket  to have it on the record)

**Comment by sgratzl** [comment]
r6036 1 & 3 done

notes: \
 double click on the code to edit it
