### ISSUE TITLE
Re-design background of combined attributes

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1014]
Righ now we have a solid grey background. I suggest the following change:
- Instead of the background, make a frame
- Show alternate shading vor every row

**Comment by sgratzl** [comment]
Replying to [ticket:1101 lex1]:

> - Show alternate shading vor every row
>   why just for the combined ones?

**Comment by sgratzl** [comment]
> Show alternate shading vor every row 
> r6059

**Comment by sgratzl** [comment]
Replying to [ticket:1101 lex1]:

> - Instead of the background, make a frame
>   I tried it and it is too salient that this columns are part of a combined one
