### ISSUE TITLE
Implement Mapping for Categorical Data as Function

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1016]
We talked about this today, but I would still argue for implementing the categorical / ordinal data identical to the numerical and allow defining functions on them. 

It's more consistent, and there might be reasons to do so.

**Comment by sgratzl** [comment]
mapping not filtering

**Comment by sgratzl** [comment]
here is the same problem with the general categorical column, see #1058. 

If the number of categories are too large, a mapping makes no sense or is really difficult. 

Furthermore as a consequence, the value needs to be rendered as a score bar for the stack and stuck case, which is only useful if colors are used. 

-> I would suggest to create a custom categorical column type, restricted to less than e.g. 8 categories, which has colors and renders a bar with the category color. 

The mapping would could be simple to have again a function |_, where the horizontal one, with points mapping a category to a value.
