### ISSUE TITLE
Consistent handling of logical operations

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1017]
Currently we handle only OR and AND. We discussed having Multiply as well. Is there something else? 

The visual encoding of AND and OR is obvious at the moment. 

Creating combinations, however, is not very intuitive. We need to improve on the labeling / interaction. 

For AND:

If I drag an attribute not in the combined rating into the cobmined area ALL empty space should be a drop target. Also you should get a large text overlay on top of everything saying. 

"Add ATTRIBUTENAME to the combined ranking (AND)"

For OR:

If I drag an attribute with the intention of making an OR all bars or Histograms should be a drop target. The large overlay should say.

"Combine ATTRIBUTE1 with ATTRIBUTE2 so that only the bigger one counts (OR)" 

Also, the Histogram on top should be labeled 

"OR - Attribute1,  Attribute2"

**Comment by sgratzl** [comment]
Replying to [ticket:1104 lex1]:

> Also you should get a large text overlay on top of everything saying. 
> 
> "Add ATTRIBUTENAME to the combined ranking (AND)"
> what do you mean with on top of everything (where is that)?
> If I drag an attribute with the intention of making an OR all bars or Histograms should be a drop target.
> difficult to realize in the current implementation, as the header and the body are separated and only the header has the logic for this kind of things

**Comment by sgratzl** [comment]
r6070
AND -> SUM, OR -> MAX

**Comment by sgratzl** [comment]
r6155 drag + alt down = sum, drag = max for combinbing columns
