### ISSUE TITLE
Implement alternative representation of mapping

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1020]
Instead of |_ we should do | | or one at the top, one at the bottom in parallel

**Comment by alexsb** [comment]
Nils suggests _|

**Comment by ngehlenborg** [comment]
Nils also suggests exploring if = is possible (parallel axes instead of orthogonal axes)

**Comment by sgratzl** [comment]
r6036

added the four modi.

TODO: parallel one aren't interactive

**Comment by sgratzl** [comment]
Replying to [comment:4 gratzl]:

> r6036
> 
> added the four modi.
> 
> TODO: parallel one aren't interactive
> r6116
