### ISSUE TITLE
Find a second dataset / use case with complex mapping requirements

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1021]
In addition to the university dataset. 

Suggestions:
- Nutrition values
- Cars and properties of them

**Comment by mstreit** [comment]
Duplicate of #1059: Import University ranking.
The top 100 under 50 dataset was used for simplicity because the mapping to 0...1 was already done. The world university dataset does not have this and requires more complex mappings. Also by far more attributes are available.

**Comment by alexsb** [comment]
Reopend, reduced prioirity since it's not about complexity, more nice to have
