### ISSUE TITLE
Update Copyright statement in source

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1022]

**Comment by mstreit** [comment]
We should not mix core developer names and institutions:

```
Copyright(C) 2005, 2012 Graz University of Technology, Marc Streit, Alexander
 * Lex, Christian Partl, Johannes Kepler University Linz
```

I suggest to just write "The Caleydo Team <www.caleydo.org>"

**Comment by alexsb** [comment]
This is thought of as copyright holders. Strictly speaking you only have copyright on the code you wrote as a student. Otherwise the copyright belongs to your employer. I agree that "The Caleydo Team" would be a good idea.

**Comment by mstreit** [comment]
Replace with short header that does not contain years and other info that needs to be changed on a regular basis. Header should include link to license text on website.

**Comment by mstreit** [comment]
Suggestion:

```
/*******************************************************************************
 * Caleydo - Visualization for Molecular Biology - http://caleydo.org
 * Copyright (c) The Caleydo Team. All rights reserved.
 * Licensed under the new BSD license, available at http://caleydo.org/license
 *******************************************************************************/
```

We could also leave out the year, but I am not sure if this is a good idea.
If we leave it in there, we need to touch all files on new year's eve.

RFC!

**Comment by mstreit** [comment]
Used Eclipse tool to successfully replace the header in all files: http://www.wdev91.com/?p=cpw
