### ISSUE TITLE
Make pathway list scrollable

### ISSUE THREAD

**Issue by cpartl** [Caleydo/caleydo#1041]
Scrollbars should show up for the list, when it does not fit the available space

**Comment by sgratzl** [comment]
r6143, r6144:

TODO: implement a IScrollBar that is compatible with the old picking manager and set that in the RankingElement

**Comment by sgratzl** [comment]
Replying to [comment:1 gratzl]:

> r6143, r6144:
> 
> TODO: implement a IScrollBar that is compatible with the old picking manager and set that in the RankingElement
> r6153
