### ISSUE TITLE
Create portal links for whole pathways

### ISSUE THREAD

**Issue by cpartl** [Caleydo/caleydo#1060]
For my current L1 pathways, which of the other pathways have portals? (1-n)
highlight window, tell me how many, connect with visual links
What are the portals between a selected L2-4 pathway and the L1 pathways (1-1)
Implicit: complete links between two L1 views

For ALL links: Clicking on a link promotes any involved view to at least L2 and sets the context of L2

@Links: Connect to title bar in case of L4, L3, L2, except if L2 context contains portal, then connect directly

**Comment by alexsb** [comment]
Fixed in the backbone. 
Visualization covered by #1179
