### ISSUE TITLE
Adapt filter of pathway ranking

### ISSUE THREAD

**Issue by cpartl** [Caleydo/caleydo#1061]
Instead of using a regex, check for case insensiteve substring.
The column should adapt dynamically while typing.
(It should be the same functionality as in the original dropdown list of the pathway view)

**Comment by sgratzl** [comment]
r6189

it is now case insensitive and live updating, but I still prefer to use the \* notation instead of a simple substring search, as it is more powerful. Your substring query would be then: {{{_text_}}}

**Comment by sgratzl** [comment]
r6257

added different filter strategies: regex, wildcard(default) and substring -> already set in the RankingElement class to substring for entourage
