### ISSUE TITLE
Implement legend

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1067]
We should show a legend for the pathways: 
- What does the ! mean
- What is the color mapping for the selected dataset
- What does the std-dev bar mean 
- What do the bubble sets mean
- What do the stubbies mean

**Comment by alexsb** [comment]
This could be in the place where we now have the dataset selection (which will move to lineup). Alternatively we could just point to the help.

**Comment by mstreit** [comment]
A separate view similar to the dataset info would be another option.

**Comment by mstreit** [comment]
Pointing to the help sounds good to me.

**Comment by alexsb** [comment]
Will be added to help.
