### ISSUE TITLE
Allow to select not-connected paths

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1083]
This would allow to deal us with missing data in KEGG and give us more flexibility

**Comment by alexsb** [comment]
See also #1524. 

Also, this is already described in a paper -

> In some cases, the information of pathway maps is not complete or simply outdated. As a consequence, they
> may not reflect the true process, especially not for all experimental conditions. Additionally, pathway databases can also contain errors that users are aware of. In order to cope with such incomplete or outdated pathway descriptions we provide a force mode for selecting paths. This mode enables analysts to add an edge to the pathway, which does not exist in the database. Notice that the second to last edge of the selected path in Figure 4(b) does not exist in the pathway map, neither in the image, nor in the underlying graph representation. By using the force mode during path selection, analysts are able to extend the current path by arbitrary nodes within the pathway map.

And is shown in a figure: 
![forcemode](https://f.cloud.github.com/assets/2039375/919586/758276e6-fecc-11e2-9f10-8895e96e8b11.png)

So that really should be in the code ;).

**Comment by cpartl** [comment]
part of #1524
