### ISSUE TITLE
Predict Rank changes on value changes

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1086]
Currently the user is able to edit the values of the selected row. 

However, it would also be interesting to predict and present the rank change if the value would increase/decrease by 5,10,20,... percent. 

Ultimately the system could suggest attributes where the item should get better by xx percent to increase its overall score by a given number. 

While the first case is quite simple, the latter case is more complex as: 
- you may not be able to invert the mapping function, e.g. abs
- there are several ways to gain places in the case of a combined score (a little bit of attribute A, some more of attribute B)

**Comment by alexsb** [comment]
Do we want to follow up on this?

**Comment by sgratzl** [comment]
I think it depends on the paper review result, whether we want to spend time on this or not

**Comment by sgratzl** [comment]
generalized to #1517
