### ISSUE TITLE
Mark inverted and non-linear mappings

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1098]
show full bars for linear and filter
show online outline of bars for non-linear and inverted

**Comment by mstreit** [comment]
instead of outline we could some kind of shading

**Comment by alexsb** [comment]
shading -> hatching (schraffieren)

Furthermore, we should add a line as part of the header below the histogram briefly textually describing anything beyond a pure linear mapping.

**Comment by sgratzl** [comment]
Replying to [comment:2 lex1]:

> shading -> hatching (schraffieren)
> 
> Furthermore, we should add a line as part of the header below the histogram briefly textually describing anything beyond a pure linear mapping.
> the hatching part should be possible (r6335) but the text is too difficult
