### ISSUE TITLE
"Linear Log" mapping fails for items with attribute values = 0

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1101]
Right now these items will not be shown at all. There should be a warning or those items should be shown with a missing value for that attribute.

**Comment by ngehlenborg** [comment]
Btw, why is this mapping called "linear log"? I don't understand the "linear" part.

**Comment by mstreit** [comment]
I guess it means that we map linear values to log scores

**Comment by ngehlenborg** [comment]
We should drop the "linear" part in this case since values don't really have a "linear" (or "logarithmic" or "exponential") property.
