### ISSUE TITLE
Add top and bottom stubs

### ISSUE THREAD

**Issue by dkalkofen** [Caleydo/caleydo#1102]
for small angles link nodes using top and bottom stubs

**Comment by alexsb** [comment]
- L1 pathways -> use upper or lower edge
  - L2 pathways -> use "knee" to the side

**Comment by dkalkofen** [comment]
- L2 pathways -> use "knee" to the side 
  this is too much geometry and those often hides other stubs -> therefore all up/down stubs have been places above or below the node instead of left or right to it
