### ISSUE TITLE
Group names screwed up again

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1105]
Shows "Group 7" instead of dataset name in enRoute

**Comment by alexsb** [comment]
@sgratzl - is the reference here correct? I'm a little confused looking at the code you changed in this commit I don't see a direct relationship to the problem?

**Comment by alexsb** [comment]
However, I can't reproduce this problem. Closing.

**Comment by sgratzl** [comment]
> @sgratzl - is the reference here correct? I'm a little confused looking at the code you changed in this commit I don't see a direct relationship to the problem? 

no it is not, maybe a error during conversion, since the ticket numbers between trac and github are different
