### ISSUE TITLE
Improve stub connection of windows

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1115]
- they currently appear flipped
  - pointing to the center of the window is good as long as there is no link. If there is a link they should point straight to the link target. This avoids the "bend".
  - better docking - try to get it under the window

**Comment by dkalkofen** [comment]
=== Fixed ==
- they currently appear flipped
  pointing to the center of the window is good as long as there is no link. If there is a link they should point straight to the link target. This avoids the "bend". 

=== Open==
- better docking - try to get it under the window 
  ++ this looks odd for higher angles - however, increasing the top/down-left/right threshold renders too many links top/down
