### ISSUE TITLE
New paths in context path don't come up as selected

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1116]
If a context paths is dynamically switched in (Ctrl-Click) it's nodes are not selected.

**Comment by cpartl** [comment]
I am not entirely sure what you mean by that. 
Do you mean that there is no orange frame around the focus node and its portals upon ctrl+click?
Or do you mean that the context paths do not show up? (how to reproduce?)

**Comment by alexsb** [comment]
I had a hard time reconstructing what I meant, but I figured it out :)

![shc_selection](https://f.cloud.github.com/assets/2039375/1254656/1a222326-2b79-11e3-8eaf-1997f2cb1b23.png)

Here, shc was set as the portal node. Notice that in the source pathway it's also "selected" (orange). In the new context paths this selection is not synchronized. If I later select nodes it works of course.
