### ISSUE TITLE
Make exclamation marks more salient

### ISSUE THREAD

**Issue by cpartl** [Caleydo/caleydo#1120]
In pathway textures, they are hard to perceive, especially when data is mapped on them. Maybe move them out of the nodes, make some white halo around the marks or something similar.

**Comment by alexsb** [comment]
Moving them out is maybe not so good as we have plenty of clutter already. 
Halo is an option, but only helps in case there is a mapping.

**Comment by alexsb** [comment]
This was not intentionally closed but was an artifact of the merge.
