### ISSUE TITLE
Setup Jenkins CI Server for Caleydo

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1126]
jobs:
- compile regression
- create exportable version of caleydo (zip, installers,...)
- tcga project builder
- [auto upload nightly builds to caledyo web server]

**Comment by sgratzl** [comment]
for the windows installer, e.g. using: [http://nsis.sourceforge.net/Main_Page NSIS] -> can also create a installer for windows under linux

**Comment by sgratzl** [comment]
for ant using the: 
 http://www.ant4eclipse.org/

and maybe the stuff from: 
http://rcpapps.cvs.sourceforge.net/viewvc/rcpapps/org.rcpapps.base.feature/releng/build.xml?view=log

for exporting products

**Comment by sgratzl** [comment]
do the installation as described in https://wiki.jenkins-ci.org/display/JENKINS/Installing+Jenkins+on+Ubuntu

**Comment by sgratzl** [comment]
see also #1139 for nsis setup generator

**Comment by sgratzl** [comment]
see also Maven + Tycho

http://www.vogella.com/articles/EclipseTycho/article.html

https://github.com/tesla/book-tycho/blob/master/en/01-introduction/01-chapter1.md

archetype: https://github.com/open-archetypes/tycho-eclipse-plugin-archetype

m2e connector is available

**Comment by sgratzl** [comment]
done
- create pom files
- regression job -> daily builds of product zips: http://dev.caleydo.org/jenkins/job/caleydo

todo: 
- [x] create extra packages: windows installers, deb packages
- [x] create release script (similar to https://docs.sonatype.org/display/M2ECLIPSE/Staging+and+releasing+new+M2Eclipse+release) 
- [x] create super project (project with product + feature + as submodules caleydo repo + extra view repos)

**Comment by sgratzl** [comment]
> create super project (project with product + feature + as submodules caleydo repo + extra view repos)

done

**Comment by sgratzl** [comment]
> create release script (similar to https://docs.sonatype.org/display/M2ECLIPSE/Staging+and+releasing+new+M2Eclipse+release) 

a first version of the release script is /src/main/scripts/scripts.sh -> prepare and finish function 

see also caledyo.super Release project

**Comment by sgratzl** [comment]
deb / rpm package generator plugins, e.g. using http://mojo.codehaus.org/unix/unix-maven-plugin/plugin-info.html or http://debian-maven.sourceforge.net/

nsis : http://mojo.codehaus.org/nsis-maven-plugin/

**Comment by sgratzl** [comment]
deb versioning, see http://www.debian.org/doc/debian-policy/footnotes.html#f37
-> 3.0.2~pre1 should work

**Comment by sgratzl** [comment]
windows installers are now build, too part of : Caleydo/caleydo.super@73a1388ab61055e7664eee43f170b0277e680ab2

based on nsis including nice installer, startup menu + file association

**Comment by sgratzl** [comment]
first deb packages are built: http://dev.caleydo.org/jenkins/job/caleydo.super/lastSuccessfulBuild/artifact/org.caleydo.rcp/target/products/caleydo-linux.gtk.x86_64.deb

can anyone with a debian system can test it?

**Comment by alexsb** [comment]
Works!
