### ISSUE TITLE
Create a custom Text Renderer

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1127]
e.g. based on slick util: http://lwjgl.org/wiki/index.php?title=Slick-Util_Library_-_Part_3_-_TrueType_Fonts_for_LWJGL

features: 
- per glyph cache not per text cache
- using awt text renderer for getting the exact positions
- avoid background pickings

goals: 
- faster
- no cache errors
- no z deltas just plain quads

**Comment by alexsb** [comment]
Could solve #931 and #997

**Comment by sgratzl** [comment]
a first working draft of the new Text renderer is available, called: BitmapTextRenderer -> it can be launched as a SandBox

features: 
- glyph based approach
- just an intensity texture -> no more background color stuff
- cache able
- kerning
- not on top of everything -> just simple quads

todo:
- improve quality of rendering by aligning the quads
- using vertex arrays for faster rendering
- compatibility for ElementLayout based layouts

**Comment by ngehlenborg** [comment]
This garbled text is what I see very frequently (Mac OS X 10.7.5, NVIDIA GeForce GT 330M):

![screen shot 2013-05-16 at 10 00 42 am](https://f.cloud.github.com/assets/1216518/512801/22323e2a-be32-11e2-9a1c-0ff0bb025606.png)
