### ISSUE TITLE
Remove Weka Dependency

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1131]
currently we only need the heavy weka library for implementing the KMeans. But as this is a quite simple algorithm, we might want to remove Weka and implement it by our own

**Comment by sgratzl** [comment]
a draft of the new version is commited 542db36c1d7cfb9a40d0bb59ebdb28f736d694e0

**Comment by sgratzl** [comment]
as a sideeffect I implemented an extension point for the clustering algorithms, such that new one can easily be integrated

**Comment by mstreit** [comment]
WEKA is still a dependency, as we currently offer two k-means tabs - one with WEKA and the other one uses our own implementation. Can we remove WEKA now? We also do not need two k-means options in the cluster dialog.

**Comment by sgratzl** [comment]
> Can we remove WEKA now? We also do not need two k-means options in the cluster dialog.

see #1146 it was because the new k-means implentation was used. And I didn't have the time yet to check where the error is. 

If you don't like the two k-means options, just remove one of the corrensponding extension entries

**Comment by mstreit** [comment]
I would like to remove the old WEKA clusterer option.
Can you try to fix the new k-means clusterer? Is there a ticket?

**Comment by mstreit** [comment]
That's really strange. It used to work already (see my comment above). I've already tried to clean the .caleydo folder as well as the launch config. Anything else I could try?

**Comment by alexsb** [comment]
My last tests showed that the weka stuff is actually broken. Probably not too hard to fix, but it there a point? We should not release with two k-means options. 

I haven't seen problem with the new k-means implementation.

**Comment by sgratzl** [comment]
> My last tests showed that the weka stuff is actually broken. 

more details, please

the custom one _should_ work, I can't guarantee it.

**Comment by alexsb** [comment]
I can fix the weka stuff if we want it to be fixed - I already fixed a minor bug where record was used twice instead of dimension & record. Currently the cluster result contains null for both record and dimension. I didn't investigate - but in my next commit an appropriate check reports an error. 

But I'm asking here whether we want to keep it around at all. 

How could you gurantee  it? Should we just fix weka and compare results?

**Comment by sgratzl** [comment]
> How could you gurantee it? Should we just fix weka and compare results?

You can't fully guarantee it, as k-means starts randomly. 

But it would help, if others would take a look at the code, too. aka CodeReview

**Comment by alexsb** [comment]
I know but if we get generally similar results over various cases then I'd be happy to accept this as correct.

**Comment by sgratzl** [comment]
as I said from my point of view it should work. Therefore it doesn't help if I'm the owner of that ticket, as I can't do that much

**Comment by alexsb** [comment]
Empirical comparison Weka VS Sam

![weka-vs-sam](https://f.cloud.github.com/assets/2039375/739783/a92e9e6e-e362-11e2-9ac4-3330567578a8.png)

Pairwise comparisons for various cluster sizes.

**Comment by sgratzl** [comment]
as @alexsb found the weka bug it isn't critical any more
