### ISSUE TITLE
External Tools (R) import / export

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1132]
we have to think of how we want to handle bindings to external tools. 

e.g. R

possibilities:
- using JRI, we can directly include R and use it for computations, but we are highly dependent on the version (hacking a (dynamic) JRI shared library is possible but difficult) -> but how should the user interact with R
- using StatET and find a way to hack into the communication, such that we can import / export data -> user has to use StatET + R environment
- generic solution, e.g. via a small webservice running along caleydo, that provides methods to read and write datasets, 
  -> implies generic tranfer and serialzation of data
- similar to MayDay: using rJava + JRI to communicate with R over a java socket and read / write data like this
  -> mix between StatET and generic solution

**Comment by alexsb** [comment]
How strongly do we actually rely on R? Do we use advanced enough statistics that justifies use of R or are the algorithms easy to re-implement.

**Comment by sgratzl** [comment]
> How strongly do we actually rely on R? Do we use advanced enough statistics that justifies use of R or are the algorithms easy to re-implement.

currently we don't need R for any computation. There are java libraries out there, which contains most of the math stuff (e.g. http://commons.apache.org/proper/commons-math/)

From my point of view R is only interesting for importing / exporting data. e.g. in our bicluster use case, the users want to play around with their algorithm, push the result to Caleydo, and see the bicluster visualization. 

However if we implement the import/export in a general way, other tools can also be easily communicate with Caleydo (Matlab,...)
