### ISSUE TITLE
Convert Eclipse Views and Applications to Eclipse E4

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1138]
currently we are using Juno with the compatibility layer. 

but the compatibility layer is not perfect. 

we should therefore think of porting the code to the Eclipse E4 standard.

see http://eclipsesource.com/blogs/2012/06/18/migrating-from-eclipse-3-x-to-eclipse-4-e4/

**Comment by alexsb** [comment]
Yes, what's your estimation on effort?

**Comment by sgratzl** [comment]
I don't know it exactly

the biggest part will be conversion of the Eclipse-Applications as all of our views have common super classes
