### ISSUE TITLE
remove all PAAD data packages ASAP

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1147]
The PAAD data set contains samples that were redacted (i.e. removed from the study) due to legal (?) reasons and all GDACs have been asked (yesterday) to remove the data until it has been cleaned up. Most GDACs have already responded, e.g. on the Broad website the data is no longer available. We should do the same.

I'm not sure what the best way is to do this. We can hack the website site code to hide all PAAD data or recreate the JSON files and delete the data packages manually.

**Comment by sgratzl** [comment]
I currently hacked the firehose-data.js file and filter PAAD out

**Comment by sgratzl** [comment]
workaround works for me
