### ISSUE TITLE
Sample project should open with DVI, Stratomex+TourGuide 

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1150]

**Comment by sgratzl** [comment]
tourguide will open on the fly, when using the stratomex add wizard. I think we don't should therefore open TourGuide at the beginning

**Comment by alexsb** [comment]
I think the main issue is if we want to show DVI by default.

**Comment by sgratzl** [comment]
> I think the main issue is if we want to show DVI by default. 

DVI is good starting point to see, what data sets are loaded and to explore the existing stratifications. So I think it is still a good starting point for a project

**Comment by alexsb** [comment]
ok, agree
