### ISSUE TITLE
Change nomenclature for "Create Small Multiples *"

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1151]
We need to find a better title for the following actions:
- Create Small Multiple Pathway Group
- Create Small Multiple Clinical Data Group

**Comment by alexsb** [comment]
Or integrate small multiples creation in dependent column mode of TourGuide

**Comment by ngehlenborg** [comment]
We definitely need to get rid of "small multiples", no matter where we put this. Our target audience does not know what is meant by this.

I'd prefer to integrate it into the Tour Guide, if possible.

**Comment by mstreit** [comment]
We can remove all small multiple entries. The functionality is now covered by our new tour guide workflow.
