### ISSUE TITLE
Unify capitalization of actions

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1152]
Currently actions such as context menus, pop up window titles, etc. do not use a uniform rule for capitalization, for example "Score group" vs. "Export Data". Sometimes it is even mixed, e.g., "Score group (Mutual Exclusive)"

**Comment by alexsb** [comment]
Yes. We should use sentence case, not title case. E.g. "Score group (mutual exclusive)"

**Comment by alexsb** [comment]
I've assigned @sgratzl since I've observed this a lot in the lineup context menues. 
@cpartl please check stratomex and DVI for occurences

**Comment by sgratzl** [comment]
I checked tour guide and the line up

> @cpartl please check stratomex and DVI for occurences

In addition, if someone still finds an errror, he should fix it
