### ISSUE TITLE
need check for version of data package vs version of software

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1156]
cal files that were generated for another version of the software cause an exception and freeze the software, but no error message is shown to the user. 

We should

a) show an error message
b) handle the exception and let the user continue with another data package

**Comment by sgratzl** [comment]
currently there are not metadata (such as the version) stored within the projects. But that I'm going to change that. 

So I can say at least, that if we don't have the metadata, the package is too old and may not be compatible.

**Comment by sgratzl** [comment]
related to #957 
I can check if the project has a valid version, but there is no possibility to abort in a clear way

**Comment by alexsb** [comment]
What do you mean in a clear way? I'd be happy if you show an error message and close.

**Comment by sgratzl** [comment]
> What do you mean in a clear way?
> clear way, more than just showing an MessageDialog and exit the application. 

But is a longer story, e.g. if you import data, you only get limited information what is going on and what went wrong.

> I'd be happy if you show an error message and close. 
> is implemented
