### ISSUE TITLE
progress indicator in Tourguide should be more informative

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1158]
The current progress indicator (spinner) is not working properly, i.e. I only get a huge, pixelated spinner image that is not moving.

It would be better to provide a standard progress indicator that also provides some information about what is happening (e.g. some score is calculated).

**Comment by sgratzl** [comment]
the new waiting icon is implemented using OpenGL and provides some notion of a progress status including a cancel button
