### ISSUE TITLE
histogram backgrounds are cyan

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1163]
When hovering over the histogram of a "stuck" attribute, the histogram backgrounds in the popup are cyan.

![Screenshot](https://f.cloud.github.com/assets/1216518/438493/bafb4cb0-b0cb-11e2-9c6a-a658c3729536.png)

**Comment by sgratzl** [comment]
wontfix, that desired behavior (somehow), it is because of the data domain colors
