### ISSUE TITLE
colors in mutation column histogram do not match colors in column itself

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1167]
The histogram shows bars in pink and red, while the bricks in the column are gray and red. And boy, that red is intense!

![Screen Shot](https://f.cloud.github.com/assets/1216518/438533/3cb660cc-b0cd-11e2-88e4-e1e70a1e90c8.png)

**Comment by alexsb** [comment]
Yes, that's because of the way how this is implemented right now in the histogram. I can fix that, but I was wondering whether we should replace the histogram with @sgratzl's implementation. Is that feasible? I'd like to not maintain multiple histogram implementations.

**Comment by alexsb** [comment]
The same issue causes also the copy number and mutation specific hack for histograms. Only datasets with copy and mutation in the name are correctly handled. This needs to be generalized for categorical data.
