### ISSUE TITLE
the two column "addition" states are confusing - can we make this easier?

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1168]
Example: I was going through a list of mutations using the "preview" mode and then decided to find a mutually exclusive mutation for the gene that I had added in preview mode. The query worked, but when I started going through the list of results, the original query column was replaced with the results.

We have two options:
1. Either we deactivate queries on preview columns (maybe we should not allow any actions and make them "read-only")
2. We allow actions but pop-up a window that says "This column is in preview mode. If you want to continue, the column will be added to the StratomeX view".

**Comment by sgratzl** [comment]
is this still an issue as we have the new tour guide wizard?

**Comment by alexsb** [comment]
No.
