### ISSUE TITLE
should a new query reset the Tour Guide view?

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1169]
I think it is too confusing to deal with new and old queries and usually there is no need to keep and old query around.

**Comment by sgratzl** [comment]
in the current tour guide wizard implementation it is implemented like this: 

if you use the wizard to create a new score (e.g. jaccard, adjusted rand,...) then automatically the previous existing leading scores will be removed. 

This is especially useful if you change the query (i.e. the selected group / stratification) during browsing

--> worksforme
