### ISSUE TITLE
StratomeX shows double columns when iterating over query results with multiple instances of the same rank

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1171]
To reproduce:
1. recreate configuration shown in screen shot

![Screen Shot](https://f.cloud.github.com/assets/1216518/439252/77cfc254-b0df-11e2-9d1f-400b604dd251.png)

**Comment by sgratzl** [comment]
@ngehlenborg can you verify this again

**Comment by alexsb** [comment]
I can't. Closing
