### ISSUE TITLE
Highlight all entries in tourguide that are shown in Stratomex

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1178]
Similar to what we do in entourage with pathways. 

Simple co-occurence: grey background
Reference column: reference color background (blue?)
Volatile preview column: preview color background (green?)

**Comment by sgratzl** [comment]
up to now the normal colors are used as in LineUp. 

if you dont like them: GLTourGuideView 561ff. is the place to change it

**Comment by alexsb** [comment]
This looks good now.
