### ISSUE TITLE
user reporting ThemeEngineManager issue launching Caleydo from command line using equinox launcher

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1185]
This could be due to a misconfiguration of the environment. I have not been able to reproduce this. Any idea what could be causing this?

``` bash
$ cd caleydo
$ ls
Caleydo.app/   configuration/ features/      gfx/           plugins/
$ java -XstartOnFirstThread -jar plugins/org.eclipse.equinox.launcher_1.3.0.v20120522-1813.jar
An error has occurred. See the log file
/Users/robertbaertsch/Downloads/caleydo/configuration/1367886126325.log.
$ cat /Users/robertbaertsch/Downloads/caleydo/configuration/1367886126325.log
```

``` java
!SESSION 2013-05-06 17:22:06.045 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.7.0_21
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US

!ENTRY org.eclipse.equinox.ds 4 0 2013-05-06 17:22:09.266
!MESSAGE [SCR] Exception while activating instance org.eclipse.e4.ui.css.swt.internal.theme.ThemeEngineManager@3c867009 of component org.eclipse.e4.ui.css.swt.theme  
!STACK 0
java.lang.NoClassDefFoundError: org/eclipse/swt/widgets/Display
       at java.lang.Class.getDeclaredMethods0(Native Method)
       at java.lang.Class.privateGetDeclaredMethods(Class.java:2451)
       at java.lang.Class.getDeclaredMethods(Class.java:1810)
       at org.eclipse.equinox.internal.ds.model.ServiceComponent.getMethod(ServiceComponent.java:126)
       at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:213)
       at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
       at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:347)
```

**Comment by sgratzl** [comment]
was the downloaded caleydo of the right architecture version: ARCH=x86_64?

as it seems that it can't load / find the correct swt binaries, which are architecture and system dependent

**Comment by sgratzl** [comment]
--> reproduced behavior by trying to launch x86 on a x64 machine

**Comment by sgratzl** [comment]
wontfix

**Comment by alexsb** [comment]
On 05/07/2013 05:02 AM, Samuel Gratzl wrote:

> --> restored behavior by trying to launch x86 on a x64 machine

Do you mean reproduced? This is an issue of the guy using the wrong 
architecture?

> —
> Reply to this email directly or view it on GitHub
> https://github.com/Caleydo/caleydo-dev/issues/1185#issuecomment-17531139.

## 

Alexander Lex
Harvard SEAS | http://www.alexander-lex.com
The Caleydo project: http://www.caleydo.org

**Comment by ngehlenborg** [comment]
I will test this, too. If I get the same error, I will get back to them asap.

**Comment by ngehlenborg** [comment]
I can confirm Sam's observation: the error is reproduced when attempting to launch a 32-bit build on a 64-bit architecture.

**Comment by sgratzl** [comment]
> Do you mean reproduced? This is an issue of the guy using the wrong architecture?

I edited the comment 5 seconds later, but you just got the initial message
