### ISSUE TITLE
include information about architecture in application name or folder name or architecture file

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1187]
For the average user it is impossible to tell for what architecture the downloaded version is.

Related to #1185.

**Comment by alexsb** [comment]
So you're suggesting that we name a caleydo folder caleydo_win_x86? I think this is weird. The download and the files are clearly stated as such. I've never seen the practice of an app naming it's folder according to architecture. 

What's an architecture file? 

The only reasonable thing to do is to check on launch if arch is correct and give a decent error message. Not sure if that's possible though, might require a script that checks first.

**Comment by ngehlenborg** [comment]
Downloading an archive in Safari on my Mac automatically extracts (and deletes) the archive and I am left with a folder named "caleydo" and no way to figure out for which architecture this build is.

**Comment by ngehlenborg** [comment]
Downloads for Java examples for windows (from http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html) contain a "release" file with the following content:

```
JAVA_VERSION="1.7.0"
OS_NAME="Windows"
OS_VERSION="5.2"
OS_ARCH="amd64"
SOURCE=" .:fa322ca37832 corba:61e2e2d9cfce deploy:86b06c66ab5e hotspot:d07dafb51e1d hotspot/src/closed:0f9b3fa32283 hotspot/test/closed:0559fe400b8e install:16b90e6b8f83 jaxp:3e0e331bdfb8 jaxws:fe6f5b57b9e6 jdk:f9323b9d020c jdk/make/closed:a92721af6d02 jdk/src/closed:635a24c8ec5f jdk/test/closed:8def5a1788ab langtools:e120818fc321 pubs:c789f1cac86d sponsors:1b50634582dd"
```

**Comment by alexsb** [comment]
I can add an info file. Estimates on whether better error messages are possible are welcome

**Comment by alexsb** [comment]
Fixed with info.txt file.
