### ISSUE TITLE
Change text in empty StratomeX to hint at the + sign, or add default empty column

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1196]
In the latter  case the default column could be removed if a column is added in a different way.

**Comment by ngehlenborg** [comment]
I vote for the former solution. No default placeholder column.

**Comment by alexsb** [comment]
Is there a reason for your preference?

**Comment by ngehlenborg** [comment]
Simply to avoid confusing users. They will learn right from the start that to add a column, they need to click on the plus sign.

**Comment by sgratzl** [comment]
change text to ?

current text:

Please use the Data-View Integrator to assign 
one or multiple dataset(s) to StratomeX.
Refer to http://help.caleydo.org for more information.

**Comment by alexsb** [comment]
Suggestion:

To add a column showing a dataset click the "+" button at the top or use the TourGuide or the DVI. 

Refer to http://help.caleydo.org for more information.
