### ISSUE TITLE
What's the plan for making additions of copy number & mutation starts usable? 

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1199]
We talked about having 
- exclusive datasets in a separate tab
- the rankings of mutated/not mutated etc integrated, with all other stratifications have a NA entry
- an exclusive mode in the original window?

**Comment by sgratzl** [comment]
> having the rankings of mutated/not mutated etc integrated, with all other stratifications having a NA entry

which special rankings?

**Comment by alexsb** [comment]
rankings should mean scores based on mutation status -> e.g., if for a gene every sample is mutated then this would be a high score.

**Comment by sgratzl** [comment]
related #1211 (data domain specific metrics) that implements: 

> rankings should mean scores based on mutation status -> e.g., if for a gene every sample is mutated then this would be a high score.

**Comment by alexsb** [comment]
Resolved relevant parts with #1211 - rest wontfix.
