### ISSUE TITLE
How to handle open Pathway tab.

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1204]
When a pathway was added in the past we have the pathway tourguide open. 

This is unusable in it's current form. I suggest that we either 
- disable it
- allow to add pathways

The best solution would be a combination: if we have a selected column it's clear - the pathway is added to it.  If there is no selected column it should be disabled and display the text: "Select a column to which to add the pathway."

**Comment by sgratzl** [comment]
>  if we have a selected column it's clear 

there is no notion of a selected column in StratomeX yet

**Comment by alexsb** [comment]
What do you call the state after you click add pathway? I get the frame around the header brick? This would be the selected column, wouldn't it?

**Comment by sgratzl** [comment]
> What do you call the state after you click add pathway? I get the frame around the header brick? This would be the selected column, wouldn't it? 

that's a temporary state of the column if you canceled or confirmed a template column, the selection is gone.

so if you want to add a pathway out of the box, there is not selection made in StratomeX

**Comment by alexsb** [comment]
Is there some reason why we don't want to make this state permanent? It would make a lot of sense to me.

**Comment by mstreit** [comment]
Add selection frame around column. The selected column is taken as the reference column if the user adds a dependent column via tour guide (pro feature)

**Comment by sgratzl** [comment]
@alexsb wan't more?

**Comment by alexsb** [comment]
Very cool. Works perfectly.

Only thing to add is to inactivate the pathway selection if no column is selected and display:

"Select a column in StratomeX to add a Pathway to it,"
