### ISSUE TITLE
Can we find a clearer text for "add numerical data". I find this confusing. 

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1207]
What do we want to say with this option? Is it:
- Add data using an existing stratification
- Add clinical data
- Add meta-data

Or something else? Add numerical is not clear IMO.

**Comment by mstreit** [comment]
Introduce categorization: Independent / dependent
Add Stratification (independent)
Add Pathway (dependent)
Add Other Data (dependent) - in addition show a list of all inhomogeneous datasets (clinical atm)
