### ISSUE TITLE
Define qualitative color palette with multiple brightness values 

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1208]
Use colors from ColorBrewer's single color scales.
See http://bl.ocks.org/mbostock/5577023

The new color palette should be used for the dataset colors.
Brighter or darker version should be used where appropriate.

**Comment by alexsb** [comment]
Which one do you mean?

**Comment by mstreit** [comment]
The sequential ones that have a single base color.

**Comment by sgratzl** [comment]
I added all ColorBrewer sets and sizes

feel free to use them for quantitative color scales. As I don't exactly know how the new color palette should look like, you either give me a better description or do it by your own

**Comment by mstreit** [comment]
Let's use the central color from the color scale as dataset colors. We can fine tune later. 
The darker version should be used for K-M plots.

**Comment by alexsb** [comment]
What do you mean? Use each diverging color scale as one dataset color? I'm not sure if that's a good idea, but we can try.

As far as KM is concerned: I thought about this and would argue for a pure gray solution. I think the color is redundant anyways and an ambiguous association (a) doesn't really matter and (b) could be resolved with interaction.

**Comment by sgratzl** [comment]
as I understood the idea is to start at the center of one of the following sets: reds, blues, greens, oranges, purples
(right top in the single color scales linked at the top)

regarding KM -> for the header brick we need to draw multiple plots at the same time

**Comment by mstreit** [comment]
No, that's not what I mean. We can use the sequential color scales for the datasets. For each dataset a different sequential scale. This way we also have nicely defined darker and brighter versions. Sam already implemented that brighter/darker can be called on the color class - also multiple times in a row.

I agree with the KM argument. I forgot that the dataset is always the same for all sub curves..

**Comment by alexsb** [comment]
The definition is closed, KM is solved, the rest is covered by #1277
