### ISSUE TITLE
How to handle Log Rank test

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1210]
the log rank test is a metric for a stratification based on a selected clinical variable

I have no idea how to implement that within the tour guide wizard

**Comment by mstreit** [comment]
The best way could be to trigger it directly on the KM plot, as it already defines the clinical variable and the stratification it belongs to. However, using the context menu is quite hidden. Do we have a better possibility? Maybe we case use a popup icon similar to the dependent column "+" icon that is shown on mouse over.

**Comment by sgratzl** [comment]
to be more precise: this is an example of a Dependent->Independent case, where you start with a dependent one and find the corresponding independent one.

So starting from a existing KM-plot that is dependent to another stratification is not a good idea.

**Comment by sgratzl** [comment]
two new options for other: 
- browse lists -> add add single single KM plot + in addition similar to "add dependent" "add independent" including: Log-Rank + selection
- multi step selection: 1. select other 2. select stratification -> same for pathways
