### ISSUE TITLE
agree on and advertise minimum required display resolution

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1218]
We should discuss if it would make sense to agree on a minimum display resolution that we want to support. I keep on running into numerous problems when demoing Caleydo on low-res projectors (e.g. 1024x768).

**Comment by alexsb** [comment]
Yes. While I say we don't support low-res (i.e. 1280 x 1024 would be the lowest I consider) this problem is also true for high res. We need to deal with retina displays in the near future, and I assume that the problems are strongly related. So maybe the solution is a technical instead of a convention.

**Comment by ngehlenborg** [comment]
@alexdb & @mstreit: Should we split this into (a) dealing with minimum resolution (for 3.0) and (b) dealing with high-res displays (post 3.0)?

**Comment by ngehlenborg** [comment]
I can have someone from our lab test on a high-res display to make sure that 3.0 works without special treatment of high-res displays. I think there are a few people who have one.

**Comment by alexsb** [comment]
Yes. This ticket is about testing with 1280 x 1024. Retina & co are different.

**Comment by mstreit** [comment]
Works fine with 1280x1024. 
I had some problems though with render artifacts when scrolling GL views, however, that might be related to #829.

**Comment by mstreit** [comment]
Added this sentence to the download section on our current website:

"Caleydo can be run with a minimum screen resolution of 1280x1024, however, a higher resolution is recommended."
