### ISSUE TITLE
Web Search for selected Genes

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1221]
comming from #666 

Users should be able to define and change the search string via the prefs page
we should store the tuples (id category, search string) in the caleydo prefs file.
we need to add default search strings for genes.

Also add a menu item to the general tool-bar on whether selections should be triggered or not.

open issue: multi mappings -> we can load the first resolved id

The primary purpose of the web browser is to get details on the genes. However, creating external links for other entities would make sense as well (e.g., proteins). So the user needs a way to specify the mapping between ID categories and the external search query where we then can just append the selected ID.

For instance, if the user selects a heat map row, he should be able to trigger the external web browser by using the context menu.
For now, I suggest to query genes on http://www.genecards.org/. Any other opinions on that?

**Comment by sgratzl** [comment]
> So the user needs a way to specify the mapping between ID categories and the external search query where we then can just append the selected ID.

so per ID Category the user should be able to specify one or more url patterns + the id type in which the user wants the parameter

> For instance, if the user selects a heat map row, he should be able to trigger the external web browser by using the context menu.

another option would be to use the SelectionInfoView for that, which can act as a central point

**Comment by mstreit** [comment]
Yes, that would be possible as well. I initially suggested to put it in the preferences because users will usually change it only once (if ever). However, I guess both options are fine.

**Comment by sgratzl** [comment]
> Yes, that would be possible as well. I initially suggested to put it in the preferences because users will usually change it only once (if ever). However, I guess both options are fine.

you are mixing two things: 
1. where to define mappings -> preferences, 
2. where to trigger -> (my suggestion) SelectionInfoView

**Comment by mstreit** [comment]
ok. 
yes, triggering the external browser in the selection view makes a lot of sense. an "auto trigger" checkbox could be useful, however, in this case Caleydo should not lose the focus (if possible).

**Comment by alexsb** [comment]
Yes, that's a good place. Do we want to trigger this for

(a) all selected with a button
(b) with double click for a specific selection within the selection
(c) with context menu

**Comment by sgratzl** [comment]
> (a) all selected with a button

the selection info view can show multiple IDCategories at the same time, so there can't be a single button

> an "auto trigger" checkbox could be useful, however, in this case Caleydo should not lose the focus (if possible).

you have to keep in mind, that one the one hand you might have multiple patterns for the same ID Category and on the other hand that if you select a bunch of genes at the same time (which can easily happen) it would trigger all of them
