### ISSUE TITLE
Refactor Selection Tree 

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1224]
This should be a three level tree with the following behavior:
- Level 1: Per ID Category, displaying ID Category plus number of entries of category. E.g., Genes (1500)
- Level 2: Per Selection type, in Selection Type Color, Displaying Selection type plus number of elements of that type, percentage and the three first entries. E.g., Mouse-Over, 1 (0.1%), EGFR
- Level 3: Per Element, showing specific elements 

Level 3 is collapsed by default and is not automatically changed.

**Comment by alexsb** [comment]
Context menu actions for the different levels:

All Levels: Clear Selection (clears all entries of specific selection type)
Level 1: No extra action (here we could in the future plug-in ID Category actions such as selecting the human readable type)
Level 2: Remove Selection type (only if not a default type) 
Level 3: Show in Online resource (see #1221)

**Comment by sgratzl** [comment]
> Level 2: Per Selection type, in Selection Type Color, Displaying Selection type plus number of elements of that type, percentage and the three first entries. E.g., Mouse-Over, 1 (0.1%), EGFR

the initial idea, was to have the three samples in a new line, however according to http://stackoverflow.com/questions/4082082/swt-table-with-variable-row-height-working-on-linux-but-not-mac-windows this doesn't work that well for Windows and Mac systems.

**Comment by alexsb** [comment]
Am I understanding you correctly that it would be hard to have three elements in one row?
I thought this would be a  tree with three leaves

Parent
|-child
|-child2
|-child3

**Comment by alexsb** [comment]
Problem was:

Parent \n
child, child2, child3
|-child
|-child2
|-child3
|-child4
...
|-childN

Here the line after \n requires increased hight. 

Could we do:

Parent 
|-child
|-child2
|-child3
- (expands)

**Comment by sgratzl** [comment]
currently 
Parent (...) child, child2, child3
|-child
|-child2
|-child3
|-child4

is implemented

I don't think that the expand button is useful, as you would need in the same way a collapse counterpart, which would more or less ends up in an additional level.

But we can talk about that

**Comment by alexsb** [comment]
Nice, I like it.

One problem: I can never expand the mouse over as it disappears before I can hit the widget ;). A solution would be that for each ID Category the Mouse Over and Selection remain, also in case of 0 selected items until another ID Category is selected. Alternatively they could always remain but moved downwards so that old ones are no longer visible.

Another issue is that the name of the selected item is not "salient" right now. Two possible strategies:

Parent
| + child1, child2, child3, ...

This could then be expanded.

Alternatively we could show selections of < n (e.g., 4) expanded and only larger ones collapsed.

**Comment by sgratzl** [comment]
> One problem: I can never expand the mouse over as it disappears before I can hit the widget ;). A solution would be that for each ID Category the Mouse Over and Selection remain, also in case of 0 selected items until another ID Category is selected. Alternatively they could always remain but moved downwards so that old ones are no longer visible.

what do you mean by remain. That even if you don't have selected them, that an element should be shown?.

> Another issue is that the name of the selected item is not "salient" right now. Two possible strategies:
> 
> Parent
> | + child1, child2, child3, ...
> 
> This could then be expanded.
> I don't want to add another layer
> 
> Alternatively we could show selections of < n (e.g., 4) expanded and only larger ones collapsed.

that would be an option

another option would be to let the user switch to mode, which is called auto expand, where everything is expanded by default. That could solve your mouse over issues

**Comment by alexsb** [comment]
Remaining - The selection itself shouldn't remain, but the "Selection" or "Mouse Over" header showing "0 Selections"

Auto-expand is bad if you want to mix, e.g., a handful of genes with many samples (StratomeX & Pathway e.g.)

**Comment by sgratzl** [comment]
@alesb 

the pushed version, contains now two strategies: 
1. the first one is to auto expand to the last level, if the number of entries is <= 4
2. if you select a selection type of the category the [default] selection type remain, even it has no entries
