### ISSUE TITLE
Include CCLE Project as Sample Project

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1226]
Focus on pathway data.

**Comment by mstreit** [comment]
Alex, can you point Sam to the CCLE project that should be used?

**Comment by alexsb** [comment]
It's defined in CCLEDataXmlGenerator.

**Comment by alexsb** [comment]
We need to check for permission - I'll take care of that.

**Comment by alexsb** [comment]
Requested rights to redistribute: 

Hi,

we (the Caleydo team) have been using CCLE data for a data visualization and analysis research project together with Novartis. We found that the dataset suits our visualization techniques very well and would like to include the  data as a sample project for Caleydo. We currently provide GBM TCGA data as a sample project and also produce pre-packaged (for one-click-import) TCGA data on a large scale. 

CCLE data would be an ideal additional  dataset, as it also includes compound data. 

If you agree, we would like to host a Caleydo project file containing CCLE data on our web-server which will be accessible for use within Caleydo. We will not give users access to the raw data files and we, of course, will give full credit to the CCLE project.

Caleydo is a purely academic open-source visualization platform (see http://caleydo.org ), developed by Harvard University, JKU Linz, Austria and TU Graz, Austria.

Please let me know if you need more information! We would appreciate your permission.

Kind Regards,

Alexander Lex

**Comment by alexsb** [comment]
Permission granted.
