### ISSUE TITLE
pathway maps (randomly) lose color mapping 

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1228]
Individual pathway bricks in a column sometimes lose the color mapping. I cannot reliably reproduce this but will add comments as I find out more.

The mapping is missing only in the in-column plots but not in the expanded plots.

**Comment by alexsb** [comment]
Please show a screenshot if possible. I've never observed that. Is it possible that the mapping is simply neutral?

**Comment by cpartl** [comment]
I cannot reproduce this.

**Comment by ngehlenborg** [comment]
This is what happened after I changed the color mapping with the histogram (through the DVI because the handles didn't react when I tried to do this directly from StratomeX):

![screen shot 2013-06-19 at 5 26 40 pm](https://f.cloud.github.com/assets/1216518/681926/e43dc6d8-d9bc-11e2-86c6-282c64f0b9ae.png)
