### ISSUE TITLE
Include hierarchization of scores in LineUp

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1231]
We discussed to include a hierarchization of scores in LineUp. For example, mutation status "mutated" and "not mutated" will be shown under the umbrella category "Mutation Status", while cluster number and number of elements will be summarized as "Properties" (might have the word wrong here).

This should clarify differences between queries and properties.

**Comment by alexsb** [comment]
This works well imo. I'm still not convinced that a mutual exclusive otpion for datasets wouldn't be better, because in the end right now that's what I'm always doing. But ok, that's another story. 

The one-pixel line however doesn't work as good as I imagined. Opinions? Suggestions?

**Comment by alexsb** [comment]
Here is what I'm talking about: 

![header](https://f.cloud.github.com/assets/2039375/663575/0f36b15e-d771-11e2-99f1-356f07cd9e5f.png)

Options:
- Keep the line, potentially adding more spacing will help but will cost us 
- Color the whole background -> this will be very colorful and sometimes it will be hard to read text on top
- Color nothing
- Show a gradient quickly fading within 5 pixels - that's probably also a problem with readability

**Comment by mstreit** [comment]
I vote for option 1.

**Comment by alexsb** [comment]
@mstreit  including increasing spacing?

**Comment by mstreit** [comment]
yes, some more spacing. other opinions?

**Comment by sgratzl** [comment]
@alexsb enough space?

**Comment by sgratzl** [comment]
I will close that ticket, if we still need to adjust the visual encoding (spaces), it won't be a critical ticket anymore
