### ISSUE TITLE
Add top-level scroll bars for import dialog

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1245]
In case there is not enough screen space there should be top-level scorll bars on all wizard pages. Right now it's simply clipped, which breaks functionality on smaller screens. 

This is also the default behavior of, e.g., Eclipse preference pages.

**Comment by alexsb** [comment]
Problem is solved on first page, although only to a certain extend. When I make it very small the scroll bar disappears again. However, doing it that small is stupid, so I'm not sure whether we need to fix it.

Problem persists on Categorical Properties page. See screenshot. 

![scrolling](https://f.cloud.github.com/assets/2039375/638198/908edd72-d2b6-11e2-8baf-1c63c5cfaa75.png)

**Comment by alexsb** [comment]
Related problem observed in the "Column Properties" of inhomogeneous dataset. See screenshot

![scrolling2](https://f.cloud.github.com/assets/2039375/638409/665c9ad0-d2bb-11e2-8bd1-b1c162bf05a9.png)

Here I can't even resize the window interestingly. 

This happens when switching form categorical to numerical. Same problem also for the categorical page.

**Comment by cpartl** [comment]
ad1) You probably reduced the size below the required size of the wizard (bottom buttons). The only way to fix this would be to introduce a scrolled composite on the wizard level, which is not smart imo, and I actually don't know how to do that yet. Besides that I agree that this is not really an issue. There should be no reason why one should reduce the size this far and if one has a low resolution like this, I wish him good luck using Caleydo anyways.

ad2) I can not reproduce the problem of the categorical property page.

ad3) Fixed in 28058fa

**Comment by alexsb** [comment]
ad 1) aggreed
ad 2) me neither today
ad 3) doesn't work for me, is even worse. Initial state:

![scrolling3](https://f.cloud.github.com/assets/2039375/644272/d4deeb4c-d389-11e2-91ac-835b72152547.png)

After switching:

![scrolling4](https://f.cloud.github.com/assets/2039375/644276/e2c882cc-d389-11e2-9bdc-8ae623203274.png)

**Comment by cpartl** [comment]
Fixed initial state problem.
Can not reproduce the issue after switching. Scrollbars appear and work nicely. Even tested on 800x600 screen resolution.

**Comment by alexsb** [comment]
The last issue continues to persist. It's not a scroll-bar issue, this happens even if there is plenty of space. If I re-size a tiny bit I don't get scroll bars but the layout corrects itself. 
Before:
![before](https://f.cloud.github.com/assets/2039375/662281/e24c7bac-d751-11e2-97b3-d20f3ac9e28f.png)
After
![after](https://f.cloud.github.com/assets/2039375/662282/ebe05e4a-d751-11e2-9ef5-5a22e8e09fcf.png)

**Comment by cpartl** [comment]
As I do not have this issue, maybe you can play a little with that yourself.  In ColumnDataPropertiesDialog in methods createDialogArea (if the problem occurs at the start) or in showNumericalDataWidgets and showCategoricalDataWidgets you can try to pack or layout the parentComposite or the scrolledComposite. In createDialogArea you can also try to set different height or width hints for the giddata of parent (at end of the method).

**Comment by alexsb** [comment]
That's the best I could get:

![scroll-bar](https://f.cloud.github.com/assets/2039375/730905/b9a06966-e25f-11e2-84b2-23aab8a3beda.png)

**Comment by cpartl** [comment]
attempt to fix it, which works for me, but that was always the case. please check.

**Comment by mstreit** [comment]
works for me
@alexsb Please check!

**Comment by alexsb** [comment]
Worked for me too
