### ISSUE TITLE
Classify color maps for ordinal data as diverging and continuous

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1248]
There should be headings for both.

**Comment by cpartl** [comment]
the question is whether we should show them together, as neutral colors make only sense for diverging schemes. 

So, shall we  display sequential, when no neutral category is selected, and display diverging, when a neutral category is selected? 

If the user has already applied one color scheme, e.g. sequential, and selects a neutral category afterwards, shall we automatically apply a default diverging one?

**Comment by alexsb** [comment]
Yes, great idea. Also the change. 

We should put some text as well:

Showing 'diverging' color schemes since a neutral category was selected. Remove neutral category to show 'sequential' color schemes.

and vice versa

**Comment by cpartl** [comment]
Where should this text be displayed? In the color scheme selection dialog?

**Comment by alexsb** [comment]
Yes. Maybe in the title or as a label on top of the color schemes.

**Comment by alexsb** [comment]
Clarification: title or on top should be:

"Diverging Color Schemes"

Text at the bottom: "Showing 'diverging' color schemes since a neutral category was selected. Remove neutral category to show 'sequential' color schemes." and vice versa
