### ISSUE TITLE
Improve Search Feature

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1258]
interesting features, that would be useful:
- as suggested by @alexsb some more present search for the "primary" label column
- toggle autoselection mode (see @ngehlenborg regarding auto loading of pathways)
- next match / previous match
- wrapped search
- hide not matching items as suggested by @mstreit 
  -> via filtering the ranking is changed, via hiding the ranking is preserved but the not matching elements are hidden

**Comment by sgratzl** [comment]
I'm currently thinking about merging the filter and search options for the categorical and string columns. 

options:
- hide not matching entries
- exclude not matching from ranking <-- filter

@ all any ideas?

**Comment by mstreit** [comment]
how would you search for something special without losing the context?

**Comment by sgratzl** [comment]
> how would you search for something special without losing the context?

the question is how likely it is, that you will search within a column were you already set a filter?

**Comment by alexsb** [comment]
Concerning hiding non-matching elements: I'm not sure whether we should do that as that would be a clear difference to a filter. 

The way I see it: 
- Filter is defined on a per-column basis and removes all non matching elements. 
- Search uses _all_ visible information, does not hide other entries (might gray them out though) and has a next - previous option.

**Comment by mstreit** [comment]
I agree with Alex. We should not merge search and filter.

**Comment by mstreit** [comment]
Again concerning hiding of non-matchin elements:
Let's assume a user wants to investigate all Austrian Universities. In this case you want to somehow get rid of Universities from other countries, while keeping the global ranking information. It might not be helpful to see the 6 Austrian Universities in a new ranking. We need to find a way to support this.

**Comment by alexsb** [comment]
Wouldn't that work with the clear differentiation of filter and search as described above?

**Comment by mstreit** [comment]
@alexsb Yes, I guess. We should try it out. It might be confusing for the user.

**Comment by alexsb** [comment]
BTW: interface-wise the chrome search box rocks. Super-simple and out of the way if you don't need it. Afair there was an option to do such a pop-up widget in eclipse recently?

**Comment by sgratzl** [comment]
> hide not matching items as suggested by @mstreit -> via filtering the ranking is changed, via hiding the ranking is preserved but the not matching elements are hidden

part of #1330
