### ISSUE TITLE
UI Deadlock when continuing after category specification with next instead of finish. 

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1261]
When I go to add groupings after specifying the categories I'm in a UI deadlock. See screenshot: Back, Next and Finish are disabled. 

![deadlock](https://f.cloud.github.com/assets/2039375/638127/c5981f62-d2b4-11e2-8e4c-ebc675a8ae2a.png)

**Comment by cpartl** [comment]
I can not reproduce this.

**Comment by alexsb** [comment]
Me neither today. Will re-open if I re-encounter it. Maybe it was a debug/hot-swap state problem.
