### ISSUE TITLE
Category Properties Layout Improvements

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1262]
- [x] Move buttons to the right of table
- [x] Improve "Neutral Category interface. Suggestions - please comment
  - Use drop-down with "None" and all the options instead of checkbox and dropbdown
  - Add column with radios to table. 
- [x] Revers Color Scheme Order doesn't work for Nominal ATM

**Comment by cpartl** [comment]
A column with radios has the problem that you probably have a hard time selecting "None" without external widgets.

**Comment by cpartl** [comment]
Any further suggestions? maybe separate color specific widgets from other?

**Comment by alexsb** [comment]
Yes. That looks good so far. Maybe a group for the colors and for "Modify Categories"?
