### ISSUE TITLE
Table Layout Improvements

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1263]
Here are some suggestions for improving the appearance and usability of the various tables. Please comment. These are mainly appearance issues, so if something is hard to do we don't have to do it. 
- [x] Decrease size of caption font for rows and columns. 
- [ ] Optimize space for tables - set columns to fit content if enough space is available
- [x] Maximize table width (not sure if that makes sense, but it looks weird to have a lot of gray space next to the table)
- [x] Provide mouse-over for clipped cells (especially headings)
- [x] Unify appearance of row and column headings. Currently Column headings are "buttons" while row headings are not. I'd go for non-buttons.
- [x] Reduce darkness of the alternating row pattern to make it clearly different from row headers

**Comment by cpartl** [comment]
ad2) What does this mean? Should the columns get wide enough to display all of its content without clipping? If so, what is "enough space" then? There is infinite space in a scrollable table.
ad3) The table is always space-filling. Its just that the background of the table is the same as the dialog. I have extended the cell lines to make this obvious for the moment. not sure if that is the ideal solution.
ad4) Done.
ad5) Done, but not with a different gray as we already have a lot of shades of gay in the table (white, black, table header background, text of disabled columns, grid lines)

**Comment by alexsb** [comment]
Looks great!

One issue I have now: when I click a column in the inhomogeneous table it changes it's width, which looks weird. The change is due to the font being made bold.

**Comment by cpartl** [comment]
still don't know about 2)

**Comment by alexsb** [comment]
Don't know what is meant? I meant that we could adapt the column width to fit it's content if there is sufficient space.

**Comment by alexsb** [comment]
I guess that's not necessary. Let's leave it at that and re-evaluate later. Not doing it does have the advantage of a more consistent layout.
