### ISSUE TITLE
Improve download dialog

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1267]
- [ ] Cancel doesn't work (see screenshot)
- [ ] Show file size, if possible.
  ![cancel](https://f.cloud.github.com/assets/2039375/639105/6ed6aa96-d2cc-11e2-9bdf-41529f5f3ec1.png)

**Comment by sgratzl** [comment]
and what should be done if the user press cancel?

 -> from the api side this is a simple RemoteFile part of the StartupProcedure. 
So if the user press cancel, there is nothing to load for Caleydo and the wizard is already gone

**Comment by sgratzl** [comment]
never mind it should work now
