### ISSUE TITLE
querying by mutual exclusivity (gene mutation status)

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1274]
Is this possible? 

If it is not possible, can we add this?

**Comment by ngehlenborg** [comment]
@sgratzl How can I do a mutual exclusivity query?

**Comment by sgratzl** [comment]
> @sgratzl How can I do a mutual exclusivity query?

find similar clusters trigged on categorical data domains is automatically mutual exclusive. see ComputeScoreFilters line 46ff

**Comment by ngehlenborg** [comment]
We need both options: query by best overlap and query by mutual exclusivity. Re-opening to discuss how to implement this. Essentially, we can have multiple different "similarity/distance measures" for retrieval.

**Comment by sgratzl** [comment]
> We need both options: query by best overlap and query by mutual exclusivity. Re-opening to discuss how to implement this. Essentially, we can have multiple different "similarity/distance measures" for retrieval.

we could add another level after "Find large overlap with displayed clusters", where the user can select the mutual exclusive and non-mutual exclusive version.

**Comment by ngehlenborg** [comment]
The second level would be a good option but of course mutual exclusivity only works for case where both the query and the entries in the database have well-defined binary states. In our case this is currently only true for mutation data.

An alternative to an extra level in StratomeX could be to run the overlap query by default and run a second search using the mutual exclusivity measure (resulting in an additional score column in LineUp) when the query is a mutation and mutations are included in the database (of course this could be generalized if we see that we will have other binary data types, e.g. male/female, treated/untreated, etc. - that should be easy to do with the new categorical datatypes).

**Comment by sgratzl** [comment]
> An alternative to an extra level in StratomeX could be to run the overlap query by default and run a second search using the mutual exclusivity measure (resulting in an additional score column in LineUp) when the query is a mutation and mutations are included in the database

I believe that this it not intuitive to use. As in some cases the second score would appear and in others not. Especially as I normally create the query and then select the target database.

> (of course this could be generalized if we see that we will have other binary data types, e.g. male/female, treated/untreated, etc. - that should be easy to do with the new categorical datatypes).

we have them, see #1319

**Comment by sgratzl** [comment]
In the current implementation for binary categorical similar clusters query, i.e. jaccard index on Mutations, a second query column will be automatically created which is the mutual exclusive version.

**Comment by ngehlenborg** [comment]
It seems that both scores are the same, at least in the builds that Alex sent me, can you check this?

![screen shot 2013-06-25 at 11 27 13 am](https://f.cloud.github.com/assets/1216518/703702/085f955e-ddb0-11e2-9fee-dfebe42f7eef.png)

**Comment by sgratzl** [comment]
If I query find similar clusters on the mutated group, I got something like this:

![2013-06-25 19_32_15-caleydo - tcga_gbm cal](https://f.cloud.github.com/assets/4129778/704268/52a644fc-ddbd-11e2-881a-376b75dcb9b7.png)

**Comment by ngehlenborg** [comment]
I think it only works for cases where the query cluster has size 1. See screenshots.

![screen shot 2013-06-25 at 1 40 36 pm](https://f.cloud.github.com/assets/1216518/704324/72453b78-ddbe-11e2-949d-9e43728fd9a5.png)
![screen shot 2013-06-25 at 1 39 26 pm](https://f.cloud.github.com/assets/1216518/704325/72535cb2-ddbe-11e2-8283-d5e4b16d296d.png)

**Comment by ngehlenborg** [comment]
Btw, the mutual exclusivity score is only required when Mutations is part of the database and the query is a mutation. But this is an enhancement that we can add later.

**Comment by sgratzl** [comment]
> Btw, the mutual exclusivity score is only required when Mutations is part of the database and the query is a mutation. But this is an enhancement that we can add later.

this is not as easy to implement as you might think. The columns are independent from the database selection. That means if I you activate a database, there is no possibility up to now that the column creator extension (JaccardScoreFactory) will be notified.

**Comment by sgratzl** [comment]
@ngehlenborg in the second example: what are you exactly expecting to see?

please describe a detailed scenario, as I think I misunderstood some requirements

**Comment by ngehlenborg** [comment]
In the second example the "mutual exclusivity" is perfect (i.e. I expect the best possible score), because there is 0 overlap between patients with MUC1 mutation (= query) and patients with TTN mutation.

**Comment by ngehlenborg** [comment]
I have played around with the new score and as expected, it does what it should be doing. However, the problem is that the score that I suggest does not take into account the size of the overlap between mutated/not mutated, which means genes that are mutated and mutually exclusive in only one patient will have the same score as genes that are mutated in 50% of the patients and are mutually exclusive. This can be resolved by sorting the perfect scores using the # mutated patients column from the metric, but it is an extra step and quite annoying, because the user would basically have to do this all the time.

If we take into account the size of the overlap we basically end up with the Jaccard index between the mutated group (the query) and the non-mutated group in the database. This is what we should do. Additionally, can allow the user resolve multiple perfect scores (= 1) by taking into account the size of the mutated group. It is very unlikely that this will ever be needed, since a perfect score requires that all mutated patients in the query match non-mutated patients in the database entry and vice versa.

However, the original problem reported in https://github.com/Caleydo/caleydo-dev/issues/1274#issuecomment-19986751 (mutual exclusive score identical to the regular Jaccard index) still needs to be fixed. My understanding is that the issue is caused by the fact that the regular Jaccard index will often return the score for the mutated group (=query) vs the non-mutated group in the database as the best result.

I suggest that whenver the mutual exclusivity score is added, we compute JI( q_mut, d_nonmut) = ME score and JI( q_mut, d_mut ) = JI score. Of course it must also be possible to query with q_nonmut, which would result in JI( q_nonmut, d_mut ) = ME and JI( q_nonmut, d_nonmut ) = JI score.

**Comment by sgratzl** [comment]
> I suggest that whenever the mutual exclusivity score is added, we compute JI( q_mut, d_nonmut) = ME score and JI( q_mut, d_mut ) = JI score. Of course it must also be possible to query with q_nonmut, which would result in JI( q_nonmut, d_mut ) = ME and JI( q_nonmut, d_nonmut ) = JI score.

now I'm confused: 

ME is defined as:  `1 - |intersect( q_x, d_x )|/|q_x|`
JI is defined as: `|intersect( q_x, d_y )|/|union (q_x, d_y) |`
with `x, y in {mut, nonmut}`

so the ME was defined for the mut vs mut case. Now `JI( q_mut, d_nonmut) = ME` compares mut with nonmut, which means if all samples in the mutated query are non mutated in the current element, the score will be 0. And `JI( q_mut, d_mut ) = JI score` will be zero, too

btw. I have a bug in the current code, it actually computed: `1 - |intersect( q_x, d_x )|/| d _x|`

**Comment by ngehlenborg** [comment]
Let's just focus on JI as the measure for now.

> so the ME was defined for the mut vs mut case. Now `JI( q_mut, d_nonmut) = ME` compares mut with nonmut, which means if all samples in the mutated query are non mutated in the current element, the score will be 0
- The score should not be 0. Let's assume that the query set are patients that **have a mutation in gene A** and we are comparing this to the set of patients who do **not have a mutation in gene `B`**, i.e. `JI( A_mut, B_nonmut)` and if the mutations in genes `A` and `B` are mutually exclusive, then the intersection between `A_mut` and `B_nonmut` contains as many patients as there are in the smaller of the two sets `A_mut` and `B_nonmut` and `JI( A_mut, B_nonmut)` is greater than 0. 
- You are correct that if the mutations in `A` and `B` are perfectly mutually exclusive, that `JI(A_mut, B_mut)` will be 0, because the intersection of these sets will be 0. This result is expected.

Just to make sure that we are on the same page regarding the definition of mutually exclusive mutations: Two genes `A` and `B` are considered to be mutually exclusive mutations in a patient cohort, when there are no patients that have a mutation in both genes. 

This is of interest when the goal is to identify mutations that are causing a disease (so called "driver" mutations). There are many mutations in patient genomes that are not causing a disease that occur just "randomly" (so called "passenger" mutations). Why are mutually exclusive genes likely to be driver mutations? Consider this basic pathway called "Pathway Alpha":

```
A -> B -> C -> metabolic product alpha
```

If `A` is mutated and not functional, then the `metabolic product alpha` will not be produced. The same holds true if `B` is mutated. Therefore, seeing a mutation in either gene `A` or gene `B` in large number of patients ("large" could be as small as 1% - 2% of a patient cohort) is a good indicator that these mutations might be drivers of the disease (there are many other factors to consider, too). 

Of course we could say the same if we see that both gene `A` and `B` are mutated in a large number of patients, but it is extremely unlikely that this will happen if either one on their own can already cause the disease.

**Comment by sgratzl** [comment]
now three columns are added: 
1. standard Jaccard Index against all groups
2. Jaccard Index but only testing against the Mutated Group if q and d are of the same database
3. Jaccard Index but only testing against the NonMutated Group if q and d are of the same database

that means 1. = MAX(2,3)

**Comment by ngehlenborg** [comment]
It looks like no scores are computed for genes/stratification that are already included in another view (the ones at the bottom from BRAF to NRAS).

![screen shot 2013-07-01 at 11 29 40 am](https://f.cloud.github.com/assets/1216518/731057/4f7a520a-e263-11e2-9af2-c85cd9634d58.png)

**Comment by sgratzl** [comment]
I put that in another ticket, as it is not directly related to mutual exclusivity -> #1371

**Comment by mstreit** [comment]
@ngehlenborg Can we close the issue?
