### ISSUE TITLE
Unify categorical color selection with color selection dialog used at runtime

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1279]
The one you get when you double-click the histogram.

**Comment by cpartl** [comment]
This is also closely related to #1257. We currently only allow to select diverging/sequential/nominal color schemes depending on the data. For numerical data we do not have such a restriction. Additionally: What about the traditional color scheme green-black-red, which is only available through the histogram dialog?

**Comment by sgratzl** [comment]
> traditional color scheme green-black-red

we don't have to stick to ColorBrewer, if we create an interface, like `IColorPalette` we can mix different color palette sources
