### ISSUE TITLE
Naming for startifications added via LineUp is not ideal - DVI uses different approach

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1280]
When I add a stratification via LineUp it's called something like:

"K-Means 5/ CNMF"

When I do the same with the DVI it's called 

"mRNA - CNMF / K-Means 5"  or similar. 

Tour guide should use the same naming strategy. Ideally the naming "algorithm" should be moved to a part of the code where both DVI and LineUp use it, e.g., in the Table Perspective creation.

**Comment by sgratzl** [comment]
LineUp just calls `datadomain.getTablePerspective(recordPerspectiveID, dimensionPerspectiveID);` to get table perspectives as used in your example. There is no special logic behind

**Comment by alexsb** [comment]
There is special logic in the DVI it seems - and that should be unified.
