### ISSUE TITLE
Missing clinical data values in BRCA 2013_04_21 data package for 3.0

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1287]
The clinical variables are listed but they don't seem to contain any data.

![screen shot 2013-06-18 at 11 06 32 am](https://f.cloud.github.com/assets/1216518/669294/df1aaea4-d828-11e2-89bd-bdf9ccc677d8.png)

**Comment by ngehlenborg** [comment]
Hm, this could be a mapping issue, because when I look at the clinical data independently of another stratification I actually get a distribution of values, see e.g. #1290, which was observed on the same dataset.

**Comment by alexsb** [comment]
Could you be specific on how to reproduce?

**Comment by ngehlenborg** [comment]
Download http://dev.caleydo.org/tcga/2013_04_21/2013_04_21_BRCA.cal and try to check survival for a gene mutation.

**Comment by sgratzl** [comment]
download:

http://gdac.broadinstitute.org/runs/stddata__2013_04_21/data/BRCA/20130421/gdac.broadinstitute.org_BRCA.Merge_Clinical.Level_1.2013042100.0.0.tar.gz

daystodeath is almost everywhere NA. 

or take a look at the raw clinical variable data using the table view.

**Comment by ngehlenborg** [comment]
There seems to be indeed a problem with the clinical patient IDs, preventing proper mapping between clinical and other data types.

I observed the same problems with THCA__2013_04_21 (3.0):

**Clinical**

![screen shot 2013-06-20 at 10 06 30 am](https://f.cloud.github.com/assets/1216518/681484/c2552fca-d9b2-11e2-859e-5d15c2dc260e.png)

**mRNA**

![screen shot 2013-06-20 at 10 06 42 am](https://f.cloud.github.com/assets/1216518/681494/dea12030-d9b2-11e2-8cfd-d101fee49063.png)

**Comment by sgratzl** [comment]
> There seems to be indeed a problem with the clinical patient IDs, preventing proper mapping between clinical and other data types.

fixed

**Comment by ngehlenborg** [comment]
What was the problem and how did you fix it?

**Comment by sgratzl** [comment]
it seemed to be that the column order / count within the clinical file is not fix. The problem was that a wrong column was used to resolve the tcga samples. Now it should be dynamically resolved to "patient.bcrpatientbarcode"
