### ISSUE TITLE
column selection via header brick does not clear after adding new pathway column

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1291]
I already had the methylation and the patient.daystobirth columns and then add the pathway column. After I confirmed I had a selection on the pathway column, but when I clicked the headers of the other two columns the selection was stuck.

![screen shot 2013-06-18 at 11 31 57 am 2](https://f.cloud.github.com/assets/1216518/669444/552a9926-d82c-11e2-9ead-b01cb74d6250.png)

**Comment by sgratzl** [comment]
I'm sorry but I can't follow you. Can you rewrite the description and add a step by step description of selection, clicking and so on, please.

**Comment by ngehlenborg** [comment]
No longer able to reproduce.
