### ISSUE TITLE
What does it mean to edit the record perspective filter and what is a record perspective?

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1294]
Terminology seems to be very developer oriented.

![screen shot 2013-06-18 at 12 12 50 pm](https://f.cloud.github.com/assets/1216518/669706/0a4502b0-d832-11e2-8f1f-a6561a44164f.png)

**Comment by sgratzl** [comment]
this is an remnant of the old TourGuide before LineUp. 

In categorical data domains you can exclude specific groups from computation. For strafications you can skip whole stratifications. This is similar to the column filter but on a data domain level.

**Comment by ngehlenborg** [comment]
Do we need this? Can the same thing be done with the column filter?

"record perspective" will not be understood by regular users of Caleydo.
