### ISSUE TITLE
File Open dialog on Mac OS X 10.7 does not work properly

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1297]
This has been an issue for a long time but I never got around to reporting it.

I always need to click on a folder twice (first on the folder I want, then on another folder, and then again on the folder whose content I want to see) to get its content and the "Favorites" part of the sidebar is missing, too (they show up after I click an entry in the file selector).

![screen shot 2013-06-18 at 12 31 24 pm](https://f.cloud.github.com/assets/1216518/669800/9ff9b2cc-d834-11e2-8c13-a490fac60ea6.png)

**Comment by sgratzl** [comment]
I can't do anything about this

as it is a standard SWT widget http://help.eclipse.org/indigo/topic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/swt/widgets/FileDialog.html, which is operating system dependent

-> sorry but wontfix

**Comment by ngehlenborg** [comment]
Can we test this without the file type filter? I see a spinner in the lower left corner that never stops. Maybe it has to do with this.

The dialog is working fine for me in Eclipse.

If we don't fix this most Mac users won't be able to navigate their file system.

**Comment by sgratzl** [comment]
LoadProjectStartupAddon line 201 -> comment it and test it yourself

**Comment by ngehlenborg** [comment]
I reduced the call to the minimum but to no avail, the problem persists. Filed a bug report:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=411064

**Comment by sgratzl** [comment]
well then I move it to 3.1 and assign it to you @ngehlenborg

**Comment by ngehlenborg** [comment]
Reassigned to 3.0 since this needs to be addressed somehow.

**Comment by alexsb** [comment]
A (bad) hack would be a check for the platform and opening the Swing File chooser.

**Comment by sgratzl** [comment]
swing doesn't work as we disable AWT

**Comment by ngehlenborg** [comment]
I need to do more testing on other Macs (maybe it is just on my machine) and if it is a problem on other Macs, then we might have to include a warning message or something like that before the dialog pops up. And mention it in the FAQ etc. If it is only on my machine, I need to figure out what is causing this.

**Comment by ngehlenborg** [comment]
This problem does not occur when launching Caleydo from the latest 3.0 test builds.
