### ISSUE TITLE
What row ID type/class am I supposed to select for some "random" data that I want to load?

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1298]
In this case it is clinical data and each row essentially has a different type.

Could we simply have something like "generic"? There will always be data "types" that we did not know about and there should be a clear way to load those.

![screen shot 2013-06-18 at 12 38 20 pm](https://f.cloud.github.com/assets/1216518/669847/9b858008-d835-11e2-987f-875e1ebf687b.png)

**Comment by alexsb** [comment]
Hit new!

**Comment by ngehlenborg** [comment]
Too complicated for regular users - how should they know what ID class name or what ID type name to enter? What is the difference anyway?

**Comment by alexsb** [comment]
There's 2 pages of documentation on that. The difference is that we're building a relational schema and that needs to be well defined. We could maybe add a unmapped category.

**Comment by ngehlenborg** [comment]
There is not information about where to find those 2 pages. I also doubt that it is a good idea to send users to read 2 pages of documentation if we could address this problem by having some sort of "catch all" data type that works for most applications.

![screen shot 2013-06-18 at 12 59 06 pm](https://f.cloud.github.com/assets/1216518/669954/8be3948e-d838-11e2-80fe-23d8da99bbc5.png)

![screen shot 2013-06-18 at 1 00 29 pm](https://f.cloud.github.com/assets/1216518/669958/99e1770e-d838-11e2-98d7-df2b94beaca5.png)

**Comment by alexsb** [comment]
See the help button ;)

![help](https://f.cloud.github.com/assets/2039375/669998/8321e2c8-d839-11e2-8435-18b6a79ac927.png)

This is important to understand as you have to understand it to create a complex analysis. 

But I agree, there could be a default "Unmapped" category.

**Comment by ngehlenborg** [comment]
Ok, let's introduce "generic (unmapped)" (I think "unmapped" by itself is not that helpful either because you need to read the documentation to understand what that would mean).

Also see #1301 for terminology regarding "ID Class" and "ID Type".

**Comment by cpartl** [comment]
I don't understand this ticket at all, as clinical data is inhomogeneous, the column id type will be disabled when selecting inhomogeneous. If the rows do contain the inhomogeneous identifiers, it is not possible to import such an inhomogeneous dataset at all at the moment. And it will be quite some effort that also involves parsing changes to enable this.

**Comment by alexsb** [comment]
You're right, there's no sense in that for this example. But you could say for miRNA for example, I don't have a variable that I want to map.

I'm not sure whether this is actually a hard problem? We could simply add a text line in the drop down and call it unmapped. In reality we'll handle it as a regular ID type creating a new "Unmapped" every time.
