### ISSUE TITLE
data import dialog and the linked documentation are contradictory

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1301]
Documentation: 

> Both tables contain the same "types" of identifiers, "Sample" and "Gene". We refer to these types as "ID Types"
> ...
> In most cases you won't need to define more complex relationships by yourself, but the predefined "GENE" ID Class is an example: it contains various ID Types such as "Refseq", "Gene Symbol", "David ID", "Ensemble ID", etc., which can all be mapped to each other.

Dialog:

![screen shot 2013-06-18 at 1 20 52 pm](https://f.cloud.github.com/assets/1216518/670083/b82da6bc-d83b-11e2-92f2-ed02da7dad4b.png)

I made some suggestions in the chat since there seems to be indeed quite some confusion about this even among the developers (probably because "type" and "class" are very abstract terms):

> ... we can replace "row/column id class" = "something" simply with "Type = something", e.g. "type = gene" or "type = sample" and replace "row id type" with "identifier = something", e.g. "identifier = TCGA sample identifier" or "identifier = RefSeq ID"

**Comment by alexsb** [comment]
There is no confusion. ID Class = IDCategory. ID Type = IDType.

Row Type and Row Identifier OK for me too.

**Comment by cpartl** [comment]
I'm also fine with the current terminology. In my ears, identifier sounds more like one single ID (which is actually an abbreviation for identifier i think) rather than the "ID Type"...

**Comment by ngehlenborg** [comment]
Please put your I-have-never-written-a-line-of-code-in-my-life-hat on for a second and try to understand the difference between "identifier type" and "identifier class".

I hope you see that I am playing devils advocate here (and in many other tickets, too) - but we want to make sure that our users understand the software and can use it. Otherwise it will be hard to make this a success.

**Comment by cpartl** [comment]
Renamed in importer. The documentation needs to be updated, but this is a more general thing as new screenshots have to be made etc.
