### ISSUE TITLE
Provide chart (histogram) for small multiple categorical data.

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1303]
Replacing K-M Plots in these cases

**Comment by alexsb** [comment]
This is the alternative solution to #1319. I think the other solution is (a) more important (b) easier to implement (c) more in the spirit of StartomeX. 

This is actually a generalization of what we consider as dependent columns - this would be equally possible with all other datasets. Moving to 3.1, re-evaluate then.

**Comment by ngehlenborg** [comment]
Here is a good example why we need this urgently: K-M plot shows clear differences in terms of age between tumor stage but it is very hard to interpret the distributions. This is from the THCA data set.

![screen shot 2013-06-25 at 10 40 04 am](https://f.cloud.github.com/assets/1216518/703189/77162c48-dda5-11e2-8f76-f15852e8529a.png)
