### ISSUE TITLE
gray-only Kaplan-Meier plots have less functionality than the original ones

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1304]
The colored ones used to work just fine and now it doesn't. 

Whatever the solution, we need one that allows users to compare:
(1) the how survival in one group to all others (could be done with extra curves in small multiples)
(2) the survival of a subset of two or more curves to each other within the subset (requires color or labels in header brick or detail view - but ideally in the header brick because the detail view kicks out columns ...)

All this ideally without walking the mouse around, this is very tedious.

**Comment by alexsb** [comment]
As I said on skype I'm extremely reluctant to re-introduce colors (for aesthetic reasons, but also for practical ones: we use color for many things already and it would be better to not use colors twice). 

Showing all lines in all multiples is definitely an option for me. 

I don't fully understand (2). However, I think if you can't recognize a curve by it's shape and magnitude it's probably a very small difference.

**Comment by ngehlenborg** [comment]
Regarding shapes: the problem with the shape of survival curves is that they are often quite similar (by design).

Here is an example for (2). I want to compare the selected, the hovered and the curve between them (2nd from top). I can't tell which of the many gray curves represents the one between the hovered and the selected.

![screen shot 2013-06-21 at 11 29 23 am](https://f.cloud.github.com/assets/1216518/687888/81d61970-da87-11e2-90b8-793d4814e123.png)

**Comment by alexsb** [comment]
Z-ordering of selections
