### ISSUE TITLE
bar for normal copy number is very hard to see in LineUp/TourGuide

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1305]
Could we use a darker gray for "normal"?

![screen shot 2013-06-19 at 3 19 49 pm](https://f.cloud.github.com/assets/1216518/677152/5c4ce3be-d915-11e2-96ec-62e9b3fb1f02.png)

We probably have the same issue with mutation calls.

**Comment by sgratzl** [comment]
see #1275 --> the colors are determined using a colorscheme (ColorBrewer.RdBu)

@alexsb how should we handle this?

**Comment by alexsb** [comment]
Two options:
- outlines, either always, or if we notice that a color has low saturation or high brightness
- darker colors

This is an issue for the histogram, etc too. We should solve this consistently.

**Comment by alexsb** [comment]
The histograms and bars in enRoute use outlines btw. Looks nice.

**Comment by alexsb** [comment]
Solved this problem in the histogram with outlines. 

![color3](https://f.cloud.github.com/assets/2039375/683488/68d4c2de-d9e0-11e2-8036-047c23c3615b.png)
![color2](https://f.cloud.github.com/assets/2039375/683491/70d49c3e-d9e0-11e2-87bd-9aaed579a4a9.png)
![colors](https://f.cloud.github.com/assets/2039375/683492/70e3d8ac-d9e0-11e2-873d-459823d4b7b9.png)

Might not work as good in this case though, but worth a try.

**Comment by alexsb** [comment]
Works great!
