### ISSUE TITLE
color scheme for "summary heatmaps" is not updating

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1307]
They are using the color map that was set when the application was launched.

![screen shot 2013-06-20 at 3 51 35 pm](https://f.cloud.github.com/assets/1216518/683588/e476228c-d9e2-11e2-8d50-4a4d8b80d19e.png)

**Comment by alexsb** [comment]
@cpartl, can  you please investigate. The remainder of this problem is a display list issue in the layout. I've added this to the end of StratomeX:

```
    @ListenTo
    public void updateColorMapping(UpdateColorMappingEvent event) {
        layoutManager.setRenderingDirty();
    }
```

The event arrives, but the Layout Renderer is not set dirty.
