### ISSUE TITLE
once a brick has been split, it will re-appear as a split brick even after removing and adding the corresponding column again

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1310]
The splitting should be reset as soon as the column is removed.

**Comment by alexsb** [comment]
That's not clear. What it the splitting was deliberate and the user wants to preserve it. However, we should probably create a copy of the perspective the first time something is split. 

Moving to 3.1

**Comment by ngehlenborg** [comment]
Yes, we definitely need a way to get back to the original stratification. Creating a copy would be a good solution.
