### ISSUE TITLE
Colors are gone for copy number and mutation status data

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1316]
See screenshot

![colors_gone](https://f.cloud.github.com/assets/2039375/687344/991d52f6-da78-11e2-9d76-14a9f6b7bae9.png)

Notice that the colors are still there in the histogram where I use the colors directly from the categories. 

Not sure whether to assign me, @cpartl @mstreit or @sgratzl 

Will investigate later.

**Comment by sgratzl** [comment]
for which project?, latest sample project?

**Comment by alexsb** [comment]
Did you replace the sample project over night? It works now.

**Comment by sgratzl** [comment]
I replaced it on Wednesday, due to the bug fixed in 9b1701835d01ef07e297f2933adbf2d49123ac31
