### ISSUE TITLE
Categorical Normalization

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1324]
```
if (categoricalClassDescription.size() > 1) {
  int numCategories = categoricalClassDescription.size() -1 ;
  if (categoricalClassDescription.getCategoryProperty(unknownCategoryType) != null) {
    numCategories--;
  }
}
```

I don't know whether two times -1 is correct, as I get for the binary categorical (gender) a normalized score of 2

**Comment by alexsb** [comment]
@sgratzl  - I looked into this. It should be -1 twice, since this is not about the number of categories but the number of spaces between the categories. E.g. for mutation, where you have 0 and 1 there is one "space" in between. I think you changing this causes #1328. I'm testing this right now - but what was the reason you changed it?

**Comment by sgratzl** [comment]
maybe you are right, but please ensure that the normalized value will be always [0...1], especially as in my buggy "gender" case, where I originally got a normalized value of 2

**Comment by alexsb** [comment]
Yea, I added an assertion to check it. I think we'll have to re-build the projects for 3.0 though. #1326 is probably also cause by that. Now that I've fixed the normalization I get exceptions for the datasets.

**Comment by sgratzl** [comment]
latest newly build tcga gbm sample project:

```
Normalization failed for org.caleydo.core.data.collection.column.container.CategoricalContainer@1ddc0fb5. Should produce value between 0 and 1 but was 1.5
    at org.caleydo.core.data.collection.column.container.CategoricalContainer.normalize(CategoricalContainer.java:245)
```

**Comment by sgratzl** [comment]
just try to load the project and you will get it, 

happens for the clinical variable with: `[NA, UNKN@WN, hispanic or latino, not hispanic or latino]` as properties

as well as gender: `[UNKN@WN, female, male]`
