### ISSUE TITLE
colors for copy number categorical are wrong

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1328]
NORMAL is now lightblue, but only in the brick. In the histogram and in LineUp the colors are correct.

![screen shot 2013-06-24 at 1 25 27 pm](https://f.cloud.github.com/assets/1216518/696900/2e77042e-dcf3-11e2-97d7-45c584f65755.png)

**Comment by alexsb** [comment]
This is because the heat map, which is used as the underlying implementation, uses the color based on the mapping of the normalized values. This was also the cause in the histogram.
