### ISSUE TITLE
Add possibility to filter elements without updating the ranks

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1330]
Two modes would be useful: 
- hide filtered elements
- update ranks according to filtered list (that's how it is realized atm)

Use case where option 1 is important:
Analyze all universities in a specific country in a global world context.

**Comment by sgratzl** [comment]
I think that can wait till 3.1 or be more precise, it doesn't have to be in 3.0.x

**Comment by mstreit** [comment]
That's independent of the 3.0.x release. We need it to cover Oliver's University ranking use case.
