### ISSUE TITLE
support loading of full expression/methylation/RPPA/etc. matrices

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1334]
This is important for instance for pathway mapping.
- [ ] display only "genes" used for clustering in heatmap bricks
- [ ] test if large data packages load on computers with "normal" amounts of memory
- [ ] build two sets of TCGA data packages (full data, selected data)

**Comment by alexsb** [comment]
Duplicate of #1216 (scheduled for 3.1)
