### ISSUE TITLE
double-click in LineUp database selection should select only the double-clicked item and deselect all others

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1336]
That would make selecting a particular datatype more convenient.

**Comment by ngehlenborg** [comment]
When a selected dataset is double-clicked it is also deselected (it should be the only one left selected in this case).

**Comment by sgratzl** [comment]
I worked like that on my windows system but I will take a look at it

**Comment by sgratzl** [comment]
the current implementation is: 
 if you double click on a data base it will activated and all others deactivated, regardless whether the double-clicked element was activated or not

**Comment by ngehlenborg** [comment]
I can't confirm this on my Mac. If I double-click a selected data set it will be deselected afterwards (along with all others).

**Comment by sgratzl** [comment]
sorry I meant now the it is like that after: 5cef9fbfd87e3f16cbafa0ed7f0f1a51155d2491

**Comment by ngehlenborg** [comment]
Thanks, that fixed it.
