### ISSUE TITLE
mark or remove metric categories when filter is applied to data type

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1339]
In this example I removed NORMAL, hetero del, homo del from the list of categories in copy number, but it is hard to see this in the interface. How about removing the corresponding columns from the copy number metric or mark them somehow, e.g. gray column label or add an asterisk.

![screen shot 2013-06-25 at 2 20 30 pm](https://f.cloud.github.com/assets/1216518/704593/19111a08-ddc4-11e2-8a39-b77c4a2a9530.png)

**Comment by sgratzl** [comment]
> e.g. gray column label or add an asterisk.

removing may lead to distortions. But you have to enable / disable the database after you updated the filter to see the effect
