### ISSUE TITLE
after changing the dataset selection for the database the filters on the "Stratification" column should be reset

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1344]
Otherwise users may quickly end up with empty result lists (this is happening to me all the time).

There should also be a visual indicator in the column header when a filter is set (right now I have to hover over the header to see the if a filter is set).

**Comment by sgratzl** [comment]
if you expand the headers to see the histograms you will already see, something like Filter: <None>

**Comment by ngehlenborg** [comment]
But I usually don't have the histograms expanded for space reasons. Maybe we could just add an asterisk to the label when a filter is active? Or just display the filter icon (active, so that users can directly edit the filter by clicking on it)?

**Comment by sgratzl** [comment]
reset filter on activate data set + simple filter icon (no interaction) is implemented. To implement the interaction I will need more time.

**Comment by sgratzl** [comment]
extracted what is missing to: #1674
