### ISSUE TITLE
it should be possible to change the color assigned to a data set

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1345]
When loading new datasets they are randomly assigned a color that might clash with other, unrelated data. 

A quick initial fix could be to assign gray by default.

**Comment by cpartl** [comment]
Also related to #1257. 
Which, if not all of the following ways to change colors of a dataset are interesting?
- Apply a custom color using a color picker
- Apply a different color from the color scheme used for datasets
- Apply a different color scheme to all datasets
  ...

**Comment by alexsb** [comment]
I'd suggest we present the data sets in a list with the current color scheme. The interface should be the same as for picking categorical colors. The user should be allowed to pick any ordinal color scheme, including the default dataset colors and the color brewer colors.

When double-clicking the color in the categorical import right now you get a color chooser. Instead it would be great to show only the colors in the set, but add a button custom color, which would go to the free color chooser. (This is also the desired behavior for the categorical import).
