### ISSUE TITLE
identifier trimming when the interesting part is neither prefix nor postfix of the original string

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1346]
I've been trying to map ids like `tcga-ab-1234-01a` to `ab-1234`. Is that possible with the current mapping tool?

**Comment by alexsb** [comment]
That shouldn't be an issue. It should work with the default regex - if it doesn't, we can fix it to thatke this as well.

**Comment by ngehlenborg** [comment]
When I tried this yesterday it didn't work with the default regex. Tagged as bug.
