### ISSUE TITLE
change how bricks are rendered

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1347]
- [x] make sure that background and brick can distinguished everywhere
- [x] indicate band height representing 100% of the elements in the brick
- [ ] consider removing "fuel bars"

![screen shot 2013-06-27 at 9 45 09 am](https://f.cloud.github.com/assets/1216518/716123/f18cea58-df2f-11e2-8ef6-f83646d0fb6c.png)

**Comment by alexsb** [comment]
layout improved, including indicators where is docked. Fuel bar stays.
