### ISSUE TITLE
load GENE/SAMPLE scoring dialog is too small

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1353]
My resolution is 1680 x 1050 but the dialog only shows the first few lines of the table and there is no way to resize the dialog.

![screen shot 2013-06-30 at 2 53 43 pm](https://f.cloud.github.com/assets/1216518/727706/8d2ef2d4-e1b6-11e2-9a77-2cb3739a6f30.png)

**Comment by alexsb** [comment]
This seems to be mac specific - for me that fits nicely and I can resize.

**Comment by ngehlenborg** [comment]
That's possible. The same problem also exists with the load grouping dialog and the load grouping scoring dialog.

**Comment by alexsb** [comment]
Actually that was a false alarm. Mixed up the dialog, same problem for me.
