### ISSUE TITLE
adding new score column to LineUp through score import messes up metric separators

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1355]
The new column is the one named "THCA ...".

![screen shot 2013-06-30 at 3 02 42 pm](https://f.cloud.github.com/assets/1216518/727724/0a7660a0-e1b8-11e2-95ed-11047fe44dbf.png)

**Comment by sgratzl** [comment]
if you meant the distorted Mutation Metrics green line -> fixed

**Comment by ngehlenborg** [comment]
Not only the green line. The (regular) metrics header seems to overlap with the THCA-Mut_BRAF column.
