### ISSUE TITLE
band alignment is broken after query with header brick ("Find based on similarity to displayed cluster").

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1356]
![screen shot 2013-06-30 at 5 01 15 pm](https://f.cloud.github.com/assets/1216518/727869/3f8a7438-e1c8-11e2-9cb2-7dc4c60a7096.png)

**Comment by ngehlenborg** [comment]
This also seems to be happening when inserting from "Browse List". Tagged critical.

![screen shot 2013-06-30 at 5 31 58 pm](https://f.cloud.github.com/assets/1216518/727919/9ed697d8-e1cc-11e2-84b3-250adb796e62.png)

**Comment by alexsb** [comment]
I can't reproduce.

**Comment by ngehlenborg** [comment]
Here's another example. Fresh StratomeX:
1. Use "+" to add new stratification with "Browse List".
2. Use "+" to add new stratification with "Browse List" (from different data set).

![screen shot 2013-06-30 at 5 52 03 pm](https://f.cloud.github.com/assets/1216518/727948/59ede07e-e1cf-11e2-9ad0-05388b330a3c.png)

**Comment by ngehlenborg** [comment]
It turns out that this is caused by duplicate patient ids (we were loading a file that distinguished the TCGA sample type and by slicing off that part we ended up with duplicate ids):

```
...

TCGA-BJ-A2N7-11 1   0.450453143563209
TCGA-BJ-A2N7-01 1   0.308974068451991
TCGA-BJ-A2N8-11 1   0.459131504209059
TCGA-BJ-A2N8-01 1   0.215490029342552
...
```
