### ISSUE TITLE
Use nominal color scales for string categories by default. 

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1358]
Right now the two-color red-white color scale seems to be used. This should be replaced with a nominal scale.

**Comment by ngehlenborg** [comment]
The same holds for nominal integer categories.

**Comment by alexsb** [comment]
But for integers it makes sense to assume an order, so I'd default integers to ordinal

**Comment by ngehlenborg** [comment]
But I explicitly declared them to be nominal categorical data.
