### ISSUE TITLE
clicking the "cluster genes button" in the hover menu of the header brick shrinks the header brick

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1359]
This is just odd. The screenshot is the state after clicking the button. The bricks shrinks as soon as the dialog pops up.

![screen shot 2013-06-30 at 5 24 52 pm](https://f.cloud.github.com/assets/1216518/727907/e0ccab24-e1cb-11e2-8186-03ccc0a12e6f.png)

**Comment by alexsb** [comment]
Works for me.
