### ISSUE TITLE
Lineup doesn't add newly loaded datasets

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1361]
They are added only on re-opening lineup

**Comment by sgratzl** [comment]
can you give the dataset data to load, as it works for me in a simple test + in which LineUp instance it should appear

**Comment by sgratzl** [comment]
I fixed a bug, where you coudn't select newly added data domains in LineUp.

**Comment by alexsb** [comment]
The clinical dataset in 

~/Dropbox/Caleydo/data/tcga/20110728/gbm/clinical/clinical_patient_public_GBM.txt

with the default import settings on top of the sample project causes this problem.

**Comment by alexsb** [comment]
I still had this issue when I imported the previously specified file again.

**Comment by sgratzl** [comment]
when you import that file, with which default settings, which columns, which data types,... it doesn't work, and where should appear what

**Comment by alexsb** [comment]
Minimal effort: no changes at all to the defaults. I just import it as inhomogeneous. It should turn up as clinical_public in the main lineup - which it does only after closing and re-opening lineup.

**Comment by sgratzl** [comment]
it still works for me, leaving LineUp open all the time: 
![2013-07-02 21_29_44-](https://f.cloud.github.com/assets/4129778/738841/eee61b40-e34d-11e2-9e32-f45e255d78df.png)

**Comment by sgratzl** [comment]
I think I found the bug, its a concurrency problem. Therefore when I debug the code I couldn't find it. 

The problem is that the NewDataDomainEvent is triggerred as soon as the data domain is created and not when it is fully loaded.

**Comment by sgratzl** [comment]
part of 4e147ba8b63151b7e8d229e49c45710a0f5e647d kepler_branch

-> new event: NewDataDomainLoadedEvent 
-> fixed the same bug for the DVI
