### ISSUE TITLE
clicking the "cluster genes button" in the hover menu of the header brick creates as new stratification in LineUp

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1362]
Even when I cancel the clustering I get a new oddly named ("Perspective_...") stratification in LineUp for that dataset.

![screen shot 2013-06-30 at 5 42 21 pm](https://f.cloud.github.com/assets/1216518/727934/2ec1b584-e1ce-11e2-86eb-3a096119b3be.png)

**Comment by alexsb** [comment]
It's a feature if you do cluster. It shouldn't happen if you cancel, but we'll live with that for 3.0.
