### ISSUE TITLE
datasets with duplicate sample ids cause band misalignment

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1363]
I'm not sure what the best way would be to fix this, but probably we should generally disallow duplicate (or n-plicate) ids in datasets, e.g. by only using the first/last instance found at import time and show a warning to the user that duplicate entries were found and all but the first/last one were ignored.

The effect of this is documented in #1356.

**Comment by mstreit** [comment]
we could handle this with our multi-mapping mechanism that we also use for genes atm

**Comment by mstreit** [comment]
@ngehlenborg Your suggested solution would mean that we randomly throw out the tumor OR the normal tissue for that patient. I guess the order of duplicates is not always the same.

**Comment by ngehlenborg** [comment]
@mstreit Yes, but in the case of TCGA we can probably handle this by using longer ids (if they are available in most outputs)

**Comment by ngehlenborg** [comment]
In the case of TCGA we will have issues with the clinical data which is only mapped to the patient level but can't be resolved directly to samples identified with a sample type. Multi-mapping might indeed be required.

**Comment by alexsb** [comment]
One solution would be to implement #949

**Comment by ngehlenborg** [comment]
For the time being, we should only keep one entry per patient per data type active to prevent effects as described in the comments of #1577. I would prefer losing some data over losing my sanity.

Additional entries for a given patient could be removed in a post-processing step after loading.
