### ISSUE TITLE
view names are not stored when project is saved

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1367]
When I saved the project I had two StratomeX views named "StratomeX A" and "StratomeX B".

When I opened the saved project, the view names are reset to "StratomeX" and "StratomeX (2)". A fresh StratomeX view "StratomeX (1)" is created as well.

**Comment by sgratzl** [comment]
> A fresh StratomeX view "StratomeX (1)" is created as well.

juno bug

**Comment by mstreit** [comment]
still not fixed in Kepler. 
It's weird, the correct names show up for a sec and are then replaced with the default names again.

**Comment by sgratzl** [comment]
> still not fixed in Kepler. 

but you don't, see: 

> A fresh StratomeX view "StratomeX (1)" is created as well.

that was a juno bug
