### ISSUE TITLE
Internal IDs visible in importer

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1372]
This is the content of TCGA_SAMPLE dropdown box in the import dialog:

![tree](https://f.cloud.github.com/assets/2039375/732586/6139b238-e286-11e2-80dd-f0678dcb6d4c.png)

This could be either because it's not set to private IDs or because the drop-down doesn't honor them.

**Comment by alexsb** [comment]
To reproduce load the sample project and add a file.

**Comment by mstreit** [comment]
needs to be tested before it can be closed

**Comment by mstreit** [comment]
Tested with a newly generated TCGA project. Tree entries are gone now.
