### ISSUE TITLE
Investigate merging problems

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1374]
Whenever I had to merge between entourage and develop it was pure hell!!! meaning that I got no help in resolving anything what soever but instead ended up with the two versions on top of each other. 

I assume this is related to some whitespace operation, which, if I remember correctly you have automated somehow. 

This seems relevant: http://stackoverflow.com/questions/3124594/git-all-the-file-marked-as-conflict

**Comment by sgratzl** [comment]
>  if I remember correctly you have automated somehow. 

I talked about that and set it correctly for the paper repositories, but never for caleydo-dev

**Comment by sgratzl** [comment]
Try to merge the eclipse_kepler branch, if you have the same issues here. I want to test, whether this is branch specific or a general problem
