### ISSUE TITLE
Enable copying to clip-board of IDs out of Selection Info

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1376]
I just needed this to debug something, but I assume that this would be very helpful. Depending on how much work it is (I assume very little) this would be nice for 3.0.

**Comment by ngehlenborg** [comment]
Yes, would be very nice.

**Comment by alexsb** [comment]
This should maybe go everywhere where we currently can export identifiers (and probably can use the identical implementation, but instead of to a file writes to the clip-board). Why not allow "Copy Identifiers" on the Brick. 

We could also thinks about copying genes and samples using multiple entries "Copy Sample IDs" and "Copy Gene IDs" - but I'm not so sure about that.

**Comment by sgratzl** [comment]
> This should maybe go everywhere where we currently can export identifiers (and probably can use the identical implementation, but instead of to a file writes to the clip-board). Why not allow "Copy Identifiers" on the Brick.
> 
> We could also thinks about copying genes and samples using multiple entries "Copy Sample IDs" and "Copy Gene IDs" - but I'm not so sure about that. 

that is a different ticket
