### ISSUE TITLE
The width of the histogram should be same as the dataset info view width

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1387]
At the moment the histogram is larger than the info view

**Comment by mstreit** [comment]
![490eaa32-e34f-11e2-8740-a77398db7482](https://f.cloud.github.com/assets/4129755/743312/3abb46e8-e3e5-11e2-9eb4-855a528622f4.png)

**Comment by alexsb** [comment]
Duplicate of / related to #1379

**Comment by mstreit** [comment]
I think that's not a duplicate, but let's see.

**Comment by alexsb** [comment]
It's not a duplicate :)
