### ISSUE TITLE
Find a better replacement to calculateNumberOfLinesInFile

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1390]
up to now to get some kind of progress `calculateNumberOfLinesInFile` is used. 

However, that methods just scans the files and counts the number of lines. Therefore, we are parsing the same (big) file twice, which takes some time. 

An alternative would be use as an indication the size of the file in bytes and use the byte read as indicator.

**Comment by mstreit** [comment]
Good point.
That code was even written before I joined the project ;)

**Comment by sgratzl** [comment]
one problem up to now is that the TabularDataParser uses the information explicitly to setup all its column containers (= arrays)

**Comment by alexsb** [comment]
Yes. The progress uses it only because it's convenient. We'll have to re-work that. This will also allow us to take care of duplicate IDs.
