### ISSUE TITLE
Update splash design

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1391]
Extracted from #1381

**Comment by sgratzl** [comment]
but keep the file type restriction in mind: see https://github.com/Caleydo/caleydo-dev/wiki/Eclipse-RCP-FAQ

**Comment by alexsb** [comment]
Here's the current state: 

![splash3](https://f.cloud.github.com/assets/2039375/754073/d6a4b596-e57d-11e2-9d61-568bb1e5e043.png)

**Comment by mstreit** [comment]
Ubuntu Unity 64-bit
![image](https://f.cloud.github.com/assets/4129755/754089/0c7eb54a-e57e-11e2-92bc-f5f3b12faaf6.png)

**Comment by sgratzl** [comment]
windows 7 64 bit 96dpi
![2013-07-05 16_20_56-eclipse](https://f.cloud.github.com/assets/4129778/754102/4fe976e4-e57e-11e2-909d-0a99ff78a76c.png)

**Comment by ngehlenborg** [comment]
Still tiny on the Mac (and the version string doesn't show up for quite some time):

![screen shot 2013-07-05 at 10 36 40 am](https://f.cloud.github.com/assets/1216518/754174/62bfd860-e580-11e2-9f67-921ef5d722ad.png)

**Comment by alexsb** [comment]
Fixed appearance for now, redesign comes later

**Comment by alexsb** [comment]
Fixed with release 3.0.3
