### ISSUE TITLE
Rename org.caleydo.vis.rank plugin to org.caleydo.vis.lineup

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1397]

**Comment by sgratzl** [comment]
LineUp is the visualization technique, Tourguide is one implementation using scores, data domains and so on. So from my point of view, we should stick with that plugin name

**Comment by mstreit** [comment]
We had a long discussion about this a couple of days ago. However, let's keep the name for now.

**Comment by mstreit** [comment]
But then org.caleydo.view.rank can be renamed.

**Comment by mstreit** [comment]
@sgratzl Should we do that now?

**Comment by sgratzl** [comment]
we could rename the vis plugin to lineup but I will wait till we decide on a repository structure
