### ISSUE TITLE
Dynamically set data in table

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1402]
In essence it would make sense to have an implementation similar to the dataset info view that switches data domain and table perspective as they are selected. The drop-down method for selecting datasets is not convenient and doesn't make too much sense, especially if one considers the table mainly as a support view.

**Comment by sgratzl** [comment]
I don't know, whether that really makes sense. I think #1401 will be sufficient.

**Comment by alexsb** [comment]
Agreed.
