### ISSUE TITLE
Rename caleydo-dev to caleydo 

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1404]
With the release we should also make the repository public. Should we rename it to caleydo instead of caleydo-dev?

**Comment by sgratzl** [comment]
should we rethink the repository(ies) structure

**Comment by alexsb** [comment]
Yes, that goes along with it. At this point I'd simply publish the whole caleydo-dev. Future plug-ins could be in separate repositories to keep them private and later be integrated in the main repo. If we want to make some major changes we don't want to publish from the caleydo main repo we could fork it. 

I think eclipse works well for that. You can have repositories independent of workspaces.

**Comment by alexsb** [comment]
We've decided: rename to caleydo and make public
