### ISSUE TITLE
Different band widths for same number of patients?

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1409]
Is there a way to make this easier to interpret? The amount of orange between cols 1 and 2 is much less than between cols 2 and 3. 

Could we add a "proportional" mode that scales all independent columns to a height relative to the overall data set size?

![screen shot 2013-07-05 at 9 44 46 am](https://f.cloud.github.com/assets/1216518/753908/7eec6e4c-e579-11e2-9944-2accab87eebc.png)

**Comment by alexsb** [comment]
Isn't that the same as #834

**Comment by ngehlenborg** [comment]
Issue #843 describes is one possible solution, there might be others, too.

**Comment by alexsb** [comment]
I think #834 is something we definitely need to do, and I think it's not going to be too hard.
