### ISSUE TITLE
In Importer: use nominal as default for string categories, ordinal for int categories. 

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1410]
That's the way it's currently handled in the back-end.

**Comment by cpartl** [comment]
Currently we use only strings for categories in importer. That way the user does not have to choose int or string and there seems to be no real downside for this (except maybe more space) atm. Should we just guess the default type (ordinal/categorical), or should the int/string also be reflected in the datastructure, which would also require additional gui elements?
