### ISSUE TITLE
make StratomeX view scrollable?

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1411]
![screen shot 2013-07-05 at 10 56 53 am](https://f.cloud.github.com/assets/1216518/754271/3738fa34-e583-11e2-8957-077dccd1cb41.png)

**Comment by alexsb** [comment]
No. We'll move columns to the context area instead.

**Comment by mstreit** [comment]
But we should still define a reasonable minimum width (and height).

**Comment by ngehlenborg** [comment]
We could offer both scrolling and auto-removal and the user could choose which one to use in the preferences (scrolling could be default). A use case for scrolling is when the there is a natural order in the stratifications (e.g. based on time).
