### ISSUE TITLE
Caleydo doesn't continue loading when focus is not on the window

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1413]
To reproduce start Caleydo and click another window. Confirmed on Linux and Mac.

**Comment by mstreit** [comment]
works for me

**Comment by mstreit** [comment]
I have observed the problem again a couple of times.

**Comment by sgratzl** [comment]
to be more precise:

during the startup of the workbench itself, starting with a grey empty window, if you know click on another window, the start process stops.

It may have to do something with the sample project as it seem to work with other ones

**Comment by sgratzl** [comment]
the reason is that eclipse is waiting till the window is getting active. 

I don't know why but it's automatically getting active on my windows system. 

Nevertheless I checked in some strange code, that will automatically setting the next shell active.

@mstreit please test

**Comment by mstreit** [comment]
I was able to stop it again

**Comment by sgratzl** [comment]
I have no idea how to fix that, especially as it works on my windows system. We could just add a note to the website and that's it. 

In addition we should test, whether it occurs just in our developing environment or even in the release

**Comment by mstreit** [comment]
Yes, the problem occurs also in the release version. 
We should mention it in the release notes.
I leave the issue still open but remove it from 3.0.1. Maybe the next RCP update solves the problem.

**Comment by sgratzl** [comment]
It may has something to do with our custom loading dialog as they use the same display, but I'm not sure about that
