### ISSUE TITLE
Caleydo packages for TCGA UCEC has no clinical data

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1419]

**Comment by mstreit** [comment]
effects only last run

**Comment by mstreit** [comment]
We should think about adding some kind of control mechanism that gives us warnings when datasets are missing. Maybe a generation report would make sense.

**Comment by alexsb** [comment]
Yes, that should be a separate ticket.

**Comment by sgratzl** [comment]
I'm currently uploading the new packages for May and April, rest will follow soon

You have to clean the cache, as the modification dates are not automatically checked
