### ISSUE TITLE
Add "New Project" data menu entry

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1420]
The new project menu entry should open the new project wizard.

**Comment by mstreit** [comment]
also add toolbar item

**Comment by alexsb** [comment]
What do you mean by new project? Discard the loaded data?

**Comment by mstreit** [comment]
Yes. We already have an "open project" menu entry that discards the loaded data.

**Comment by alexsb** [comment]
We don't actually need an icon and a tool-bar menu for things like this. Gimp, Inkscape etc do very well without that. I think the toolbar could be cleaned up to only include stuff you do on a regular basis instead.

**Comment by sgratzl** [comment]
> Gimp, Inkscape etc do very well without that

In my version, I have in both tools a menu item for that

**Comment by alexsb** [comment]
You're right, Inkscape has them, but my gimp doesn't. I'm observing though that I'm not using these buttons. Does any of you?

**Comment by sgratzl** [comment]
I don't see the need for an icon in the toolbar, too. But at least a menu entry would be useful.

**Comment by mstreit** [comment]
Ack. We need a menu entry but no toolbar icon.

**Comment by mstreit** [comment]
Rename "restart" to "New Project..."

**Comment by sgratzl** [comment]
the icon size doesn't match the other icon sizes (24px)
