### ISSUE TITLE
Add hide group from column feature

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1430]
After the import of Nature clustering stratifications, the biggest group is often NA. As the NA patients are usually split up uniquely in all other groups of a compared stratification, StratomeX gets unnecessarily cluttered.

**Comment by alexsb** [comment]
I'd rather do this on the data side. I could add NA as an unknown type to the parser?

**Comment by alexsb** [comment]
Or it could be manually defined in the TCGA import

**Comment by mstreit** [comment]
In some cases it is useful to have NA as a separate group. A soft hide may be better. However, the scoring would also need to check this.

**Comment by ngehlenborg** [comment]
Maybe for now we can just **remove** the NA group, e.g. at import time if user requests it. That would solve the vis problem and the query problem. Later we can add support to **hide** groups in the views or exclude them from the query.

**Comment by mstreit** [comment]
Yes, we can do that. Where would it fit in the GUI?

**Comment by alexsb** [comment]
That already works. Simply remove the category when importing.

**Comment by mstreit** [comment]
That's only possible in the "Import data" dialog and not in the "Add grouping for.." dialog.

**Comment by mstreit** [comment]
We cannot do it on the importer level, because sometimes you want to add a grouping (from a paper for instance) and just inspect the subtypes they had there. In TCGA the patients added after the paper was published are in the NA group. Hiding would be useful in this case.

**Comment by mstreit** [comment]
@cpartl Can you add the page where a user can remove groups to the "Add grouping" dialog. atm this is only supported when the user adds groupings to a newly imported dataset (via the Import data wizard).

**Comment by cpartl** [comment]
I guess it will require a little more than just adding this page, as it is specific to categorical data with color assignments etc. Additionally, a grouping file can contain multiple individual groupings (columns). Therefore, we would probably need something similar to inhomogeneous datasets, where we can specify the properties for individual columns. Adding and removing groups on a column basis will also affect the datastructure for parsing and the parser itself.
