### ISSUE TITLE
Import External Score OK/cancel buttons are gone after selecting file

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1432]

**Comment by sgratzl** [comment]
what do you mean by gone: not visible, not selectable -> as I can see them and select them

**Comment by mstreit** [comment]
gone = not visible
However, they are there right after the dialog has been opened.
![import1](https://f.cloud.github.com/assets/4129755/773304/49cf17fe-e935-11e2-8d1f-0b3ba869b7f9.png)

**Comment by sgratzl** [comment]
do you have a similar behavior in the import grouping dialog, as both are more or less the same code?

**Comment by mstreit** [comment]
no

**Comment by sgratzl** [comment]
now the layout is even more similar to the import grouping one, please test it again. As it always worked on my system, I can't verify it

**Comment by mstreit** [comment]
works now.
