### ISSUE TITLE
adding a new view creates two instances/tabs of the same view

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1436]
This happened after I had save the data set with one Stratomex view before. Closing one tab will close the other tab, too. In the end I was unable to remove that duplicate tab.

**Comment by sgratzl** [comment]
did you saved the project using kepler or juno?

in the kepler case, I can't reproduce the problem

**Comment by ngehlenborg** [comment]
I used the 3.0.0 download.

##

**Comment by sgratzl** [comment]
so you created and saved the project using the 3.0.0 release?, could use either send me the project or at least the containing workbench.xmi file

**Comment by sgratzl** [comment]
I think I found the bug, it is all about how we were creating the unique secondary ids for different StratomeX views. They weren't unique over multiple running instances. Now they are time based. 

To fix your project you either have to:
1. delete the containing workbench.xmi, load the project, assign you stuff to StratomeXes and store it again
2. edit the containing workbench.xmi: 
   1. look for a bunch of lines, matching: `<children xsi:type="advanced:Placeholder" xmi:id=".*" elementId="org.caleydo.view.stratomex.*" .*/>`
   2. in the project you send me, there was an element id twice: `org.caleydo.view.stratomex:0` 
      delete the duplicate line
