### ISSUE TITLE
Add labels to the individual curves in KM-plot detail mode

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1443]
There is some space on the right to render the group names. This of course only works in the detail mode. 
This feature is also needed for the NMC screenshot.

**Comment by mstreit** [comment]
I think that's fine.

![screenshot_20130712_205429](https://f.cloud.github.com/assets/4129755/790325/b794fa38-eb24-11e2-896c-d3e88a39c622.png)

**Comment by ngehlenborg** [comment]
This is an example where it really doesn't work. I know that this will be hard to fix, but maybe we could at least re-plot the label for the currently selected and/or hovered line on top of the others (precedence: hovered > selected > regular).

![screen shot 2013-07-16 at 10 37 48 am](https://f.cloud.github.com/assets/1216518/805377/5b2257ba-ee25-11e2-8e3b-1fc9e77761c8.png)

**Comment by mstreit** [comment]
Looks good. Closing issue.

![screenshot_20130717_133333](https://f.cloud.github.com/assets/4129755/811444/c0262c7c-eed4-11e2-847d-7e83ff143282.png)
