### ISSUE TITLE
Load Pathways only once per GLContext

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1454]
as far as I understand every pathway brick is independent of each other. That means that the same pathway figure is loaded multiple times in the same OpenGL context. 

We should avoid that, as it is a waste of time and space. 

We should think about something similar to [ThreadLocal](http://docs.oracle.com/javase/7/docs/api/java/lang/ThreadLocal.html) but for OpenGL context

**Comment by sgratzl** [comment]
there is a new class: `GLContextLocal` that provides two features:
1. similar to ThreadLocal one can have a variable that is stored within the context. Therefore if the same class instance is used over multiple gl contexts, the context specific value will be returned
2. in addition a static method: `getOrCreateShared` is available that let you share one and the same GLContextLocal over multiple instances.

Use case for the second one: PathwayTextureManager

GLPathway now uses a shared GLContextLocal to hold and reference its PathwayTextureManager. That means all GLPathway instances probably use the same instance. Therefore a pathway will be loaded only once per GLContext, e.g. per StratomeX and not per GLPathway view. 

They will just probably use the same PathwayTextureManager as the shared reference is only soft. That means the first one will create the PathwaytextureManager and others will use the same instance. However if nobody references the shared local, the GC is allowed to collect it. That means, if no pathway view is visible in StratomeX the shared PathwayTextureManager can be garbage collected. 

@cpartl this may also improve the performance of entourage.

**Comment by mstreit** [comment]
Pathways are loaded in StratomeX much faster now. Good job.
