### ISSUE TITLE
Directly load KEGG Pathways from KEGG server during startup

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1457]
requirements: 
- [x] pathway view has to handle unmodified pathways
- [x] getting image size without loading the whole image, -> see http://stackoverflow.com/questions/1559253/java-imageio-getting-image-dimension-without-reading-the-entire-file

**Comment by sgratzl** [comment]
> pathway view has to handle unmodified pathways

@alexsb you said there should be a script around that manipulates the images -> where is it?

**Comment by sgratzl** [comment]
as the download needs some time, we could create an general first run dialog.

In this dialog, shown only once during the first start, we could: 
- download pathways: wiki + kegg
- download mappings

**Comment by ngehlenborg** [comment]
I second that proposal. It is taking too long (and the progress indicator says still 0% even though many pathways have already been downloaded according to the log).

**Comment by sgratzl** [comment]
I implemented a simple cache initializer. The KEGG pathway download will take some time, but at least the user will bet some feedback

**Comment by alexsb** [comment]
Script - @mstreit did that.

**Comment by mstreit** [comment]
Removed green portions of KEGG pathways using this unix command:

```
mogrify -path . -transparent "#bfffbf" -format png *.png
```

**Comment by sgratzl** [comment]
a first draft of the shader is part of e4c018d625f888f6b3ad587e35236f0c9690ef58. The problem is that due to map mapping and linear filtering you can't do a binary decision, whether to filter a color or not. I tried to implement a version based on HSV, which should give us more flexibility
