### ISSUE TITLE
TCGA_SAMPLE mapping should use lowercase by default

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1460]
Since we are creating the data packages with lowercase we should also use this as the default for loading groupings and matrices.

**Comment by cpartl** [comment]
-> TCGA_sample? For consistency, this should probably be applied to all id categories and id types (GENE, SAMPLE, REFSEQ_MRNA, ENTREZ_ID, DAVID, PATHWAY_VERTEX ...) thus also changing enums etc. Maybe the inverse solution would be easier (changing package creation to upper case)?

**Comment by ngehlenborg** [comment]
Ok, let's make this uppercase when building the packages. But we still need to enforce uppercase mapping when the user selects TCGA_SAMPLE. The other ID types are not affected by this.
