### ISSUE TITLE
error message when matrix loading fails is not informative

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1462]
Can we tell the user more about what went wrong?

![screen shot 2013-07-12 at 6 03 27 pm](https://f.cloud.github.com/assets/1216518/791269/0f79ed0c-eb3f-11e2-93c8-97e199f4abd1.png)

**Comment by cpartl** [comment]
Where can I get this dataset? Do you know what went wrong?

**Comment by ngehlenborg** [comment]
I don't know what went wrong. The data set that I tried to load is in now in the dropbox projects folder for 3.0/KIRC: `KIRC-TP.meth.by_mean.data.txt`. That might not happen with enough heapspace.
