### ISSUE TITLE
Caleydo in unstable state after failed matrix import

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1463]
After loading of large matrix failed, I confirmed the error message (see #1462), but the import wizard did not close (see screenshot). Some of the values in the data clipping fields were missing.

![screen shot 2013-07-12 at 6 23 34 pm](https://f.cloud.github.com/assets/1216518/791358/fdf9dc10-eb41-11e2-8f86-799450ef77c1.png)

**Comment by cpartl** [comment]
Can not reproduce this, for me the wizard closes after confirming the error message.

**Comment by cpartl** [comment]
As I still cannot reproduce it, I assume that this is a special condition when being out of memory. Therefore, I will close this issue. Reopen should it occurr again when not being out of memory.
