### ISSUE TITLE
seemingly random subset of samples in query set are in selection (highlighted) when previewing the results

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1465]
Depending on what I preview I seem to be getting a different selection.

![screen shot 2013-07-14 at 12 56 03 am](https://f.cloud.github.com/assets/1216518/793824/e98ff948-ec41-11e2-8b4f-48cf382a3ed0.png)
![screen shot 2013-07-14 at 12 55 57 am](https://f.cloud.github.com/assets/1216518/793825/e9b2ba8c-ec41-11e2-89d7-07f130bcaada.png)

**Comment by sgratzl** [comment]
This is on purpose, isn't it. The selection will be the intersection of the query and the current previewed stratification.

Or what do you mean?

**Comment by ngehlenborg** [comment]
Ok, with the explanation this makes sense, but it is not obvious without it. 

We need a better visual indicator for the query brick, the "hit" brick and the intersection of those. Could we use an alternative second selection color and use it for the outlines of the relevant bricks as well as for the selected bands?

**Comment by sgratzl** [comment]
> Could we use an alternative second selection color and use it for the outlines of the relevant bricks as well as for the selected bands?

Do you remember the yellow bands..., which we already had

query brick = orange box
hit brick = preview gray box
selected band = selection

**Comment by alexsb** [comment]
I can imagine that an alternative selection color might help a little, but the underlying problem is that users have to understand that. We can either 
- trust they read the (yet to write) documentation, or
- add annotation to the selection somehow,

IMO.

**Comment by ngehlenborg** [comment]
Could we use the "hatch" pattern in the background of the query brick, the hit brick and the intersection band?

PS. I doubt that people will read the documentation. But we still need to write it, because otherwise they will complain that there is no documentation ...

**Comment by sgratzl** [comment]
> Could we use the "hatch" pattern in the background of the query brick, the hit brick and the intersection band?

"hatch" pattern isn't possible for the intersection band, at the moment.

**Comment by sgratzl** [comment]
so the goal is: 
1. highlight query block
2. highlight hit block
3. highlight only the band between them (if there is one), but select the whole band -> = only the band between the two block in a special color/style = right bands in the screenshots

**Comment by sgratzl** [comment]
I implemented the three goals

if you don't like the colors for the hit block or the band between, take a look at `TourGuideRenderStyle.STRATOMEX_...`

**Comment by ngehlenborg** [comment]
I like the yellow, I think that makes it much clearer what is going on. Can we also put a yellow box around the query and a dashed yellow box around the hit?

If the selected row in the lineup view would be yellow, too, then it would be perfect (only when it shows the results of a query, for normal browsing we should still be using orange).

@alexsb @mstreit: What do you think about this?

**Comment by ngehlenborg** [comment]
Should we also be using yellow in pathway queries?

**Comment by mstreit** [comment]
I am not really a fan of yet another color, but I guess it's ok to use yellow again. 
Yes, to be consistent we should also use it for pathway queries.

**Comment by sgratzl** [comment]
3 things:
1. do we have an alternative to color: blinking, dashing, texturing isn't possible
2. adjusted rand queries / log rank -> in this case there is no group intersection -> I think we don't should set a selection as it will be normally everything
3. pathway queries -> do you mean the selection of the query group?

**Comment by mstreit** [comment]
why not just making the borderlines of the bands thicker and maybe a little darker? that should look nice and we do not need to introduce an additional color.

**Comment by sgratzl** [comment]
I checked in some version where we can play around with the band borders. Just take a look a `TourGuideRenderStyle`

I tested to change the color of the selected row, but didn't like it as would only make in rare cases sense, which is more confusing than helpful

**Comment by mstreit** [comment]
Very nice. I like it a lot. Should we also add the line-stippling to the highlight in LineUp (and make the background a littler lighter)? It should basically look the very same as the highlight in StratomeX.

![screenshot_20130718_141235](https://f.cloud.github.com/assets/4129755/818889/79359422-efa3-11e2-9e3f-c1ec5b0fbc5a.png)

**Comment by mstreit** [comment]
I noticed that the line-stippling is currently only shown for JI queries. Maybe we should also highlight the source column for ARI queries using the line-stippling. Atm there is not source highlight at all.
