### ISSUE TITLE
previewing stratifications breaks DVI

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1466]
The DVI should only show the active (=included in a view) stratifications/variables in the folded dataset boxes.

![screen shot 2013-07-14 at 8 42 16 am](https://f.cloud.github.com/assets/1216518/794243/085c8daa-ec83-11e2-8f72-bdac0a4eb1b4.png)

**Comment by cpartl** [comment]
This currently only works for the overview mode of nodes, for matrix mode this will have to be fixed with tickets #868 and #869.
