### ISSUE TITLE
selecting a matrix stratification that does not map to the pathways when querying with (P)GSEA should not be possible

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1468]
Right now it is possible to select a matrix stratification for the query that does not map to the pathways and no error or warning is shown to the user. I can only tell from these log messages that something is wrong:

``` java
!ENTRY IDMappingManager for TCGA_SAMPLE_GROUP 1 0 2013-07-14 01:46:48.889
!MESSAGE No mapping found between [IDType of TCGA_SAMPLE_GROUP: group_record_org.caleydo.datadomain.genetic_44_1270145250] and [IDType of TCGA_SAMPLE_GROUP: group_record_org.caleydo.datadomain.genetic_43_842206928]
```

We should either show a warning/error message to the user (and ask them to select another stratification) or don't allow them to select unmapped stratifications.

I guess a warning would be easier to implement and it would also be a solution in case the user changes the pathway database after an initial query.

**Comment by sgratzl** [comment]
> does not map to the pathways

= no shared genes? or not a valid mappable dataset type (genetic data domains)?

**Comment by mstreit** [comment]
The latter, I assume.

**Comment by ngehlenborg** [comment]
This is a bit odd. I am trying to use (P)GSEA with copy number of methylation data. According to the DVI, there is a "GENE" mapping between those data domains and the pathways. However, (P)GSEA is deactivated.

**Comment by sgratzl** [comment]
> This is a bit odd. I am trying to use (P)GSEA with copy number of methylation data. According to the DVI, there is a "GENE" mapping between those data domains and the pathways. However, (P)GSEA is deactivated. 

according to #920: 

> query: a group of a stratification (only from mRNA, mRNA-sig)

-> will just be enabled for datadomains containing mRNA

**Comment by ngehlenborg** [comment]
We should enable it for everything that has as "GENE" mapping to pathways (at the risk of the user).

**Comment by sgratzl** [comment]
> Right now it is possible to select a matrix stratification for the query that does not map to the pathways and no error or warning is shown to the user. I can only tell from these log messages that something is wrong:

How were you able to select it, I'm just able to select those groups, who are having a genetic background. The other e.g. RPPA, Clinical, doesn't work.
