### ISSUE TITLE
pathways do not fit into view

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1471]
![screen shot 2013-07-14 at 11 27 58 am](https://f.cloud.github.com/assets/1216518/794423/379878f6-ec9a-11e2-839a-0c0ac3db7e3a.png)

**Comment by alexsb** [comment]
You can drag them. We can't make them smaller otherwise it's pointless.

**Comment by ngehlenborg** [comment]
Can't drag in screenshots for case study. Please give me at least 5.

**Comment by alexsb** [comment]
But you can adjust your scaling now and even easier increase your window size ;).
