### ISSUE TITLE
p-values for PGSEA query where there does not seem to be a PGSEA score

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1473]
Any idea what is going on here? I am using only 1500 genes, i.e., there might be pathways without any mapped genes.

This was the second PGSEA query of the session. Maybe this is a caching issue.

![screen shot 2013-07-14 at 12 24 52 pm](https://f.cloud.github.com/assets/1216518/794501/57b8f50e-eca2-11e2-9c88-2325fd1d4c34.png)

**Comment by mstreit** [comment]
As we now show the #mapped genes, it should be obvious to users what happens. Pathways with 0 mapped genes don't have a score. By default, all of them appear at the very end of the list. Closing issue.

![screenshot_20130725_105759](https://f.cloud.github.com/assets/4129755/854566/95a662ca-f508-11e2-958c-fb22b5756b97.png)
