### ISSUE TITLE
auto-maximizing and -minimizing of the LineUp view (double-click on tab) causes StratomeX rendering errors 

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1476]
Examples from two different sessions:

![screen shot 2013-07-14 at 12 39 06 pm](https://f.cloud.github.com/assets/1216518/794537/7e259a82-eca5-11e2-8a7e-776b7163aae7.png)
![screen shot 2013-07-14 at 12 48 59 pm](https://f.cloud.github.com/assets/1216518/794538/7e35a21a-eca5-11e2-9ecd-dba3e1d38e8c.png)

**Comment by sgratzl** [comment]
are you working with the develop_scaling branch or the pure develop one?

**Comment by ngehlenborg** [comment]
Pure develop.

**Comment by mstreit** [comment]
@ngehlenborg Please confirm that issue is still open in the HEAD version.

**Comment by alexsb** [comment]
I can't reproduce.

**Comment by ngehlenborg** [comment]
The bricks are no longer messed up but I get a flicker on the righthand side of the view after scaling down with the second double-click. It looks like the size of the view is not determined correctly since changing the window size fixes the issue.

![screen shot 2013-07-22 at 6 36 13 pm](https://f.cloud.github.com/assets/1216518/836297/de15a3d6-f2ec-11e2-9116-c83bcd2e39d4.png)

**Comment by mstreit** [comment]
@sgratzl Can you reproduce it on our Mac?

**Comment by sgratzl** [comment]
I can reproduce it, somehow the viewport magically shrinks. If I dump the viewport: before 1698 afterwards 1641.

**Comment by ngehlenborg** [comment]
Appears to be fixed for StratomeX view but not for LineUp view. I get a lot of flickering in the LineUp view that persists in the tab that was open, even after switching to other tabs. View resize fixes the flickering.

![screen shot 2013-08-20 at 10 54 32 am](https://f.cloud.github.com/assets/1216518/994169/7ac74fd2-09a8-11e3-9329-51bd3c695d44.png)

**Comment by sgratzl** [comment]
why is that important and a must for 3.0.2?

**Comment by ngehlenborg** [comment]
Because I am demoing the software frequently and would also like to create some videos for talks and in both cases it is a serious problem.

**Comment by sgratzl** [comment]
the problem with this bug is that I don't really know how to solve it. I implemented another workaround, which fakes a resize of one pixel. As resizing seem to fix the issue. 

The underlying problem is - as far as I understand - that min/maximizing a view is implemented such that the children (our opengl canvas) won't notice it. So from the canvas point of view it won't need a resize but the underlying OpenGL surface, seems to be corrupted.

**Comment by sgratzl** [comment]
@ngehlenborg can you test it again, please?
