### ISSUE TITLE
expression levels not mapped on pathway detail view

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1479]
Based on the BRCA case study data set.

![screen shot 2013-07-14 at 8 41 11 pm](https://f.cloud.github.com/assets/1216518/795192/914b9cbe-ece7-11e2-9aa4-cadf59520d86.png)

**Comment by sgratzl** [comment]
wontix -> I'm currently rewriting the pathway shader because of #1457

**Comment by ngehlenborg** [comment]
Reopening because #1457 is closed  and I am still experiencing the problem. See also #1417 (EnTourage).

**Comment by alexsb** [comment]
Occurs in 3.0.1 beta builds.

**Comment by ngehlenborg** [comment]
Only in the build, not when I launch from Eclipse.

**Comment by sgratzl** [comment]
can anyone test it again?

**Comment by mstreit** [comment]
Works for me.
