### ISSUE TITLE
Disable and not hide invalid TourGuide Wizard options within StratomeX

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1482]
by @ngehlenborg: we should show all options in the tour guide wizard all the time, including the currently not possible ones. That would be easier for the user. 

In addition, a tooltip should explain why that option is not available.

**Comment by ngehlenborg** [comment]
The dashed line is great. Could you also make the text gray to make this perfect?

**Comment by mstreit** [comment]
..and maybe also add a solid frame for the activated ones.
