### ISSUE TITLE
default scaling factor for Mac needs to be increased

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1484]
Since users will typically not be aware of the scaling settings in the preferences we need to have a better default, the current one is too small.

I don't know what the correct setting would be, but the slider position in the second screenshot should give you an idea. 

It might also be nice to have a text field to enter the exact scaling factor (or at least a numeric representation next to the slider) to restore a particular setting, e.g. for taking screenshots.

![screen shot 2013-07-15 at 10 12 35 am](https://f.cloud.github.com/assets/1216518/798076/e56377ce-ed58-11e2-8c70-5fe343ce3765.png)
![screen shot 2013-07-15 at 10 12 59 am](https://f.cloud.github.com/assets/1216518/798075/e5643f1a-ed58-11e2-9e61-32990c139613.png)

**Comment by alexsb** [comment]
On Linux it's the other way around, it needs to be decreased.

![default_scaling](https://f.cloud.github.com/assets/2039375/798426/498e2c2e-ed60-11e2-822a-71cc42fd3363.png)

**Comment by sgratzl** [comment]
the reason for both observations is that the default scaling is depending on the reported DPI: `Display.getDPI()`

That means in @alexsb case it claims to have a too high DPI, this is also the reason why the splash screen looks so weird on this machine -> it should print in the console something with: `DPI: Point`

In @ngehlenborg case, as already pointed out in the previous ticket, the mac swt always returns 72 DPI regardless of the current real DPI.

**Comment by sgratzl** [comment]
on the mac I now assume a 96 dpi resolution (which is wrong btw. but will reproduce the old results)
