### ISSUE TITLE
# genes mapped to pathway != # genes shown?

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1485]
Dataset: BRCA_incl_Nature_Subtypes.cal
Pathway: Ascorbate and aldarate metabolism

Only a single gene is mapped according to the pathway map, but LineUp says 8.

![screen shot 2013-07-15 at 10 50 13 am](https://f.cloud.github.com/assets/1216518/798291/2fa2ac92-ed5e-11e2-8fc9-b75d6a525e17.png)
![screen shot 2013-07-15 at 10 51 55 am](https://f.cloud.github.com/assets/1216518/798292/2fa30a34-ed5e-11e2-878d-27157c86efeb.png)

**Comment by alexsb** [comment]
This is probably a multi-mapping. Can you click the node and check how many show up in the selection info view?

**Comment by ngehlenborg** [comment]
No, only one gene mapped to the pathway.

![screen shot 2013-07-15 at 11 13 16 am](https://f.cloud.github.com/assets/1216518/798473/228c64e6-ed61-11e2-8fdb-5aa5974ae905.png)

**Comment by sgratzl** [comment]
there is a bug within the pathway renderer as it doesn't take multi mapping into account. So LineUp is correct and I'm working on a fix for the Pathway. Then you will see another Node mapped, which is a multi-mapping
