### ISSUE TITLE
heatmaps for full matrices are not informative

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1487]
We need to sample the most variable genes from those matrices and cluster those for the heatmaps.

**Comment by mstreit** [comment]
We can either calculate the most variable genes inside Caleydo or use the firehose gene list of the sampled matrices as white list for the sampling.

**Comment by ngehlenborg** [comment]
Let's compute them internally for now. This solution is more universally applicable.

**Comment by mstreit** [comment]
OK, the variation can be calculated with the existing FloatStatistics. The question is if we should sample during the column creation or if we should add the sampled stratification to the dataset and also make it accessible for other purposes. The latter is of course more general.

**Comment by alexsb** [comment]
I think this should be done after parsing the dataset and should then be stored (serialized) with the dataset.

**Comment by mstreit** [comment]
I agree. When the matrix gets too big (threshold?) we should calculate the sampled perspective, cluster it and store it. The user could then choose with our usual mechanism between the full matrix and the sampled one - like we do it for k-means and unclustered now.

**Comment by mstreit** [comment]
I will add sampled default perspectives to the table class (which can be null if the dataset is small enough or no sampling has been requested). This way users can always decide if they want to see the full matrix or the sampled ones (in StratomeX for instance).
For TCGA dataset we would have then "Ungrouped full", "Ungrouped sampled", "K-Means full", "K-Means sampled".
For calculations like GSEA we can then always work with the full matrices. StratomeX by default can show the sampled ones.
Any comments on that?

**Comment by ngehlenborg** [comment]
Sounds good to me.

**Comment by alexsb** [comment]
- Use affinity instead of K-Means
- Ungrouped sampled is unnecessary

**Comment by mstreit** [comment]
This is the result when we take the 1500 most variable genes (by calculating the variance). We load the full matrices but the heatmaps only show the sampled dataset. The cluster heatmaps definitely look better than before, but still not very good. The overall variance is rather low. (Affinity clustering (input parameter 9) is applied instead of K-Means).

![screenshot_20130722_222834](https://f.cloud.github.com/assets/4129755/837746/b01881b2-f30d-11e2-94e3-735a9acb4cee.png)

**Comment by ngehlenborg** [comment]
Do you know why they look so different from the ones we get when using the Firehose filtered data? (or do they look the same with affinity clustering?)

Btw, why affinity clustering over k-means?

**Comment by mstreit** [comment]
We use affinity because it is supposed to give us better results (non-fixed number of clusters).

It seems that the Firehose 1500 gene subset is calculated differently. Atm we use variance.

**Comment by mstreit** [comment]
@ngehlenborg Do you know how Firehose finds the most variable genes? I didn't find documentation on that.

**Comment by mstreit** [comment]
IQR is more robust regarding outliers than the variance. I will test it.

**Comment by mstreit** [comment]
Still looking quite different

IQR filtered genes:
![screenshot_20130724_175758](https://f.cloud.github.com/assets/4129755/849785/0ff71414-f47a-11e2-97e4-ba486af24d10.png)

Firehose filtered genes:
![screenshot_20130724_180526](https://f.cloud.github.com/assets/4129755/849819/e2a94f8a-f47a-11e2-8cdd-d8b61f22b04e.png)

**Comment by alexsb** [comment]
Do you use k-means for the firehose and affinity for the IQR filtered?

**Comment by mstreit** [comment]
Yes. But it looks like different genes. I will try it with both Affinity.

**Comment by alexsb** [comment]
My guess: you can't tell without using the identical clustering algorithm. But you're right: also the histograms look a little different.

**Comment by mstreit** [comment]
This is Sampled Firehose with Affinity Clustering. Still the same.
![screenshot_20130724_203128](https://f.cloud.github.com/assets/4129755/850747/4caeed36-f48f-11e2-81e1-ed0a5f3c4ab7.png)

**Comment by mstreit** [comment]
@sgratzl Do you know an R package that we could use for testing?

**Comment by sgratzl** [comment]
within the java library: commons-math there are statistical implementions of Median, percentile, Variance, ...

just add this package as a dependency and you can reuse most of your code to determine the data

**Comment by sgratzl** [comment]
> @sgratzl Do you know an R package that we could use for testing?

just use the `quantile` and `var` commands

**Comment by mstreit** [comment]
I actually meant an R package that calculates the most variable genes.

The results of variance and IQR look plausible. So they must use a different way to find the "most variable" ones.

**Comment by ngehlenborg** [comment]
The problem is that the gene profiles are not properly normalized before computing of the variance/median absolute deviation (used by Firehose) and before visualization. We need to subtract the mean of each gene profile from each value in the gene profile.

The normalization is not performed in Firehose (however, after subtracting the mean, at least the Firehose mRNA gene profiles will have a variance of 1).
