### ISSUE TITLE
Refactor Data Management

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1489]
ideas: 
1. [ ] _reduce caching_ use more views instead of storing the data, e.g. for normalized values, log values,... -> just apply a function on the raw data on the fly
   -> see `IFloatList`, where you can setup a mapping function and it will return another `IFloatList` instance
2. [ ] _otpimize datastructure_ optimize data for specific types, e.g. for numerical tables, you could store everything in a big 2-dim array. You don't need columns
3. [ ] _on-the-fly statistics_ compute simple statistics during parsing. See `FloatStatistics` that computes online multiple simple statistics
4. [ ] _slice_ provide similar functions to googles guava [Table](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/collect/Table.html) -> row Slice, column Slice,...
5. [ ] _direct access_ why doesn't provide the perspective / virtual array a direct access to the values? You always have to take the way over the underlying data table
6. [ ] _transposing_ transposing a table, should be completely hidden and implemented e.g using a transposing wrapper
7. [ ] _categorical optimization_ optimize categorical storage, as the number of categories is known, we could optimize the data, such that in the best case only 1 or 2 bits are used per data item
8. [ ] _serialization optimization_ store the expected number of data item within the description -> in the import case, we created a preview and therefore know the number of lines, in the tcga example, we could parse it once. Advantage: optimization, you can even create the histogram during parsing + no need to scan a file twice during parsing
9. [ ] _numpy slicing_ provide fast slice access, e.g. I want to have a whole column or a whole row, in the best case function similar to python numpy table implementation or guava table

**Comment by sgratzl** [comment]
btw. I already optimized the categorical data column, such that the normalized value will be computed on the fly. This saves around 30MB of main memory for 10 lines of code

**Comment by alexsb** [comment]
Interesting points. Will take a look at them. Here some comments: 
- _optimize datastructure_ What would be the immediate benefit here? Is this only about memory? This would mean that we use different table implementations for different data types - which is maybe a good idea, especially since mixing categorical and numerical doesn't make too much sense, but I'm not sure what it would buy us at this point.
- _direct access_ You need access to the row AND column ID. The table perspective could provide direct access, but not the virtual array or the perspective
- _transposing_ Definitely!
- _serialization optimization_ Definitely!

I'll have to look into the other points in detail.

**Comment by sgratzl** [comment]
> optimize datastructure What would be the immediate benefit here? Is this only about memory? This would mean that we use different table implementations for different data types - which is maybe a good idea, especially since mixing categorical and numerical doesn't make too much sense, but I'm not sure what it would buy us at this point.

simpler access (in a loop we always want e.g. the normalized value) + less casts (e.g. instead of getRAW with generic I would implement some specialized functions) + more typesafe + faster usage + less memory consumption (internally): 

as we don't have that many different types, we could implement something like: 

``` java
IFloatTable t = datadomain.getTable().asNormalizedTable(idtype dim, idtype row);
float v = t.get(i,j);
IFloatIterator it = t.iterator();
IFloatList f = t.col(i);
IFlaotList f = t.row(j);
IFloatTable t2 = t.slice(i_range, j_range)
t2 = t.transpose();

or

ITable<String> datadomain.getTable().asStringTable(idtype dim, idtype row);
IFloatTable datadomain.getTable().asFloatTable(idtype dim, idtype row); //asFloatTable <-- depending on the underlying type, may throw an exception, e.g. in the String / categorical case

IFloatTable tab = tablePerspective.getTable().asFloa...
```

> direct access You need access to the row AND column ID. The table perspective could provide direct access, but not the virtual array or the perspective

that true, that should be possible, too. But if we support slicing, a single perspective could return a slice of the table, with just the selected rows / columns and all elements in the other direction, e.g. `ITable t = t.slice(dim_va, all);`

**Comment by alexsb** [comment]
Moving discussion to https://docs.google.com/document/d/1Xaf2ucDqm5lVqhv-aWu6B41NaRV1RAlV4RY98oCxyw4/
