### ISSUE TITLE
perform comparison of Caleydo GSEA enrichment scores and Broad reference implementation

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1492]
Proposal for testing strategy:
- [ ] export list of samples in query subsets
- [ ] export full matrix
- [ ] import both into R and/or the GSEA desktop application
- [ ] compute GSEA on the KEGG pathways (only those also available in Caleydo)
- [ ] import ranked list of gene sets and scores (enrichment score, later also p-values) into TourGuide and compare with results of built-in GSEA

We should test this for different tumor types and different query subsets.

Once the data has been imported to R, we can also try alternative methods such as GSA.

**Comment by sgratzl** [comment]
see `...tourguide project/test/testGSEA.R`

**Comment by mstreit** [comment]
@sgratzl Did you run a test already? If yes, what was the result of the comparison?

**Comment by mstreit** [comment]
according to @sgratzl the results are very similar. close.
