### ISSUE TITLE
investigate why RPPA data does not have a GENE mapping to pathways in BRCA use case data set

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1497]
Looks like it is using "protein" and still has the "|" in the protein name.

**Comment by sgratzl** [comment]
we defined RPPA as: protein x tcga_sample, 

so there is no | parsing yet nor is protein a known gene mapping

**Comment by ngehlenborg** [comment]
Maybe better to parse as genes and to use only the part before "|".

**Comment by sgratzl** [comment]
in a similar fashion: microRNA is also a special IDCategory and not a gene id type

**Comment by ngehlenborg** [comment]
Unlike proteins, microRNAs have no "direct" mapping to "genes". It is ok and expected for them to have a different ID type.

**Comment by mstreit** [comment]
I've tested it with a newly generated BRCA cal package. The columns in the RPPA dataset are now mapped to gene symbols.
