### ISSUE TITLE
selection is messed up when selecting "unmapped" clusters for GSEA query

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1498]
I tried to perform a GSEA query using RPPA data (which does not have a gene mapping to the pathway - see #1497). The selection didn't get cleared when I changed the selection in the RPPA column (I successively selected the four clusters that have a selection in the screenshot) and I got the following output on the console:

``` java
...
!ENTRY IDMappingManager for TCGA_SAMPLE_GROUP 1 0 2013-07-16 11:01:28.714
!MESSAGE No mapping found between [IDType of TCGA_SAMPLE_GROUP: group_record_org.caleydo.datadomain.generic_8_1798049823] and [IDType of TCGA_SAMPLE_GROUP: TCGA_SAMPLE_GROUP_primary]
2013-07-16 11:01:30.044 java[63598:707] [IMKInputSession deactivate] exception caught.
    IMKInputSession:<IMKInputSession: 0x7ffa5c13aed0> -- 
    NSInvalidSendPortException : [NSMachPort sendBeforeDate:] destination port invalid
2013-07-16 11:01:35.170 java[63598:707] [IMKInputSession activate] exception caught.
    IMKInputSession: <IMKInputSession: 0x7ffa5c13aed0> -- 
    NSInvalidSendPortException : [NSMachPort sendBeforeDate:] destination port invalid
2013-07-16 11:01:56.634 java[63598:707] [IMKInputSession deactivate] exception caught.
    IMKInputSession:<IMKInputSession: 0x7ffa5c13aed0> -- 
    NSInvalidSendPortException : [NSMachPort sendBeforeDate:] destination port invalid
```

![screen shot 2013-07-16 at 11 01 53 am](https://f.cloud.github.com/assets/1216518/805547/ffbde4da-ee28-11e2-94de-cbccd8a133a7.png)

**Comment by sgratzl** [comment]
you have a multi selection of the RPPA column (CTRL-Key hold), which was recently added. 

However none of the clusters could be used a query to the GSEA, as only the one with a frame around the cluster are possible.

**Comment by sgratzl** [comment]
wontfix
