### ISSUE TITLE
color assignment for categorical data seems to be broken for large number of categories

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1499]
The tumor stage categories (see BRCA use case data set, "Overall Stage" clinical variable) are all gray.

![screen shot 2013-07-16 at 11 20 31 am](https://f.cloud.github.com/assets/1216518/805689/757538b6-ee2b-11e2-9cc2-4ed434e6b9cf.png)

**Comment by sgratzl** [comment]
I know that, but the largest qualitative color scheme is only 12. 

So what colors should be used instead of, if the number of categories is larger than 12?

**Comment by sgratzl** [comment]
another problem is that the stages aren't the same over multiple tumor types. So if we want to specify them, we would need to do that on a per tumor type.

**Comment by ngehlenborg** [comment]
For now a general solution for categorical variables with > 12 categories would be the easiest solution.

Should we just repeat colors? Or use equidistant hues in HSB? In the end there is no good solution to this, but we should use something that is reasonable. I tend towards HSB colors.

@alexsb @mstreit: What do you think?

**Comment by alexsb** [comment]
hmm, I actually think that we shouldn't try to use colors and this gray is OK. Color is only a redundant encoding anyways and adding more colors only could cause confusion.

**Comment by ngehlenborg** [comment]
Ok, but then we need to use another gray as default.

**Comment by alexsb** [comment]
Why?  A darker one?

**Comment by sgratzl** [comment]
`CategoricalClassDescription` line 215 if you want to change it.

**Comment by ngehlenborg** [comment]
Darker or lighter doesn't matter. If it is the same color as the brick background it looks like a rendering error. @sgratzl please use a slightly darker gray.

**Comment by sgratzl** [comment]
done, if you still don't like it: `CategoricalClassDescription` line 215 is the place to change it
