### ISSUE TITLE
Decide which icon set we should use in the future

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1507]
Some options:
- http://p.yusukekamiyamane.com/icons/preview/fugue.png
- https://www.fatcow.com/free-icons
- http://openiconlibrary.sourceforge.net/
- http://xantorohara.110mb.com/core-icons/Eclipse-16x16.html

Icons with size 16x16 are probably fine for our purpose.

@ALL: Any favorites?

This should be decided before we can do #1420

**Comment by alexsb** [comment]
So far we use 99% custom made icons. I don't think we'll get around that in the future, there are just not too many icons out there for "show portal stubs" etc.

**Comment by mstreit** [comment]
We can replace many of our current icons with standard icons. When I look at the general toolbar for instance, that would not be a problem. For more specialized icons we could just pick one that somehow fits (out of >4k that should be doable). Designing good 16x16 icons will be very hard.

**Comment by alexsb** [comment]
I don't see a point in replacing existing icons, with maybe some exceptions. I don't think that we'll find suitable icons even in a 4k icon set. Also I don't think we have to pick a single set - we just need to make sure that they fit somehow.

**Comment by mstreit** [comment]
We should use the standard size of Eclipse icons (16x16). Our current icons are 24x24, which makes it hard to find new ones. If we use multiple icon sets, the icons will never fit together (see open icon). That just looks ugly.

**Comment by ngehlenborg** [comment]
I agree with Marc, we should try to use standardized icons wherever possible. The current ones are hard to understand.

**Comment by alexsb** [comment]
Picking 16x16 icons is definitely not a good idea. Even if Eclipse currently does that it's not going to work in the near future with high DPI screens.

As I said I think we won't be able to use a lot of stock icons, but I'm happy to look in a specific library if I need one.

**Comment by sgratzl** [comment]
the lineup icons are mainly based on fatcow

**Comment by mstreit** [comment]
We can pick a standard icon set that also offers the same icons bigger.

**Comment by cpartl** [comment]
I vote for 24x24 icons from a set for standard operations. We will still have to design custom ones for specialized operations like "Show portal links" in the future and this will be easier with 24x24.

**Comment by sgratzl** [comment]
I vote for some icon sets that has multiple icons sizes. In addition I would suggest to have: SWT view toolbar icons 16x16, main toolbar : 24x24 and OpenGL icons 32x32 (better zooming) as I prefer power of 2 images in OpenGL

**Comment by mstreit** [comment]
Agree. Do you also have a suggestion which icon set to use?

**Comment by sgratzl** [comment]
http://p.yusukekamiyamane.com/icons/preview/fugue.png
-> 16x16 png
-> credit link

https://www.fatcow.com/free-icons
-> 16x16 & 32x32 png
-> credit link

openiconlibrary:
-> really large + ico&png + various sizes: 8-128 
-> big collection with duplicates: e.g. 7 zoom in icons -> difficult to get a common style
-> credit link

Eclipse Icons
-> mainly 16x16 png
-> "boring"

either fatcow or openiconlibrary

**Comment by mstreit** [comment]
I vote for fatcow too.
the very different styles mixed in openiconlibrary is not optimal.
