### ISSUE TITLE
LineUp standalone with data import vs. web version vs. full Caleydo integration

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1508]
Web version: 
- pro: could increase potential users and impact
- con: lots of work, already published

Standalone: 
- pro: little effort
- con: neither fish nor fowl 

Full Caleydo integration:
- pro: make lineup available for our bio users as well as all the others with the same application
- pro: no duplication of implementation (importer, etc.)
- con: maybe too complicated/overkill for ranking only users

**Comment by alexsb** [comment]
I'm voting for the full integration and a potential slim version for the demo standalone.

**Comment by mstreit** [comment]
Agree.
The Caleydo integrated LineUp view should allow users to pick any ID category as a row identifier.

**Comment by sgratzl** [comment]
LineUp view: https://github.com/sgratzl/org.caleydo.view.lineup

**Comment by sgratzl** [comment]
LineUp data importer: https://github.com/Caleydo/org.caleydo.vis.lineup.demos

**Comment by sgratzl** [comment]
a draft of the full integration view is already functional, a simple demo imported is implemented
