### ISSUE TITLE
Reordering of bricks not possible when bricks are highlighted from a query (grey border)

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1509]
The drop target is not appearing in between bricks. Only the drop target before the top brick and after the bottom brick is appearing.

**Comment by cpartl** [comment]
I think I need a more detailed description how to reproduce this, i can reorder bricks within a column while there is a gray border around the brick column.

**Comment by mstreit** [comment]
Add a column, add another column using Jaccard index ("Based on overlap with existing cluster". While the grey highlight is drawn around the bricks in the previously added column, no reordering is possible.

**Comment by cpartl** [comment]
Hm, the drop target is a little covered by the gray borders, but other than that reordering works for me.
