### ISSUE TITLE
Unique IDs generation

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1510]
Persistent Unique IDs must not be based on incrementing an integer, as the this will only create unique ids within the same java vm. 

However if you save and load projects collisions will occur. 

e.g. Datadomain Ids. 

solution: use e.g. time based ids, or by using [UUID](http://docs.oracle.com/javase/6/docs/api/java/util/UUID.html)

**Comment by mstreit** [comment]
I fully agree that we should switch.
However, is this relevant for release 3.0.1?
