### ISSUE TITLE
Realize rank optimization analysis (R IX in paper)

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1517]
R IX: Rank-driven attribute optimization Optimizing the ranking of an item is an important task. Instead of analyzing how the ranking changes upon modifications of the attribute values or the weights, it should be possible, for example, to optimize the settings (i.e., values and/or weights) to find the best possible ranking of a particular item. Identifying the sensitivity of attributes, i.e., how they are influencing the ranking, for example, for finding the minimum attribute value change needed to gain ranks, is another rank optimization example.

Oliver suggested to integrate a gradient decline solver

**Comment by sgratzl** [comment]
alternative: simulated annealing solver - not as greedy as a simple gradient decline

**Comment by sgratzl** [comment]
> it should be possible, for example, to optimize the settings (i.e., values and/or weights) to find the best possible ranking of a particular item.

**formally optimizing values**:

_input_: 
  `$row`, `$ranking-criteria`
_cost function_: 
  `rankOf($row, $ranking-criteria) -> MIN`, i.e `count({$x | $ranking-criteria.compare($x,$row) < 0}) -> min`
_parameters_: 
  all setable float parameters in `$ranking-criteria`, i.e. `filter(flatten($ranking-criteria),ISetableColumnMixin&IFloatRankableColumnMixin)`
_constraints_: 
  user dependent -> ui dialog

**formally optimizing weights**:

_input_: 
  `$row`, `$parallel-ranking-criteria`
_cost function_: 
  `rankOf($row, $parallel-ranking-criteria) -> MIN`, i.e `count({$x | $ranking-criteria.compare($x,$row) < 0}) -> min`
_parameters_: 
   the weights $w_i of $parallel-ranking-criteria"
_constraints_: 
- sum of $w_i = 1 
- $w_i > 0 <-- TO discuss: 
- $w_i < 1

to discuss: $w_i > 0 or $w_i >= 0 -> would allow to remove items from the parallel combiner and $w_i <= 1 would just allow a parallel combiner with a single child. 

**sensitivity minimal value change**:

_input_: 
  `$row`, `$ranking-criteria`
_variables_: 
  `$rank_ori` ... original rank, `$vals_ori` ... original values
_cost function_: 
  `(($vals - $vals_ori)*$w_i)^2 -> MIN`
_parameters_: 
  see optimizing weights
_constraints_:
- `rankOf($row, $ranking-criteria) < $rank_ori` ... better rank
- user dependent -> ui dialog
- weights $w_i for the sensitivity scaling of attribute values,

**Comment by mstreit** [comment]
Nice summary @sgratzl!
For the realization we should investigate existing multi-objective optimation (MOO) techniques, see http://en.wikipedia.org/wiki/Multi-objective_optimization.

**Comment by sgratzl** [comment]
I don't think that we have a Multi-Objective problem, as we always have a single cost function with some constraints.

**Comment by mstreit** [comment]
Atm yes, as the single objective is to optimize the rank. But what if we would include other objectives? Such as that the weighted sum of an attribute should be minimized at the same time. If we could also address these MOO problems, then our solution could be interesting for a much wider audience.

**Comment by sgratzl** [comment]
you know, that the complexity increases dramatically between single object optimizations and MOO.

**Comment by mstreit** [comment]
Yes, that is more a direction for future research than a quick thing to do. However, providing a visualization that allows research to easily access complex MOO techniques could have a nice impact. 
Let's stick to the rank optimization for now.

**Comment by sgratzl** [comment]
just to remember the links:
 http://sourceforge.net/projects/optalgtoolkit/
 http://www5.cs.fau.de/research/software/java-parallel-optimization-package/
 http://sourceforge.net/projects/joptima
