### ISSUE TITLE
Enable selecting individual genes in pathway for enRoute

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1524]
There is currently an undocumented "force mode" written by @dkalkofen that allows you to select genes as a path that are not connected by an edge. This is important to deal with bugs in pathway databases. 

However, we should provide an option where we can actually collect a set of genes independent of their connections. We could have something like 

a, b-c-d, e, f 

where only b-c-d is connected. This is somewhat against the concept of paths, but it is a feature that is much-desired by analysts (I get this request at every meeting). 

I therefore suggest we distinguish between a "path mode" and a "free mode". The path mode uses the same paradigm as before, with the exception of the force mode being documented and accessible through a context menu. 

The free mode lets users click together genes from multiple pathways. This might lead to new requirements on how to handle selections from multiple pathways (show & manage). For now I think we should handle this by enabling people to remove nodes in enRoute.

**Comment by cpartl** [comment]
I could not find any way to enable the force mode, not even sure if it's in the code at all...

**Comment by alexsb** [comment]
Probably @dkalkofen  forgot to commit it?

**Comment by cpartl** [comment]
Is this sufficiently solved? The soluction actually also includes #1083.

**Comment by cpartl** [comment]
I guess it is. -> closing
