### ISSUE TITLE
add support for matrix normalization to TCGA project builder

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1533]
We should perform normalization of the matrices by default using the "z-score" normalization apprach (first formula in http://en.wikipedia.org/wiki/Standard_score). However, it should also be possible to turn this off, e.g. using --center-matrices false  and --scale-matrices false. See http://stat.ethz.ch/R-manual/R-devel/library/base/html/scale.html for inspiration.

I haven't check all matrices, but I assume that for now we could use universal flags (i.e. either no matrices will be normalized or all).

Ultimately, we should expose these (and maybe more) normalization methods in the Caleydo UI to allow users to create normalized matrices of their data (as new perspectives).

Related to #1487.

**Comment by sgratzl** [comment]
the problem with these normalization approaches is that they don't have defined limits. 

What we are currently understood as normalization is a simple linear scaling in the range 0..1 and we need this range for almost everything, e.g. heatmaps, plots,...

**Comment by sgratzl** [comment]
see also #1489 for other ideas, this transformation could be applied on the fly, too. Since the FloatStatistics can be computed during loading

**Comment by ngehlenborg** [comment]
What do you mean by "defined limits"? 

All we need to support is subtraction of the mean and division by the standard deviation. This normalization/scaling of the data is generally independent of the visualization.

**Comment by sgratzl** [comment]
> What do you mean by "defined limits"?

by our 0..1 scaling we know that the getNormalizedValue will return a value between 0 and 1, regardless of the raw data. This will be heavily used e.g. for the heatmap to compute the color. 

> All we need to support is subtraction of the mean and division by the standard deviation. This normalization/scaling of the data is generally independent of the visualization.

What should with we with the z-score values? or for what should we use them?

**Comment by ngehlenborg** [comment]
> > What do you mean by "defined limits"?
> 
> by our 0..1 scaling we know that the getNormalizedValue will return a value between 0 and 1, regardless of the raw data. This will be heavily used e.g. for the heatmap to compute the color.

This scaling for visualization will/can still be applied to the normalized data.

> All we need to support is subtraction of the mean and division by the standard deviation. This normalization/scaling of the data is generally independent of the visualization.
> 
> What should with we with the z-score values? or for what should we use them?

z-score scaling (subtract mean, divide by sd) is different from linear scaling to fit the data into [0,1] (subtract min, divide by range). 

We want to use the z-score normalized data for instance to select the genes with the highest MAD scores (see #1487) and for correct visualization of the gene expression profiles.
