### ISSUE TITLE
(Pathway) detail view overlaps column

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1539]
Observed in [#637](https://github.com/Caleydo/caleydo/issues/637#issuecomment-22873211):

![](https://f.cloud.github.com/assets/2039375/986333/d9236494-08d6-11e3-8518-81c1ad8aabd4.png)

**Comment by alexsb** [comment]
Happens when you resize the window while detail is open.

**Comment by ngehlenborg** [comment]
Ok, we can live with that.
