### ISSUE TITLE
investigate problem with microRNA-seq heatmaps

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1540]
Screenshot from latest KIRC full data set. Looks like the data matrix doesn't contains any negative values (but a lot of NAs?).

![screen shot 2013-08-20 at 8 08 36 am](https://f.cloud.github.com/assets/1216518/993106/5a0f94b4-0991-11e3-9cdd-55e3e468cb00.png)

Compare to Firehose report: http://gdac.broadinstitute.org/runs/analyses__2013_05_23/reports/cancer/KIRC/miRseq_Mature_Clustering_Consensus/nozzle.html

It appears that there are **some** negative values (see color range in top left corner).

(The reports for mature microRNA and precursor microRNA have very similar looking heatmaps).

**Comment by alexsb** [comment]
Cannot reproduce: 

![micrornaseq](https://f.cloud.github.com/assets/2039375/997086/a1b1033a-09db-11e3-9f29-a2cd1b985a41.png)

**Comment by alexsb** [comment]
I have plenty of NANs too, but I have positive and negative values

**Comment by ngehlenborg** [comment]
I was using the data set that you generated yesterday with the code that was current this morning. Why does your matrix look so differently?

**Comment by alexsb** [comment]
Colors look a little different, but look at your histogram! I used the DS in the dropbox.

**Comment by ngehlenborg** [comment]
Whatever code has changed since this morning removed the problem. I don't know what changed, but it would be good to understand how this suddenly disappeared.

**Comment by alexsb** [comment]
Let's reopen this if it reappears.
