### ISSUE TITLE
set histogram color map cutoffs at 2 or 3 sd by default?

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1542]
That would leave to prettier heatmaps by default but could easily be changed by the user if they don't like it. Maybe this could also be handled through a setting.

Should only be applied if matrix has both negative and positive values, if only negative or only positive this should only be applied to the negative or positive end, respectively.

**Comment by alexsb** [comment]
We will use this for both centered and not-centered data equally. Most datasets have a tail at both ends.

**Comment by alexsb** [comment]
Fixed, but a bug in the color mapper remains. Color map is not correctly updated. Temp fix by calling colorMapper.update() everytime a color map is retreived from Table.
