### ISSUE TITLE
most-variable matrix used for pathway mapping?

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1543]
It appears that the full matrix is no longer used for pathway mapping in the latest GitHub version:

![screen shot 2013-08-20 at 10 41 23 am](https://f.cloud.github.com/assets/1216518/994082/c362118e-09a6-11e3-9d17-2ec318e7645f.png)

This is the full KIRC data set.

**Comment by alexsb** [comment]
Did that work at some point? If so, who implemented it?

**Comment by ngehlenborg** [comment]
I am not 100% positive if it worked, but I was under the impression that it did when Marc and I were experimenting with the full matrix data sets.

**Comment by alexsb** [comment]
It certainly worked when you used just the full dataset. If @mstreit  can confirm that that didn't work I'll implement it. If it did work I'd appreciate if the original developer fixes the bug ;).

**Comment by mstreit** [comment]
Full matrix mapping definitely worked. However, I am not sure if we tested the mapping after our own sampling integration.

**Comment by alexsb** [comment]
You mean using Firehose sampled worked in combination with full matrix in StratomeX?

**Comment by mstreit** [comment]
I have not implemented it. I think we assign the wrong (sampled) table perspective in the pathway brick configurer.

**Comment by alexsb** [comment]
This is implemented. The problem appears to be an issue with mrna-seq. Possibly mapping. I can reproduce with mrNA seq, but here is what I get with mrna:

![all_nodes](https://f.cloud.github.com/assets/2039375/1002371/c7f43e5e-0a7b-11e3-80a2-3bdb1e9081a5.png)

**Comment by alexsb** [comment]
Cause: We don't have full matrices loaded for mRNA-seq.

**Comment by mstreit** [comment]
In general, we are loading the mRNA-seq full matrices from the preprocess package in the data run (which works fine for BRCA for instance). However, for KIRC the file inside the package has a different, unexpected name: "KIRC.uncv2.mRNAseq_RSEM_normalized_log2.txt"
Our importer is looking for these files: "<tumorname>.mRNAseq_RPKM_log2.txt"
@ngehlenborg Do you know of any rule for which tumor type we should look for which file?

**Comment by mstreit** [comment]
For now, we are first looking for the RPKM file and if this has not been found, we try to load the RSEM file. This should work, however, it would be nicer to know what the actual pattern is.

**Comment by mstreit** [comment]
We decided to use the RSEM file and if we can't find it we take the RPKM file.

**Comment by mstreit** [comment]
mRNAseq works now for KIRC:
![image](https://f.cloud.github.com/assets/4129755/1017286/2fc294da-0c0d-11e3-9772-4372cf83c15b.png)

**Comment by mstreit** [comment]
What are we going to do about the many NaN?

**Comment by alexsb** [comment]
They should be sampled at 80%. You can try to tune that to exclude stricter, say at 40% in line 668 of Table:

```
if (stats.getNaNs() < stats.getN() * 0.8) 
```

**Comment by sgratzl** [comment]
so another magic value constant within Caleydo...

**Comment by mstreit** [comment]
That's the result with 40%:
![image](https://f.cloud.github.com/assets/4129755/1017405/b9ce5c84-0c0f-11e3-8151-68c9e38db202.png)

**Comment by alexsb** [comment]
@sgratzl firehose does it too!

**Comment by mstreit** [comment]
That's the sampled firehose version:
![image](https://f.cloud.github.com/assets/4129755/1017470/8290dcfe-0c11-11e3-9339-85beb326c52d.png)
