### ISSUE TITLE
RFC: dynamic size scaling of nodes in thumbnails

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1545]
![dynamic_sizes](https://f.cloud.github.com/assets/2039375/1003605/b7fc4342-0a90-11e3-8d0f-a48d6431a8a2.png)

This is an example of nodes that are scaled the more they deviate from the average. I like it. Keep it?

**Comment by alexsb** [comment]
Here an improved version:

![dynamic_sizes1](https://f.cloud.github.com/assets/2039375/1004818/4276ae04-0aaa-11e3-8f8f-eddaa8152d23.png)

**Comment by mstreit** [comment]
I like it too!
