### ISSUE TITLE
Improve reporting & error handling of project builder. 

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1547]
Right now projects are build even if exceptions occur. Looking at the standard logs might help, but we've overlooked problems in the past. To avoid this I suggest the following strategy:

Graceful Fail: if an exception occurs simply don't build the project. We then will notice.
Extra Log: Write which datasets have been parsed for which data type (including info on complete or sampleld) into a file.

**Comment by sgratzl** [comment]
see also #1422

**Comment by sgratzl** [comment]
see also #1607

**Comment by sgratzl** [comment]
in the current version a java.util.logging file will be created in XML format. 

analyzable e.g. using http://www.logmx.com/
