### ISSUE TITLE
Globally registered key binding for Clear Selections

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1548]
I would suggest to introduce a globally recognized key binding for triggering the "Clear Selection" action. 

As due to the #1526 #1523 more and more elements are quickly selectable. So a common way to deselect everything would be useful

**Comment by mstreit** [comment]
Good point. How about "Ctrl+R" (for reset)?

**Comment by sgratzl** [comment]
I introduced key bindings for save project (S) + open project (O), too
