### ISSUE TITLE
Add Z-standardization, std-dev clipping and imputation to import dialog.

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1553]
- [x] z-score normalization
- [x] std dev clipping (???)
- [x] imputation

**Comment by alexsb** [comment]
zscore and imputation only for numerical matrices, std-dev clipping for all numerical

**Comment by cpartl** [comment]
RFC. Please update the textual description of the individual elements yourself if needed.There are some issues with space now on the numerical properties page. Possible solutions/improvements:
- Shorten textual descriptions
- Move "Swap rows and columns" to second wizard page, where you select the dataset type
- Remove "Swap rows and columns" completely. I am not sure if we need this anymore as we can transpose the table.

**Comment by alexsb** [comment]
If using Z-Score normalization disable Data Center and set to selected and 0, as this is implied with Z-Score normalization.

**Comment by alexsb** [comment]
Yes, let's remove swap rows and columns for now and re-add this as a runtime option once we can do that.

**Comment by alexsb** [comment]
On the std-dev widget:
- [x] Move standard deviation to the left, min/max to the right.
- [x] Default activate and set to 3 std deviations. 
- [x] Forbid negative numbers

**Comment by alexsb** [comment]
> Yes, let's remove swap rows and columns for now and re-add this as a runtime option once we can do that.

Maybe that's not such a good idea after all. If we'd need to transpose e.g. an mrna matrix we'd have 30.000 columns instead of 500 - which would be a lot of overhead.

**Comment by cpartl** [comment]
RFC again.
