### ISSUE TITLE
Update GBM sample project to include complete matrices.

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1554]

**Comment by mstreit** [comment]
Waiting for #1565

**Comment by sgratzl** [comment]
subset of #1554

**Comment by mstreit** [comment]
Not completely a subset of #1554, as we usually add the paper subtypes.

**Comment by mstreit** [comment]
Not sure if we should add the old Verhaak subtypes or if we should just provide the unmodified generated GBM project.

**Comment by ngehlenborg** [comment]
Let's add them if it is not too much of a hassle.

##

**Comment by mstreit** [comment]
The original Verhaak subtypes are only defined for 172 samples. As we have 528 mRNA samples in the latest GBM run, the bands look weird when adding further columns. In the EuroVis paper we used unpublished GBM subtypes, which we cannot add to the sample project.

**Comment by ngehlenborg** [comment]
Ok, no additional stratifications for now.

##

**Comment by mstreit** [comment]
Replaced old sample GBM project with full matrix version in the "3.0" folder.
The package starts up with mRNA 4 CNMF and Hierarchical already added to StratomeX.
