### ISSUE TITLE
NA values in TCGA matrices need to be imputed in project builder

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1555]
Use k-nearest neighbor to compute missing values.

@ngehlenborg Do you know which k they use in Firehose?

**Comment by ngehlenborg** [comment]
They are using the R impute package, version 1.20.0 with default parameters:

```
temp <- impute.knn(as.matrix(exp))
```

Details can be found here: http://rss.acs.unt.edu/Rdoc/library/impute/html/impute.knn.html

**Comment by alexsb** [comment]
Decided to do this asap. Implementation options:
- use a separate transformation, to keep the original values around
- replace NAs and ignore previous values
- store a bit that tells us that a value was previously NA

Also, we discussed to do this only for sampled matrices, which might lead to undesired results for GSEA and sampling, but could be done much faster. It should be part of the data packaging step. Should be triggered by DataProcessingDescription.

**Comment by sgratzl** [comment]
there are two separate tasks: 
1. integrate the description and result into the data model in a backward compatible way
2. implement the `impute.knn` logic to compute the data

**Comment by sgratzl** [comment]
from

![from](https://f.cloud.github.com/assets/4129778/1129356/5d25acec-1b89-11e3-800a-43f47524e16e.png)

to

![to](https://f.cloud.github.com/assets/4129778/1129357/600cc260-1b89-11e3-861f-81254a714edb.png)

with maximal 10sec for the mRNA-seq data computed on the unsampled data

**Comment by sgratzl** [comment]
notes: 
- the imputation is computed in parallel where applicable using Fork Join Tasks
- it is based on the `impute.knn` source code (R and Fortran 77)
- the results matches for a simple dataset (http://www.inside-r.org/packages/cran/impute/docs/khanmiss), when the `maxp` is large enough, such that no two-mean-clustering will occur. 
- if the clustering needs to be done, then the result differ maybe due to different starting points or double precision. 
- up to now they it is computed as the other processing step on every project load

**Comment by sgratzl** [comment]
another note: 
- currently the values are REPLACED instead of stored in a view -> was simpler to test, I can change that back to to any other version: view, bitset

**Comment by ngehlenborg** [comment]
Here's another even more striking example of the improvements:

3 days ago:

![screen shot 2013-09-09 at 5 14 53 pm](https://f.cloud.github.com/assets/1216518/1130254/68fe5c12-1ba2-11e3-8c63-79f3bbbbed25.png)

This morning:

![screen shot 2013-09-12 at 7 59 21 am](https://f.cloud.github.com/assets/1216518/1130264/d3bdd2f8-1ba2-11e3-8b45-45067178f463.png)

**Comment by mstreit** [comment]
Close?

**Comment by sgratzl** [comment]
> Close?

we need to clarify how to handle the imputed data. As stated before, the original values are currently replaced.

**Comment by mstreit** [comment]
OK. As this is what Firehose is doing, let's replace it for now.
Do you agree @ngehlenborg ?

**Comment by alexsb** [comment]
I do agree, we do the same thing for the z-standardization

**Comment by ngehlenborg** [comment]
Replacement is fine for now.
