### ISSUE TITLE
GUI problems with Search View

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1557]
The results in the search dialog are clipped and can not be revealed unless I resize the window. On KDE/Linux:

![search](https://f.cloud.github.com/assets/2039375/1021164/6c7ff31c-0ce5-11e3-9c96-90fdc2df337a.png)

**Comment by sgratzl** [comment]
os specific problem, 

on windows: 
![2013-08-26 17_24_26-](https://f.cloud.github.com/assets/4129778/1026760/9f37b22a-0e63-11e3-8f30-27d845ffd51d.png)

don't have that OS -> I can't fix it

**Comment by mstreit** [comment]
OK, I will give it a shot.

**Comment by ngehlenborg** [comment]
I still have this problem on Mac OS X with build b76.

**Comment by ngehlenborg** [comment]
Works on Mac OS X with build b79. Closing.
