### ISSUE TITLE
Kaplan-Meier plot axis labels in detail view plotted outside view and into frame

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1559]
![screen shot 2013-08-24 at 5 34 39 pm](https://f.cloud.github.com/assets/1216518/1021471/059be190-0d05-11e3-890f-d2ee8ee5505a.png)

**Comment by alexsb** [comment]
This should be possible to do correctly with the LineLabelRenderer, but I guess it gets the wrong parameters. 

Note the new align parameter in TextRenderer renderTextInBounds, which the LineLabelRendere should use instead of calculating the width by itself.
