### ISSUE TITLE
apparent discrepancy between %mapped genes in (P)GSEA and mapped genes shown in pathway map

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1561]
KIRC 2013-05-23 mRNA-seq and PI3K-Akt pathway

**%mapped genes approximately 0.05** (compare to screenshot below)
![screen shot 2013-08-25 at 10 10 18 am](https://f.cloud.github.com/assets/1216518/1022471/523cc362-0d90-11e3-806f-455501e20c0c.png)

**looks like almost 100% genes are mapped**
![screen shot 2013-08-25 at 10 10 46 am](https://f.cloud.github.com/assets/1216518/1022472/6eb7c2bc-0d90-11e3-87c2-48243b46ad4b.png)

**Comment by mstreit** [comment]
Note that some genes appear multiple times in the pathway. See screenshot above.

**Comment by alexsb** [comment]
Likely cause: sampled perspective is used instead of complete one for calculating the %

**Comment by ngehlenborg** [comment]
The high number of genes shown in the LineUp metrics is due to the mapping of multiple genes to nodes in the pathway, e.g. PIK3CA, PIK3CB, PIK3CD, PIK3R1, PIK3R2, and PIK3R3 all map to the PI3K node.

**Comment by ngehlenborg** [comment]
Another example where the numbers are even more off (same data set as above):

![screen shot 2013-08-25 at 11 05 20 am](https://f.cloud.github.com/assets/1216518/1022561/fd73ac08-0d97-11e3-9df5-313f6ef4d032.png)

![screen shot 2013-08-25 at 11 05 41 am](https://f.cloud.github.com/assets/1216518/1022562/094a9708-0d98-11e3-8cde-bf083575535d.png)

**Comment by mstreit** [comment]
Identified and fixed the problem. We only took the sampled matrices for GSEA calculation instead of the full ones.
The result of the example from above is now the following:
![image](https://f.cloud.github.com/assets/4129755/1022688/9fc71064-0da5-11e3-836d-df5401d14b12.png)
