### ISSUE TITLE
left outline of TourGuide wizard is missing

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1566]
![screen shot 2013-08-26 at 7 21 57 am](https://f.cloud.github.com/assets/1216518/1025366/d57fb4a8-0e41-11e3-9198-4eba84090d61.png)

**Comment by mstreit** [comment]
On my system the outline is there. However, the line is thicker on the right side.
![image](https://f.cloud.github.com/assets/4129755/1047957/7e046850-107f-11e3-92c0-52bdf4d4c105.png)

**Comment by sgratzl** [comment]
the lines will be drawn, I assume it is something with GL_LINE_SMOOTH and the positions of the lines, such that they between two pixels.

**Comment by mstreit** [comment]
Issue also has to do with the scaling factor. When I switch it to 1.05 the border lines are fine.
![image](https://f.cloud.github.com/assets/4129755/1047966/c9657b22-107f-11e3-84ce-2d4b3bb73a78.png)

Seems to come from the interpolation in the rendering.

**Comment by sgratzl** [comment]
I found the problem: 
 the problem is not drawing the border but drawing the left white stuff at the left side. 

solution: custom border renderer with a slight offset to the wizard center
