### ISSUE TITLE
fix computation of p-values for log rank test

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1568]
Increasing log rank scores should lead to decreasing p-values.

**Comment by sgratzl** [comment]
before:
![before](https://f.cloud.github.com/assets/4129778/1026573/833e1058-0e60-11e3-8988-717861c70800.png)

after:
![after](https://f.cloud.github.com/assets/4129778/1026574/855d6ab4-0e60-11e3-8b6d-4791bed10972.png)
