### ISSUE TITLE
are we computing the log rank scores correctly?

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1575]
Testing for mutations: 1 mutated, 296 not mutated. Mutated dies immediately. log rank score is 291 and P value is 0, but I highly doubt that this is correct. This can't be significant, the mutated group is too small.

![screen shot 2013-08-27 at 3 09 48 pm](https://f.cloud.github.com/assets/1216518/1037280/6ff87d8e-0f4c-11e3-9f5c-3686c008250b.png)

**Comment by ngehlenborg** [comment]
1. **We need to prevent computation of query statistics if the groups are too small.**
2. How does Caleydo deal with the patients for which we don't have any confirmed information about their status, i.e. NA? Does Caleydo assume that they are still alive at the time of the last patient death (i.e. NA = max(days.to.death)) or are they excluded from the computation of the log rank test? 

**My observations**
I get different "log rank" scores (i.e. chi-squared values) than reported by Caleydo ("log rank score" is 291 for ARG2 in KIRC 2013-05-23) in both cases when computing the test in R:
Patients with unknown status assumed alive at last death event:

```
Call:
survdiff(formula = Surv(as.numeric(time[, 1]), as.numeric(status[, 
    1])) ~ group)

          N Observed Expected (O-E)^2/E (O-E)^2/V
group=1 292       75 75.99316     0.013       145
group=2   1        1  0.00684   144.256       145

 Chisq= 145  on 1 degrees of freedom, p= 0 
```

Patients with unknown status excluded (nna = not NA):

```
survdiff(formula = Surv(as.numeric(time[nna, 1]), as.numeric(status[nna, 
    1])) ~ group[nna])

              N Observed Expected (O-E)^2/E (O-E)^2/V
group[nna]=1 75       75  75.9735    0.0125      36.3
group[nna]=2  1        1   0.0265   35.7748      36.3

 Chisq= 36.3  on 1 degrees of freedom, p= 1.73e-09 
```

Here are the curves (assuming unknown patients alive):

``` R
> fit1 <- survfit(Surv(as.numeric(time[which(group==1),1]), as.numeric(status[which(group==1),1])) ~ 1 )
> fit2 <- survfit(Surv(as.numeric(time[which(group==2),1]), as.numeric(status[which(group==2),1])) ~ 1 )
> fit1
Call: survfit(formula = Surv(as.numeric(time[which(group == 1), 1]), 
    as.numeric(status[which(group == 1), 1])) ~ 1)

records   n.max n.start  events  median 0.95LCL 0.95UCL 
    292     292     292      75      NA      NA      NA 
> fit2
Call: survfit(formula = Surv(as.numeric(time[which(group == 2), 1]), 
    as.numeric(status[which(group == 2), 1])) ~ 1)

records   n.max n.start  events  median 0.95LCL 0.95UCL 
      1       1       1       1      50      NA      NA 
> plot(fit1, conf.int=0, col="red")
> lines(fit2, col="blue")
```

![screen shot 2013-08-27 at 5 28 40 pm](https://f.cloud.github.com/assets/1216518/1038243/38b45938-0f60-11e3-80fd-7ed306a71b6e.png)

Excluding unknown patients:

``` R
> fit1 <- survfit(Surv(as.numeric(time[nna[-length(nna)],1]), as.numeric(status[nna[-length(nna)],1])) ~ 1 )
> fit1
Call: survfit(formula = Surv(as.numeric(time[nna[-length(nna)], 1]), 
    as.numeric(status[nna[-length(nna)], 1])) ~ 1)

records   n.max n.start  events  median 0.95LCL 0.95UCL 
     75      75      75      75     722     563     951 
> plot(fit1, conf.int=0, col="red")
> lines(fit2, col="blue")
```

![screen shot 2013-08-27 at 7 05 33 pm](https://f.cloud.github.com/assets/1216518/1038797/48603944-0f6d-11e3-90a6-b074251d5e69.png)

And here is the screenshot from Caleydo:

![screen shot 2013-08-27 at 5 36 09 pm](https://f.cloud.github.com/assets/1216518/1038274/d9057156-0f60-11e3-89a3-7fd6fa44d7e9.png)

Finally, both of my curves are different, they end below 80% or at 0%, respectively, while the curve in Caleydo ends above 80%.

**Comment by sgratzl** [comment]
> How does Caleydo deal with the patients for which we don't have any confirmed information about their status, i.e. NA? Does Caleydo assume that they are still alive at the time of the last patient death (i.e. NA = max(days.to.death)) or are they excluded from the computation of the log rank test? 

current implementation:

GLKaplanMaier line 391 -> if the value is unknown -> assume alive -> BUG -> now the graphs looks similar to the 1. R plot
LogRank.java line 98 -> if the value is unknown -> it will be assumed that the person is still alive

**Comment by sgratzl** [comment]
I added two things: 
- first you can set a min size filter within the Preferences, that will exclude groups from jaccard & logrank that are too small (default 0)
- second, in the mutation case you can now use the mutated metric to filter (by manipulating the mapping function) such that too small mutated clusters will be excluded (= filter not mapped entries enabled)

**Comment by ngehlenborg** [comment]
Filter in preferences is a good idea!

The minimum size does not work properly in b79. I set the minimum cluster size to 10, but I still get stratifications where the mutated group is only a single patient. Only when I deactivate the "not mutated" group, the filter seems to work.

**Comment by sgratzl** [comment]
the problem with log rank is that I know currenty three different version how to compute the z-score:

[Wikipedia](https://en.wikipedia.org/wiki/Logrank_test): `z = (E_a-O_a) / sqrt(V_a)`
[R](http://cran.r-project.org/web/packages/survival/index.html): `z = (E_a-O_a)^2 / V_a`
[Statistics Note](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC403858/): `z=(E_a - O_a)^2/E_a + (E_b - O_b)^2/E_b`

in the currently commited version I used the R version.
