### ISSUE TITLE
investigate why tour guide buttons get a dark outline + other

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1576]
left: created in image editor / right: screenshot
![screen shot 2013-08-27 at 12 28 15 pm](https://f.cloud.github.com/assets/1216518/1037326/3841257a-0f4d-11e3-9956-479f69caf54b.png)
- [ ] remove dark outline
- [ ] change size to 32x32 for all tour guide buttons
- [ ] used add_independent instead of new?

**Comment by sgratzl** [comment]
dark outline:

the solution is: alpha premultiplication.

see http://download.java.net/media/jogl/jogl-2.x-docs/com/sun/opengl/util/texture/Texture.html

see also: http://home.comcast.net/~tom_forsyth/blog.wiki.html#[[Premultiplied%20alpha]]

we are using: `gl.glBlendFunc(GL.GL_SRC_ALPHA, GL.GL_ONE_MINUS_SRC_ALPHA);`
but should use: `gl.glBlendFunc(GL.GL_ONE, GL.GL_ONE_MINUS_SRC_ALPHA);` for texture blending

the problem: where to set it, to avoid side effects?

alternative: create a custom loader and avoid alpha premultiplication

**Comment by mstreit** [comment]
It would be good to have this fixed for the final NMC screenshots.

**Comment by sgratzl** [comment]
I fixed in especially for these buttons. As if I add it to some more general place (e.g. TextureManager) it will produce side effects -> see DVI StratomeX icon, if you uncomment the code

btw. I would add some border or 3D effect to make them more "attractive" to pushes.
