### ISSUE TITLE
when exporting survival column split based on mutation, entries in mutated group also appear in non-mutated group

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1577]
To reproduce:
- KIRC 2013-05-23 data set
- split survival based on ARG2 mutation status
- export survival data based by right-clicking header brick

B2-4098 is the patient with the mutation, the corresponding entry appears at the very end of the file (for the "mutated" group, I assume) but also higher up between the others.

**Comment by ngehlenborg** [comment]
In fact, there are further duplicates, for a total of 4:

B2-3924, B2-4099, B8-4620

**Comment by ngehlenborg** [comment]
I have analyzed the MAF file that we are using to extract mutation calls:

B2-4098 - only mutations in TCGA-B2-4098-01A
B2-3924 - only mutations in TCGA-B2-3924-01A
B2-4099 - only mutations in TCGA-B2-4099-01A
B8-4620 - no mutations at all

However, it seems that for these four patients, the tumor was split up into 2 portions, e.g.

TCGA-B2-4098-01A-01D-1458-08
TCGA-B2-4098-01A-02D-1386-10

(portions 01 and 02, D = DNA) and they were sequenced at two different centers (08 = Broad, 10 = Baylor).  This probably explains why we have the same patient twice.

Related to #949 and #1363.

Here is a nice illustration of a side effect of duplicate ids:

![screen shot 2013-08-27 at 6 46 37 pm](https://f.cloud.github.com/assets/1216518/1038696/a2bd88e0-0f6a-11e3-8289-0b2c9956765f.png)

**Comment by alexsb** [comment]
So how do you suggest we should handle this? It's clearly no issue of the exporter. It may be considered as an issue of the importer, or it may be considered as correct behavior.

**Comment by alexsb** [comment]
Closing, this is a symptom of duplicate ids as referenced in the other tickets.
