### ISSUE TITLE
use absolute mapping for PGSEA score by default

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1579]
- [ ] fix spelling of PGSEAP-value -> PGSEA P-value
- [ ] fix mapping, see below

**with current default mapping:**
![screen shot 2013-08-27 at 10 57 39 pm](https://f.cloud.github.com/assets/1216518/1039568/c4ac4496-0f8d-11e3-87de-db64da4529c1.png)

**with absolute mapping:**
![screen shot 2013-08-27 at 10 57 50 pm](https://f.cloud.github.com/assets/1216518/1039569/d0a90bda-0f8d-11e3-8688-c830ce61b31a.png)

**Comment by sgratzl** [comment]
now used mapping function: `linear(0, max(abs(value_min),abs(value_max)), abs(value) , 0, 1)` 

linear interpolation between 0->0 and the max absolute value of the range -> 1
