### ISSUE TITLE
excessive log messages of little value

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1582]
Related to #1571, do we need log messages such as the following, which often get written hundreds of times? My session log files are easily in the range of 5 - 10 MB.

Maybe we should introduce a "debug" mode (via preferences) in case someone really needs all INFO level messages. By default I would only write errors and maybe warnings.

```
INFO: org.caleydo.core.view.ViewManager@3776c784: Registering view: Heat map for [D: [P for [IDType of GENE: dimension_org.caleydo.datadomain.genetic_2b918c03-140abef072f--7fee_911567039], size: 1500]; R: [P for [IDType of TCGA_SAMPLE: record_org.caleydo.datadomain.genetic_2b918c03-140abef072f--7fee_911567039], size: 59]]
```

```
group_record_org.caleydo.datadomain.genetic_2b918c03-140abef072f--7faa_577659452]
INFO: IDMappingManager for TCGA_SAMPLE_GROUP: No mapping found between [IDType of TCGA_SAMPLE_GROUP: TCGA_SAMPLE_GROUP_primary] and [IDType of TCGA_SAMPLE_GROUP: group_record_org.caleydo.datadomain.genetic_2b918c03-140abef072f--7faa_577659452]
```

**Comment by sgratzl** [comment]
In not happy with the logging in general. The eclipse logging toolkit is too inflexible, compared to slf4j, logback...

but if you just want to remove all the INFO & OK messages, you can set `-Declipse.log.level=WARNING` within your launch configuration

**Comment by sgratzl** [comment]
> Maybe we should introduce a "debug" mode (via preferences) in case someone really needs all INFO level messages. By default I would only write errors and maybe warnings.

the normal way is to use the proper log category: 
 eclipse: OK, INFO, WARNING, ERROR, CANCEL
 slf4j: VERBOSE, INFO, WARN, ERROR, FATAL

and filter out the non interesting  - including package specific filters
