### ISSUE TITLE
changing filters on data domain does not update metrics bar colors (gray vs colored)

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1583]
To reproduce:
- select CNV
- set filter to only allow amps to pass
- query 
- change filter to only allow dels to pass

=> del bars still gray (see screenshot below)

![screen shot 2013-08-28 at 7 08 05 am](https://f.cloud.github.com/assets/1216518/1041516/587d0d0a-0fd3-11e3-9602-b0c88d6e796c.png)

**Comment by sgratzl** [comment]
workaround: deactivate / activate the data domain

problem: colors are up to now final for LineUp columns

I can try to replace the column with the new colored version

**Comment by sgratzl** [comment]
I replace the column upon filter change. It might not be optimal but work in 90 percent of the cases.
