### ISSUE TITLE
Rethink vertical positioning of KM plots in column

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1587]
Evenly distributing the KM plots in the column would reduce the ugly band compression that we currently have.

**Comment by sgratzl** [comment]
the same holds for pathways. 

I would suggest (it enough space is available) to put it at the same y-position as their corresponding cluster

**Comment by mstreit** [comment]
I agree, putting the bricks one the same y-pos as the bricks in the column the pathway or KM plots are depending on would result in nice bands. 
@cpartl How difficult is this to implement? It would be nice to change it for the NMC screenshots.

**Comment by ngehlenborg** [comment]
Don't forget that there are often situations in which one or more blocks are really small and their height is less than the height required for the KM or pathway plot - you'd have to handle this somewhat flexibly to avoid overlapping blocks.

##

**Comment by mstreit** [comment]
Yes, we discussed that already. I think equally distributing the bricks is the best and most universal solution.

**Comment by cpartl** [comment]
closed via b7a18cd

**Comment by mstreit** [comment]
Looks nice!
However, before accepting the column, the bands are slightly off from the bricks. When hover over something, they are correct.

**Comment by mstreit** [comment]
The KM bricks now look a little bit detached though. Other opinions?
![a-d_mrna_microrna_overlap_m3_mi2_survival_stages](https://f.cloud.github.com/assets/4129755/1050635/29a796c2-10bd-11e3-80c5-8ee27840b636.png)

**Comment by cpartl** [comment]
Not sure what to do about the detached look. Maybe an unobtrusive column background would help, but not sure if we should do that.

**Comment by mstreit** [comment]
Let's keep it as it is for now. Thanks for fixing.
