### ISSUE TITLE
Improve TCGA Browser Startup Addon

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1597]
we could improve the tcga data browser with additional information stored in the json file, including data stats, color, clustering information,...

**Comment by mstreit** [comment]
A little table per data package would be good. Similar to: http://compbio.med.harvard.edu/tcga/stratomex/

**Comment by ngehlenborg** [comment]
Somehow the tree is not attached to the top of the view, I can move it out of the visible area using the scroll wheel:

![screen shot 2013-09-10 at 2 49 33 am](https://f.cloud.github.com/assets/1216518/1112626/3afe1744-19e5-11e3-8e91-6b48c26edec3.png)

**Comment by sgratzl** [comment]
please retest 

part of 4ee5b89356cb71b20a509801bef525df4c34a9ac
