### ISSUE TITLE
make scaling factor directly accessible in UI

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1601]
During demos it is sometimes quite useful to change the scaling factor, e.g. to show detail in the LineUp or StratomeX view but then "zoom out" to show an overview.

This could be implemented either as a global slider (if we can find a good place) or as a keyboard shortcut or both.

**Comment by sgratzl** [comment]
within the main toolbar (top left) we would have enough space. 

regarding keyboard shortcut: I think `CTRL-+` and `CTRL--` are still free to use. But things like `CTRL-MouseWheel` are already used in some of the new views (e.g. bicluster)

**Comment by ngehlenborg** [comment]
Main toolbar: sounds good.

Keyboard: How about `CTRL-{ALT|SHIFT}-+` and  `CTRL-{ALT|SHIFT}--` since this is something that typical users would rarely do. That way we can save `CTRL-+` and `CTRL--` for standard zooming.
