### ISSUE TITLE
add mutsig q-values as scoring information to mutation gene stratifications

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1605]

**Comment by sgratzl** [comment]
as far as I understand: 

during package generation the mutsig q-values should be packed into the package, right?

**Comment by ngehlenborg** [comment]
Yes, that's correct. MutSig CV 0.9. Issue moved to 3.0.4 however.

**Comment by sgratzl** [comment]
importing q-values is mostly implement, please take a look at `MutSigTask.java` for the details about mapping, data source and so on

**Comment by sgratzl** [comment]
@ngehlenborg, can you please test it

the current used file is: http://gdac.broadinstitute.org/runs/analyses__2013_05_23/data/GBM/20130523/gdac.broadinstitute.org_GBM-TP.MutSigNozzleReportCV.Level_4.2013052300.0.0.tar.gz

-> as referenced in `FirehoseProvider.java findMutSigReport()`

**Comment by ngehlenborg** [comment]
This seems to have been added. See #1694.
