### ISSUE TITLE
Report on data sources inside of Caleydo

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1607]
When creating projects we should report the exact file in the exact package (ideally including a link) out of firehose, similar to https://github.com/Caleydo/caleydo/wiki/TCGA-Package-Generator but dynamically.

**Comment by sgratzl** [comment]
@cpartl thx again

**Comment by cpartl** [comment]
Please specify exacly what should be reported on and how and where this information should be accessible.

**Comment by mstreit** [comment]
Did you get necessary information what should be contained in the report?
