### ISSUE TITLE
Refactor Logging

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1609]
generalizing #1582 and #1571 

we should rethink our current logging strategy. 

should have: 
- the errors & warnings [& info] should be accessible via the errors eclipse view within Caleydo
- capture the eclipse errors in the logging service

must have:
- log to file support (either on a per start basis or some rolling file
- simple to use and class based
- different levels ERROR -> DEBUG
- flexible logging selection on a class / package level

should prevent:
- sysout and syserr
- --consoleLog ... 2 lines for 1 message is too much

frameworks: 
- java.util.loggging -> could be the underlying one
- log4j
- logback
- slf4j - meta
- commons-logging - meta -> already part of caleydo because of natable

**Comment by alexsb** [comment]
Yes, definitely! Our current logging is super-awful and clumsy to write.
