### ISSUE TITLE
Bands are gone after viewing pathway in detail mode

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1611]

**Comment by mstreit** [comment]
@cpartl Can you reproduce this on your machine?

**Comment by cpartl** [comment]
Actually, no. Are there any specific conditions?

**Comment by mstreit** [comment]
OK, it has nothing to do with the detail mode. It's a shader problem.
Reproduce:
- Load mRNA stratification
- Add pathway - pick some from the list and the bands are gone

Log: Shader status invalid: (no info log)
