### ISSUE TITLE
Auto-upload / provide / paste, etc the log when someone clicks "Report a bug" in Caleydo

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1614]
This would make the cumbersome process of finding the latest log obsolete.

**Comment by sgratzl** [comment]
we have to check, which privacy related information are stored within the log files before we can upload them to a public place 

e.g. currently we are dumping the environment variables, containing: username and a lot of system information

as an alternative we could just prepare an email template and print the related information in a popup box, and point to the file location of the log file

**Comment by sgratzl** [comment]
things the user should provide:
java version, caleydo version, architecture, project name (if a standard one), platform, error description, latest warning & error messages (no info, debug)

optional:
list of open views, screenshot, contact address

btw. with the current logging strategy I doubt that a full log would help us finding bugs.

**Comment by mstreit** [comment]
Related to log mechanism refactoring #1609
