### ISSUE TITLE
"Help > Error Log" does nothing

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1615]
I should get the eclipse error view I presume, which I don't. We should either show that or show the log text file.

**Comment by alexsb** [comment]
Related to #1609

**Comment by sgratzl** [comment]
are we are talking about the latest release or your local version?

-> add org.eclipse.ui.views.log plugin to your launch config

**Comment by mstreit** [comment]
Works for me for both release version and Eclipse head. 
@alexsb Re-open if updating your launch config does not work.
