### ISSUE TITLE
change p-value mapping in LineUp for Tour Guide

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1617]
The Park lab suggested that we change the p-value mapping used in LineUp:
- [ ] use `-log(p-value)`
- [ ] change column header label to `-log(p-value)`

Further suggestions were to change the color or style of the bar for p-values that are not significant. This is something that is hard to implement at the moment, because it both requires a significance cut-off and correction for multiple testing. See #1616.

**Comment by sgratzl** [comment]
what about the corner case: p-value = 0 -> `-log(0) = Inf`

in addition, we need to linearize this mapping in the 0..1 range

**Comment by sgratzl** [comment]
so please come up with a mapping: `p-value -> [0,1]`, given: `pvalue_min`, `pvalue_max`

**Comment by ngehlenborg** [comment]
`p-value = 0` should be mapped to `Double.MIN_VALUE` before `log` is applied. The log scale data should be mapped to `[0,1]` using regular linear scaling (here: divide by maximum of log-transformed values). 

Unfortunately, p-values of 0 have the potential mess up the length of the other bars.

**Comment by ngehlenborg** [comment]
To deal with very small p-values, we could also set a lower limit greater than `Double.MIN_VALUE`, e.g. 10e-10, and map every p-value smaller than that to this value before the log transformation is applied.

**Comment by sgratzl** [comment]
current js code:

```
linear(0.0, -log(Math.max(10e-10,value_min)), -log(Math.max(10e-10,value)), 0.0, 1.0)

linear(start, end, value, start_to, end_to)
```

**Comment by sgratzl** [comment]
don't like it, change it in `org.caleydo.view.tourguide.impl.Utils.createPValueMapping()`
