### ISSUE TITLE
add note to pathway download progress indicator

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1618]
It should say that this download is only performed once and updated if necessary, e.g.

"Downloading pathway information. This may take a while but will not be required next time you start Caleydo, unless updated pathway information is available on the server."

**Comment by sgratzl** [comment]
@ngehlenborg please check if the current version is sufficient. Adding a second line isn't possible.

**Comment by alexsb** [comment]
I think it's sufficient
