### ISSUE TITLE
Update splash

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1619]

**Comment by sgratzl** [comment]
please keep https://github.com/Caleydo/caleydo/wiki/Eclipse-RCP-FAQ in mind

**Comment by ngehlenborg** [comment]
messageRect: 55,328,537,20 [x,y,w,h]
progressRect: 55,351,537,20
version: 55,378,537,20 (right-aligned text)

progressbar colors (if possible): 255,255,255 (foreground), 7,7,33 (background)
message fontsize 12pt
version fontsize 10pt

![caleydo-3-regular](https://f.cloud.github.com/assets/1216518/1150775/071d4d68-1ef0-11e3-8503-85b70a34196a.png)

Example with message, version and progress bar as defined above: 

![screen shot 2013-09-16 at 12 53 09 pm](https://f.cloud.github.com/assets/1216518/1150811/83568b9c-1ef0-11e3-812d-fb9344583256.png)

**Comment by ngehlenborg** [comment]
Do we have a place for for copyrighted/licensed materials that we are using in Caleydo? The background image is from http://en.wikipedia.org/wiki/File:Hyades.jpg and was created by Todd Vance. It is licensed under [Creative Commons Attribution-Share Alike 2.5 Generic](http://creativecommons.org/licenses/by-sa/2.5/deed.en).
