### ISSUE TITLE
Update Caleydo logo

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1620]
In Wizards, general toolbar, app icon.

**Comment by mstreit** [comment]
...also on current website

**Comment by sgratzl** [comment]
hint: some of the application icon are stored within the super project, too

**Comment by mstreit** [comment]
ok. do we really need all the different version that are currently stored in org.caleydo.core/resources/logos?

**Comment by sgratzl** [comment]
most of them, yes. But what about creating a script and let imagemagick create the different versions for you based on an svg image

**Comment by mstreit** [comment]
yes, that would be optimal.

**Comment by sgratzl** [comment]
... and on github (caleydo machines + caleydo organisation)
... and on gravatar
... and within the import / export icons

**Comment by sgratzl** [comment]
> ... and within the import / export icons
> In Wizards, general toolbar, app icon.

done

**Comment by ngehlenborg** [comment]
Thanks! Looking good, closing.
