### ISSUE TITLE
show numerical variables from new datasets in "Other lineup"

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1623]
For example, right now it is impossible to use survival data loaded from external files.

**Comment by sgratzl** [comment]
Other lineup lists all: inhomogenous natural number columns. 

so if you manually import such an imhomogenous table, containing columns of type natural numbers, it will appear in LineUp

**Comment by alexsb** [comment]
How was the data loaded? Homogeneous or heterogeneous?

**Comment by ngehlenborg** [comment]
**Inhomogeneous**

**Comment by sgratzl** [comment]
natural numbers? -> by default it would be numerical (float)

**Comment by sgratzl** [comment]
@ngehlenborg can you test it again, please. 

Otherwise what types of data should be listed in the "others" view

**Comment by ngehlenborg** [comment]
Ok, this is what I found:

Loading integers (natural numbers) works, but then I get a histogram preview (instead of a KM preview for the regular "days to death"). Loading floats (real numbers) does not work.

I think both should work and we should recommend to load survival data as real numbers.

![screen shot 2013-09-14 at 3 46 24 pm](https://f.cloud.github.com/assets/1216518/1144167/addd6442-1d76-11e3-90f6-2f09db19533e.png)
