### ISSUE TITLE
logrank queries with mutations broken

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1627]
Deselecting the "not mutated" group no longer seems to work. The top hits are always genes with only a single mutation.

**Comment by sgratzl** [comment]
as far as I know is the log rank symmetric, so both test scenarios: not-mutated vs mutated and mutated vs not-mutated result in the same value. 

So if you deselect the "not mutated group" just deselect the not-mutated vs mutated case, but the other one remains. 

There is currently no "min size" filter implemented in the log rank algorithm directly

**Comment by ngehlenborg** [comment]
I thought exactly that had been fixed in #1575 and for all that I remember it worked fine until I pulled the latest code yesterday:

> second, in the mutation case you can now use the mutated metric to filter (by manipulating the mapping function) such that too small mutated clusters will be excluded (= filter not mapped entries enabled)

I will test this with 3.0.2 to confirm.

**Comment by ngehlenborg** [comment]
I figured it out. I had set the minimum cluster size filter in the prefs, but that got deleted yesterday when I was working on the pathway issues. So it wasn't really the data domain filter but the cluster size limit that affected all my queries.

Since the prefs filter only works after restarting the StratomeX view, this is a little bit confusing and maybe also the source of the problem that I reported [earlier](https://github.com/Caleydo/caleydo/issues/1575?source=c#issuecomment-23519664):

> The minimum size does not work properly in b79. I set the minimum cluster size to 10, but I still get stratifications where the mutated group is only a single patient. Only when I deactivate the "not mutated" group, the filter seems to work.

These are the issues with the current approach:
1. the prefs set size filter is too hidden and therefore easily forgotten
2. the prefs set size filter will affect all queries

I suggest that we move the set size filter from the prefs to the data domain filtering dialog with a checkbox to activate it and a text field or spinner to set the size. Once it is active, the filter icon should be set to blue. What do you think?

**Comment by ngehlenborg** [comment]
Btw, now that I know how I can reproduce my earlier results I'm fine with moving this to 3.0.4.

**Comment by sgratzl** [comment]
> What do you think?

Like that idea, implemented it in that way. 

In addition the original preference value is used as a default value for the data set specific min size filter. 

However the min size filtering is currently not implemented for pathways
