### ISSUE TITLE
missing and unnecessary Tour Guide wizard options

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1631]
Missing: adding pathway as unstratified and without mapping any data onto it.

Unnecessary: "Select stratification" when adding independent column to unstratified dependent column (right now only possible for clinical parameters but if missing option is added this would also apply to unstratified pathways): since it is the only option in the first step we should drop it.

**Comment by sgratzl** [comment]
> Missing: adding pathway as unstratified and without mapping any data onto it.

currently not possible in StratomeX since every pathway needs to be mapped to something
@alexsb or am I wrong?

**Comment by alexsb** [comment]
@cpartl is more qualified to say something to that, but I think it's possible. It's afair the default of the pathway standalone view where a strat is only later mapped to a view. I think pathway can handle a null dd and strat.

**Comment by sgratzl** [comment]
I don't think that the pathway view is the problem but StratomeX and its BrickColumns, which are based on TablePerspectives.

**Comment by sgratzl** [comment]
> Unnecessary: "Select stratification" when adding independent column to unstratified dependent column (right now only possible for clinical parameters but if missing option is added this would also apply to unstratified pathways): since it is the only option in the first step we should drop it.

was introduced as part of #1482 (disable and not hide invalid options) but I will try to find a balance between hide and disable

**Comment by sgratzl** [comment]
extract the missing single pathway to an own ticket #1633
