### ISSUE TITLE
Option to Skip save recent project

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1632]
in my daily work I don't care about the recent project, but it costs me a lot of time to save it. 

I suggest an simple option to cancel the save recent project task during shutdown (maybe including a "remember me" option)

**Comment by mstreit** [comment]
I am not sure if this is a useful feature for end-users. How about turning off auto-save for the experimental version?

**Comment by ngehlenborg** [comment]
I agree, it's a nuisance for developers but quite the opposite for users.

**Comment by sgratzl** [comment]
wontfix
