### ISSUE TITLE
Missing TourGuide option: Adding standalone pathway

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1633]
coming from #1631: 

missing: adding pathway as unstratified and without mapping any data onto it.

comments:
by @alexsb 

> @cpartl is more qualified to say something to that, but I think it's possible. It's afair the default of the pathway standalone view where a strat is only later mapped to a view. I think pathway can handle a null dd and strat.

by myself:

> I don't think that the pathway view is the problem but StratomeX and its BrickColumns, which are based on TablePerspectives.

**Comment by ngehlenborg** [comment]
Let's move this to 3.0.4.

**Comment by sgratzl** [comment]
@cpartl any ideas?

**Comment by sgratzl** [comment]
extracted sub task to #1664 -> blocked by it
