### ISSUE TITLE
Create section in help or software for copyrighted/licensed materials used in Caleydo

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1636]
- [ ] create section, e.g. in about dialog
- [ ] include information for splash screen image (#1619)

**Comment by sgratzl** [comment]
include fatcow icons link: https://www.fatcow.com/free-icons

**Comment by sgratzl** [comment]
currently accessible via: About Dialog -> Installation Details -> Licensed Materials

don't like the text, change it: `LicenseInstallationPage.java`

**Comment by alexsb** [comment]
Should we acknowledge the various libraries? I think especially Pathvisio does deserve credit?
