### ISSUE TITLE
Cannot change left side of color mapping in header detail mode

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1641]
The left vertical line cannot be dragged. 
@cpartl and @sgratzl Can you confirm this behavior?

**Comment by mstreit** [comment]
The interaction with the toolbar of the header brick in detail mode does not work as well. I cannot close the detail mode anymore. The problem with the inactive toolbar is only present when columns are on both sides of the detail view.

**Comment by sgratzl** [comment]
yes I can

**Comment by sgratzl** [comment]
but I can drag just the line by picking it above the blue box. 
- I have no problem closing the detail mode

**Comment by mstreit** [comment]
@cpartl Can you try to fix this asap please. We want to release at 4pm today.

**Comment by mstreit** [comment]
@sgratzl yes, it is a problem with the order of the blue rectangle. 
The problem with the non-working close button is only present when the detail view is shown for the right column.

**Comment by cpartl** [comment]
Please test if everything works again...

**Comment by mstreit** [comment]
Works again. Thanks @cpartl
