### ISSUE TITLE
investigate why tree view scrolls beyond top position on Mac

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1643]
![screen shot 2013-09-19 at 9 23 45 am](https://f.cloud.github.com/assets/1216518/1172983/f9889806-212e-11e3-9f81-3774a49ddfd5.png)

![screen shot 2013-09-19 at 9 22 16 am](https://f.cloud.github.com/assets/1216518/1172984/00e36f2c-212f-11e3-9472-8d1b92ab98c2.png)

**Comment by mstreit** [comment]
Can't reproduce with the 3.0.4 release as well as the current HEAD version using the latest MacBook Pro 15.4'' model.
@ngehlenborg Do you still have this problem? If yes, with which version?
