### ISSUE TITLE
TCGA data browser content does not appear until focus is removed from project wizard on Mac

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1644]
Data is loaded instantaneously but not shown until I click on another window (e.g. splash screen).

**Comment by mstreit** [comment]
@ngehlenborg Please test again.

**Comment by ngehlenborg** [comment]
Still doesn't work. Same issue.

**Comment by ngehlenborg** [comment]
News: this only happens when I launch from within Eclipse but not when I launch using a build. Seems to be another strange issue related to Eclipse (maybe related to the broken file open dialog that never shows any files when I launch from within Eclipse ...)

**Comment by sgratzl** [comment]
another strange mac problem...
