### ISSUE TITLE
Is there a minimum amount of memory required to run Caleydo?

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1645]
We observed a "Could not create Java Virtual Machine" error when trying to launch on an old Windows 8 machine with 2 GB or RAM.
- [x] determine what happens if requested memory is larger than available memory
- [x] add notice on download page

**Comment by sgratzl** [comment]
current memory related jvm settings: `-Xms512m -Xmx2048m  -XX:MaxPermSize=256m`

**Comment by sgratzl** [comment]
seems to be a memory problem: 1GB RAM test vm:

![2013-09-20 12_48_21-](https://f.cloud.github.com/assets/4129778/1179900/5fb56240-21e2-11e3-866f-a25aa735e60a.png)

![2013-09-20 12_48_41-](https://f.cloud.github.com/assets/4129778/1179897/59012a9c-21e2-11e3-9e63-6a68eb932b59.png)

**Comment by sgratzl** [comment]
with the latest build it worked on my test vm (32-bit 1GB RAM)

what is missing is the download note (but I have no rights to do that) -> @mstreit

**Comment by mstreit** [comment]
Added: "Caleydo requires at least 2GB of RAM for the 64-bit versions and 1GB of RAM for the 32-bit version. For working with large projects we recommend at least 4GB."
see http://www.icg.tugraz.at/project/caleydo/caleydo-application-download
