### ISSUE TITLE
What pathway nodes should be considered equivalent?

### ISSUE THREAD

**Issue by cpartl** [Caleydo/caleydo#1647]
Currently, two nodes are considered equivalent (and therefore as portal), if they share at least one PathwayVertex. E.g. [IGFR,EGFR,ERBB2] and [EGFR, PDGFRA] are equivalent. However, this way you can highlight several context nodes that are equivalent to the focus node, but not equivalent to each other. I'm not saying that this is bad per se, but it might be confusing.

**Comment by alexsb** [comment]
Maybe we should  introduce color-codes for that? 

A colored frame showing that it is a multi-mapping, and a tool-tip showing the actual mapping?

**Comment by cpartl** [comment]
We should add tooltips, yes. Not sure if we should add more on-node colors.

**Comment by alexsb** [comment]
How about we draw a little triangle covering the lower left corner to indicate a multi-mapping. Works with the square we use for non-mapping.

**Comment by cpartl** [comment]
I agree that a triangle (or any other symbol) in gray or black would be better than color coding. However, the analogy to non-mapping is not really given. The square indicates, that an experimental dataset has no mapping for a node, but multi-mappings are inherent to the pathway map and not dependent on experimental data.
Btw. this is related to #1563

**Comment by cpartl** [comment]
Important consequence of the previous argument: you can have a multi-mapping for a non-mapping node

**Comment by alexsb** [comment]
I didn't want to make a functional analogy, I just wanted to point out that it works OK from a visual point of view. And we can do both at the same time - square on the right, triangle on the left.
