### ISSUE TITLE
Rework the way data is added to Entourage

### ISSUE THREAD

**Issue by cpartl** [Caleydo/caleydo#1648]
The current solution is specifically designed to work with the ccle dataset, but we need a more general solution.

We decided that we want to use Lineup for specifying assigned data. The following requirements must be met:
- Multiple datasets can be assigned at the same time (entourage-exclamation marks and enRoute)
- Multiple stratifications can be chosen and have to be applied to all assigned datasets
- Individual groups from stratifications can be selected/de-selected
- On-Node Mapping: Stratifications should be selectable for single datasets (which should also be selectable)

We decided that we want to have (at least) 3 lists for stratifications, the groupings of a selected stratification, and the datasets.

One issue in this regard is, whether we should display the stratifications independently of the dataset it corresponds to, or to use an approach similar to the stratomex assignment.

Pro independent (i.e., not filtered by datasets):
- Stratifications are applied to all datasets, in-line with enRoute
- Having two lists of datasets (one for viewing the associated stratifications and one for selecting the datasets to be assigned) might be confusing.

Pro dependent:
- Same approach as for stratomex and also dvi
- Listing several "4 CNMF Clustering" stratifications would might be confusing as the origin is not stated (although we could add the origin dataset to the label or in a different column, which could also be filtered)
- Only way that it is feasible to manage stratifications based on, e.g., copy number. The large number of strats would be prohibitive to use in combinations with others. 

In this regard, the application of stratifications from mutation status /cnv of individual genes might be interesting in the future. If I understood that correctly, currently all stratifications for all genes are calculated on demand for stratomex. I think we do not need that in this case, but rather add a stratification based on one selected gene at a time on demand.

Another decision we have to make is how we integrate lineup. We have different options:
- Integrate it directly into the data selection area of entourage. IMO this would be the best option in terms of integration/effective useability for showing/hiding this window. However, as entourage is in compatibility mode, some features of lineup might not work. Maybe we do not need these features, so @sgratzl what would not work? 
- Use one separate lineup swt view.
- Use several separate lineup swt views (one for each list). I actually do not like this solution, as it is not integrated at all and showing/hiding them would be much more effort than it is now.

**Comment by sgratzl** [comment]
> @sgratzl what would not work? 

dragging, mapping editor, [selection]

but I don't know it exactly

**Comment by alexsb** [comment]
I've updated the original text a little. A couple of questions:

> Pro independent (i.e., not filtered by pathways):

What do you mean with "filtered by pathways?

> Multiple stratifications can be chosen and have to be applied to all assigned datasets

There is always only a single stratification in enRoute/Entourage

> Stratifications are applied to all datasets, in-line with enRoute

That's IMO always the case, as it's essential for enRoute. ALL datasets have to have the same stratification, else the technique simply doesn't work. 

I'm for DS dependent listing of stratifications.

**Comment by cpartl** [comment]
> What do you mean with "filtered by pathways?

I never wrote that. This was maybe introduced by your changes!?

> There is always only a single stratification in enRoute/Entourage

Actually, we assigned multiple stratifications when we added "All".

> I'm for DS dependent listing of stratifications. 

We really have to be careful here not to confuse that with the dataset selection though.

**Comment by alexsb** [comment]
> I never wrote that. This was maybe introduced by your changes!?

Haha, indeed. I meant datasets. Edited.

> Actually, we assigned multiple stratifications when we added "All".

Yes, but that's a special case. Is there a use-case for really doing multiple stratifications?

**Comment by cpartl** [comment]
> Yes, but that's a special case. Is there a use-case for really doing multiple stratifications?

Good question, I can not really think of any right now. From an implementation point of view it does not really matter if we support it or not, because it already works that way in enroute. I guess it's just about being more restrictive in the UI, and if this is beneficial for the user in some way (maybe less complex).

**Comment by cpartl** [comment]
@sgratzl Can you start by setting up a lineup view with these lists? I can take over afterwards if you tell me how and where to react on actions.

**Comment by alexsb** [comment]
I think this ticket is largely resolved and the remaining minor issues are in separate tickets.
