### ISSUE TITLE
mapping editor is missing "filter" handles when using p-value/q-value mapping

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1651]
The handles (black lines with circular endmarkers) are missing when the p-value/q-value mapping (#1650) is applied:

![screen shot 2013-09-24 at 10 19 38 pm](https://f.cloud.github.com/assets/1216518/1205650/f71eab74-2588-11e3-8c75-e76334c2dbaf.png)

**Comment by sgratzl** [comment]
this is currently not possible. Since it is based on a custom JavaScript function, there is no way to interpret the code and infer minimum and maximum values out of it, which would be then used for the mapping editor features.

**Comment by sgratzl** [comment]
a simple workaround is to edit the first line of the JavaScript code and encode your filters here for the raw values.

**Comment by sgratzl** [comment]
since there is no way to parse the code, we could try to provide additional variables to the code about the filtering marker

e.g.

```
if (v < raw_marker_min || v > raw_marker_max) return NaN

variables: raw_marker_min, raw_marker_max, normalized_marker_min, normalized_marker_max
```

**Comment by sgratzl** [comment]
@ngehlenborg can you test it, please

variables:

```
filter.raw_min
filter.raw_max
filter.normalized_min
filter.normalized_max
```
