### ISSUE TITLE
remove Eclipse-specific README.html from build packages (seen at least in the Linux tarball)

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1654]

**Comment by sgratzl** [comment]
I just see a readme folder containing a readme_eclipse.html. 

did you mean that?

**Comment by ngehlenborg** [comment]
Yes.

**Comment by sgratzl** [comment]
based on http://vzurczak.wordpress.com/2011/05/22/removing-root-files-in-a-rcp-built-with-tycho/
