### ISSUE TITLE
DVI routing error

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1658]
I don't know why but sometimes my DVI looks like this:

![2013-09-26 13_48_25-caleydo - screenoncochemicalthresholdsclamped2 5 cal](https://f.cloud.github.com/assets/4129778/1217267/a7697860-26a1-11e3-87d6-22755c37a2c9.png)

**Comment by cpartl** [comment]
Can't reproduce this problem, any hints how to?

**Comment by sgratzl** [comment]
no, can't reproduce it by myself -> wontfix

**Comment by sgratzl** [comment]
reproduce:
1. open a single-view vis, e.g. crossword
2. assign one or more table perspectives
3. save project
4. load the saved project
5. switch to crossword view
6. close it
7. open it again using main toolbar menu
8. error appears in dvi, since the crossword view restored the old state
