### ISSUE TITLE
Create Lineup View for Entourage Data Assignment

### ISSUE THREAD

**Issue by cpartl** [Caleydo/caleydo#1662]
Create a lineup view for the assingment of data to entourage. It should contain:
- A list of stratifications. It should work in a similar fashion as with the StratomeX lineup, i.e. you select the datasets for which you want to see the stratifications. @alexsb and I decided that only one stratification shall be selectable at a time.
- A list that shows the groups of the currently selected stratification. It should be possible to check/uncheck individual groups.
- A list of datasets. It should be possible to check/uncheck individual datasets. Checked datasets should be shown in entourage using the selected groups of the selected stratifications.

**Comment by cpartl** [comment]
related to #1648

**Comment by alexsb** [comment]
Here is a mockup of lineup, the way I could imagine it:

![entourage_lineup](https://f.cloud.github.com/assets/2039375/1238827/d10feddc-29f0-11e3-85d6-b3909152a62e.png)

**Comment by sgratzl** [comment]
II started to work in a new branch: https://github.com/Caleydo/caleydo/tree/develop_genlineup

current state: 
- tour guide adapters are extracted
- stratomex is working again

@cpartl please checkout that branch and help me with the `EntourageAdapter`. Define and implement ways how to: 
- check if an element is visible
- add an element
  in Entourage

the current feature set is similar to StratomeX, I'm currently working on the dataset and grouping stuff

**Comment by cpartl** [comment]
What do you mean by "element"? 
A TablePerspective?

**Comment by sgratzl** [comment]
> What do you mean by "element"?
> A TablePerspective?
> element = element of the ranking table (AScoreRow). 

I assume that Entourage supports just a single record stratification. If so the simplest solution is to store the last updated row to show (via `update(...)`) and check for similarity in `isPreviewing` and `isVisible``

**Comment by sgratzl** [comment]
now a simple data domain selector is shown -> "injected" by the entourage plugin

in a similar fashion I'm going to implement the group selector

**Comment by sgratzl** [comment]
except for the Entourage logic, it is done
