### ISSUE TITLE
There is a weird "1" wikipathway

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1667]
See: 

![wiki](https://f.cloud.github.com/assets/2039375/1254483/d89a6122-2b76-11e3-8b77-94a136b8292f.png)

We should avoid this. If it's a problem in Wikipathways (i.e., this is listed as a pathway) we do want to create a manual exception for this. This is especially stupid because it's the first in the list.

**Comment by cpartl** [comment]
Hm, I currently have no overview about where we get the pathways from, but it is apparently part of the zip file we download (Hs_1_WP2356_53422.gpml and Hs_1_WP2356_53422.png). 
@sgratzl Can we just remove these files from the archive? Or are these files generated from somewhere?

**Comment by sgratzl** [comment]
> @sgratzl Can we just remove these files from the archive? Or are these files generated from somewhere?

for wikipathways all are stored on our server in the archive. So just remove the files from the archive and update it on the server. The rest should be done automatically.

**Comment by cpartl** [comment]
removed non-pathways from zip file on server
