### ISSUE TITLE
Add pathway database identification to pathway lineup in Entourage

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1668]
As in the pathway lineup for Stratomex this information is important. To save space, should we just use 'K' and 'W' and provide a KEGG and Wikipathways tooltip?

**Comment by sgratzl** [comment]
should that a be a categorical column, or just an pathway name prefix

**Comment by alexsb** [comment]
I think a categorical column would be smarter,  since this would allow to sort based on it, etc?

**Comment by sgratzl** [comment]
> I think a categorical column would be smarter, since this would allow to sort based on it, etc? 

and solve #1669
