### ISSUE TITLE
Merge free selection with path-based selection for choosing genes for enRoute

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1671]
By default selection runs in path mode. By pressing Alt the same time any node should be added. 

Was: "Create Icon for free selection of nodes."
Currently it's the same as the path selection icon.

**Comment by alexsb** [comment]
Actually thinking about this I'm not sure anymore that this should be a separate state. It would be much better to simply use a modifier (Ctrl?) key to select free nodes in the regular path selection mode.

**Comment by cpartl** [comment]
Hm, i guess there are trade-offs. A modifier is not really visible to the user, but selection might be easier if known. I vote for Alt, if we decide for a modifier.

**Comment by alexsb** [comment]
Yea, but if we use a modifier we can easily combine path and free selection, thereby making it clear to the user when there is an actual path in the pathway. 

We could add context-menus to the nodes when in path mode "add to path (shift-click)" to make it more salient?
