### ISSUE TITLE
Synchronize selected datasets and groups with entourage

### ISSUE THREAD

**Issue by cpartl** [Caleydo/caleydo#1676]
Currently entourage and the selections in lineup are out of sync initially, and whenever you click in entourage you lose the selections in lineup.
I added the methods `isDataDomainVisible`, `isGroupVisible`, `getSourceGroupList`, which in `EntourageAdapter` should provide you with the necessary information (if they work correctly ;-)).

**Comment by sgratzl** [comment]
I don't want to poll button states. Please, provide change listeners or events.

**Comment by cpartl** [comment]
These states only change by clicking the buttons in lineup. It is just about the initialization (we currently need some selected stratification/dataset at startup in entourage) and that it remembers its selection when entourage gets the focus. I think a change listener can't do much here...

**Comment by alexsb** [comment]
Here is an example of an initialization problem. The dataset is chosen correctly, but the groupings are not. Notice that the two copy number groups each contain all samples, not the 2 groups that one would expect driven by the 2cnmf clustering. 

![initialization](https://f.cloud.github.com/assets/2039375/1270386/3591000a-2d09-11e3-9322-1aeede013be5.png)

**Comment by sgratzl** [comment]
> but the groupings are not. Notice that the two copy number groups each contain all samples, not the 2 groups that one would expect driven by the 2cnmf clustering. 

grouping = stratification?, if yes: I think I can't fix that, since I don't know all the stratifications (especially mutations, copy-numbers,...) at any time, since they lazily created.

**Comment by cpartl** [comment]
Sync looks quite good now i think. 
What is missing:
- Synching the pathway mapped dataset (see `getPathwayMappingDataDomain`)
- Synching the selected groups.

**Comment by alexsb** [comment]
Maybe what @cpartl means is that the groups are not there for the initial state: 

![group_init](https://f.cloud.github.com/assets/2039375/1271799/a84fa2b4-2d21-11e3-8178-a99439d27167.png)

**Comment by alexsb** [comment]
You can still confuse the "Select All/Select None" state by changing the stratification after clicking on select all / select none. Here is an example: 

![select_all](https://f.cloud.github.com/assets/2039375/1273350/7560af82-2d45-11e3-91d6-942ddce8f108.png)

I suggest we remove the checkbox here and do a "Select None | Select All" that are both always visible and execute the respective action?
