### ISSUE TITLE
Allow to specify a single dataset for on-node mapping in entourage

### ISSUE THREAD

**Issue by cpartl** [Caleydo/caleydo#1677]
Up to now we specify the data that is assigned to enroute via lineup. However, we also want to specify the data for on-node mapping. But you can only display a single dataset at a time using on-node mapping.

The discussed solution:
Add another column to the dataset list, which uses radio buttons. The selected radio determines the dataset for on-node mapping.

I can take care of the communication to entourage, just provide me a method in `EnrouteAdapter` that is called when the radio is selected.

**Comment by sgratzl** [comment]
if you click at the label, what should change: checkbox or radio?

**Comment by sgratzl** [comment]
btw. this issue, #1675, and #1676 have nothing to do with LineUp anymore. The EntourageAdapter is hacking in the TourGuide and creating the elements by itself. -> `GroupElements.java`, `DataDomainElements.java`

**Comment by cpartl** [comment]
> if you click at the label, what should change: checkbox or radio?

Hm, I guess we have to try it out and see what is best.
I feel that either only selecting the checkboxes, or both (radios and checkbox) could work.
In the latter case clicking the label to de-select should of course only affect the checkboxes.

**Comment by alexsb** [comment]
Will be dealt with together with #1679
