### ISSUE TITLE
How to open/close lineup for dataset selection conveniently?

### ISSUE THREAD

**Issue by cpartl** [Caleydo/caleydo#1678]
We should be able to open lineup from entourage. 
How should this look like GUI-wise?
Static button somewhere? Where? Which icon?
Should we also be able to close lineup within entourage?

**Comment by alexsb** [comment]
Yes. Options:
- Opens by default with Entourage
- Opens as soon as you extend the selected path window 
- An extended selected path window contains a message and a plus sign to add data
- Add a button to the toolbar (not a big fan of that) 

Concerning closing: I wouldn't. The x button of the lineup is pretty clear.

**Comment by cpartl** [comment]
Yes, it should be opened with entourage by default.
I would vote for a button that just does open the lineup view, it should not be a side effect of a different action imo (e.g. extending the path window).

**Comment by alexsb** [comment]
Related to #1683

**Comment by alexsb** [comment]
How about we add a button "Select data" at the bottom of the Selected Path window if LineUp is not visible.

**Comment by cpartl** [comment]
I think we should place a button somewhere that is guaranteed to be visible, as the dataset assignment is not only for enroute. Since the selected path can be hidden, I would actually like to add a button to the toolbar for now...
