### ISSUE TITLE
How to enable/disable on-node mapping in entourage?

### ISSUE THREAD

**Issue by cpartl** [Caleydo/caleydo#1679]
It should be possible to enable/disable on-node mapping.
One possibility would be a button in the toolbar.
We could also use a checkbox in the header of the column for on-node mapping radios.
Other suggestions?
In any case, the radios should be grayed out when on-node mapping is disabled.

Discuss.

**Comment by alexsb** [comment]
Maybe a button in the toolbar wouldn't be too bad after all, combined with the options described in #1678. A click on the button would simply open lineup. 

I would tune the "Choose Dataset to Map Dialog to look like that:

![ds_selection](https://f.cloud.github.com/assets/2039375/1270150/5e666e4c-2d05-11e3-8c6c-c5014576ec86.png)

**Comment by cpartl** [comment]
So the toolbar button should just open lineup?
I would not draw a checkbox for "None", this makes no sense

**Comment by alexsb** [comment]
> So the toolbar button should just open lineup?

Yes

> I would not draw a checkbox for "None", this makes no sense

Oh, I disagree! I hate interfaces that have many options and don't have a select all/ select none button.

**Comment by cpartl** [comment]
ok, but this checkbox does not look like a select all/none to me.

**Comment by cpartl** [comment]
it is more a radio for the checkboxes...

**Comment by alexsb** [comment]
Includes considerations of #1677

**Comment by alexsb** [comment]
> it is more a radio for the checkboxes...

This is actually more like a button than a checkbox or a radio. I've checked a couple of interfaces and most use some kind of drop-down to "select all, none, etc." I'm not hung up on using a checkbox at all - happy to hear better suggestions - I just figured it's the most space efficient way to do it.

**Comment by alexsb** [comment]
This works excellently. I thought a little about the None radio box - we could instead have a "(disable)" next to "Map onto Pathway". If we decide to stick with the None radio we can close this.
