### ISSUE TITLE
Interface for determining which samples to map onto pathway

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1680]
Another problem is which samples to actually map: all samples of a dataset does not make much sense in most cases. 

There are two options: 
- Map the selected samples only - this will be weird if none are selected and samples are only selectable through enRoute. 
- Provide some means to pick the groups/samples. Then we'd actually need essentially the stratification lineup to let users choose that. There we have two options
  - Add a second row of check boxes in the choose groups menu similar to the choose datasets menu suggested in #1679.
  - Make the choosing of groups independent of the choosing of groups for enRoute (which will be confusing and requires a lot of space IMHO).

**Comment by cpartl** [comment]
Hm, I am not sure if we should provide an interface to select different groups than shown in enroute. That way enroute and the on-node mapping can get easily out of sync and the on-node mapping hints to the wrong nodes for detailed exploration.
I would use the same groups as for enroute and maybe additionally provide the option to use selected samples instead.

**Comment by alexsb** [comment]
Yes, that's what I meant. I didn't think about selecting different groups.

**Comment by cpartl** [comment]
What was the final solution we decided for here? Add the switch between selected and normal mode to the toolbar?
