### ISSUE TITLE
Groupings are duplicated when clicking into enRoute

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1681]
After assignement with lineup the grouping is correct: 

![correct](https://f.cloud.github.com/assets/2039375/1270442/02c55012-2d0a-11e3-83ca-5c6252a79690.png)

Once I click into enRoute the grouping is suddenly duplicated:

![duplicated](https://f.cloud.github.com/assets/2039375/1270445/13ca8472-2d0a-11e3-934c-997d904275de.png)

**Comment by cpartl** [comment]
prevented this from happening, but the root cause still remains: `onSelectionChanged` is still called when entourage gains focus. @sgratzl can you prevent that?

**Comment by sgratzl** [comment]
> @sgratzl can you prevent that?

done. setting no callback during state syncing

**Comment by alexsb** [comment]
Works. Closing.
