### ISSUE TITLE
Wizard for enRoute in Entourage

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1683]
- Right now in Entourage we have the "Select Path" window on the right which contains the enRoute view. We should either rename that to enRoute or relate in some other way that we can show experimental data here. 
- In the empty space of the selected Path view we should put the following text:

> To visualize experimental data select nodes in a pathway using the  "Toggle path selection button" ([PATH]) and use [LineUp] to specify which data to show"

Here [PATH] should be the actual (functional) "Toggle path selection" icon and the "Toggle path selection button" text should be underlined? and trigger the same action, while the [LineUp] text should open or activate LineUp.
- We should think about whether it is obvious enough that the experimental data in enRoute appears when you expand the view.

**Comment by cpartl** [comment]
What do you mean by "empty space"? There is no empty space when a long path is selected. 
Or should this wizard only be visible when no path is seleted?
As display space is cruical for entourage I think we should not show a wizard permanently...

**Comment by alexsb** [comment]
Yes, the idea was that this is visible when no path is selected. When a path is selected the user is already half-way there. We then can show some message in enRoute if no data is yet selected. 

The only thing to consider is whether we want to make the expand button more salient and communicate its meaning, but I'm not sure if that's necessary.
