### ISSUE TITLE
Trigger focus node out of LineUp?

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1685]
It would be interesting to use the LineUp rankings of genes (mutations and copy numbers) to trigger a pathway query that updates the pathway list. These would all be of equal rank of course, but it would still be helpful.

**Comment by cpartl** [comment]
Added what is necessary on the entourage end. @sgratzl Can you trigger a `LoadPathwaysByGeneEvent` out of lineup when using the context menu on one gene ranking element (e.g. mutations, copy number)?

**Comment by sgratzl** [comment]
done -> see EntourageAdapter -> FIXME

**Comment by alexsb** [comment]
Cool, but it would be nice if we could tell people right in the context menu that there is no mapping pathway when there is none (which is the case for roughly 4/5 of all genes).
