### ISSUE TITLE
How do we want to sync DVI and Entourage?

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1686]
DVI is currently not synced with Entourage data assignments. I'm not sure how we should do that. We basically create "foreign" perspectives all the time in this scenario, so we'd need to constantly add perspectives to the datasets in the DVI?

**Comment by sgratzl** [comment]
foreign table perspectives aren't visible in DVI. If you correctly trigger the TablePerspectiveChanged events, you should see this generic "this datadomain is used in that view" band.

**Comment by alexsb** [comment]
Supplement tool-tip to the generic band
