### ISSUE TITLE
change data package builder to ask for password and username on console if not supplied as a parameter

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1695]
That would allow us to keep this information out of the launch configs ...

If the user supplies "--username" and/or "--password" but does not provide the actual username or password, the package builder should prompt the user to enter this information on the console.

**Comment by sgratzl** [comment]
alternative eclipse only solution: http://stackoverflow.com/questions/313270/how-to-make-eclipse-prompt-me-for-command-line-arguments

AFAIK there is also a special passwort_prompt magic variable

**Comment by ngehlenborg** [comment]
I have implemented the Eclipse-only solution but we should still add the password prompt for other scenarios.

**Comment by sgratzl** [comment]
I will implement a similar approach using magic variables, (e.g. PROMPT) as the argument handler can't handle empty arguments.
