### ISSUE TITLE
Create Box Plot for use within StratomeX

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1697]
Critical for non-death clinical data

**Comment by alexsb** [comment]
A drawing by Nils:

![screen shot 2013-10-24 at 6 12 10 pm](https://f.cloud.github.com/assets/2039375/1404158/e70aebce-3cff-11e3-8d85-6ec8ac86fc0f.png)

**Comment by sgratzl** [comment]
draft part of develop_parcoords_feature branch:

![2013-11-25 12_05_12-caleydo - tcga_gbm_sampled cal](https://f.cloud.github.com/assets/4129778/1612337/9aba77be-55c1-11e3-892a-7b17b825888c.png)

Code in class `BoxAndWhiskersElement`

**Comment by sgratzl** [comment]
status quo: (develop branch)

![2013-11-25 18_07_42-caleydo - tcga_gbm_sampled cal](https://f.cloud.github.com/assets/4129778/1615060/233fe1c8-55f4-11e3-8974-2fa5f65e399b.png)
