### ISSUE TITLE
Dynamically update links to help in all Caleydo releases

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1706]
We will be starting to consistently version our help and thus we should make an effort to maintain the help links out of caleydo - they should always point to the relevant revision of the help. 

I suggest we only update the help with major version increments, e.g., 3.0; 3.1; 4.0, but not with minor increments such as 3.0.3 (this might lead to some inconsistencies - we should think about that). 

In addition we will maintain a develop version of the help, where all new features or changes should be immediately added (and if not immediately documented clearly marked with a TODO). This develop version will then at release time be moved to the release version. 

Thus, all help links must be updated from 

http://help.caleydo.org/develop to 
http://help.caleydo.org/3.* 

when releasing.

**Comment by sgratzl** [comment]
all help pages use the common preifx: `GeneralManager.HELP_URL`, which could be customized with the version, similar to the basic download url `DATA_URL_PREFIX`.

**Comment by sgratzl** [comment]
blocked by: new help url structure

**Comment by sgratzl** [comment]
since the new help is already online -> what is the pattern that should be used in `GeneralManager.HELP_URL`?

**Comment by alexsb** [comment]
```
"http://help.caleydo.org/" + majorVersionNumber + "/"
```

should work.
