### ISSUE TITLE
Can't load genetic data from scratch

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1708]
Finish button does not activate!

**Comment by cpartl** [comment]
Works for me in the cases I tested. So, what data? Which page? Which selected properties? Have you forgotten to fill some required fields?

**Comment by alexsb** [comment]
![no_loading1](https://f.cloud.github.com/assets/2039375/1465434/cb7e87f2-4561-11e3-8676-076242026521.png)

**Comment by alexsb** [comment]
Radio Load data from file option does not appear on my system.

**Comment by ngehlenborg** [comment]
I have the same and additional problems (text in description is scrollable???) on Mac OS X 10.9

![screen shot 2013-11-04 at 10 10 45 am](https://f.cloud.github.com/assets/1216518/1465569/7307811c-4563-11e3-80e3-5b9365ba1fa9.png)
![screen shot 2013-11-04 at 10 10 57 am](https://f.cloud.github.com/assets/1216518/1465570/7308cc66-4563-11e3-846b-0f14b4f7aa2c.png)
![screen shot 2013-11-04 at 10 10 39 am](https://f.cloud.github.com/assets/1216518/1465571/73096e50-4563-11e3-9311-ee8363b8678a.png)

**Comment by alexsb** [comment]
I also observe some inconsistent state of the finish button when clicking through the various menus. For example, if you come to the load project tab with an enabled finish button it is not automatically disabled when no project is specified.

**Comment by cpartl** [comment]
Added group around radio buttons, which seems to fix the problem of the disappearing button on my system. Added mechanism to keep finish button up-to-date when switching pages or modifying widgets. @alexsb Please check if it works for you now.

**Comment by alexsb** [comment]
Works. Closing.
