### ISSUE TITLE
Add version number to Splash

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1709]
Currently the version number is gone. Is that intentional?

**Comment by alexsb** [comment]
It seems to appear sometimes? When I moved the splash out of focus and back into focus it appeared. Is this a Linux issue, or can someone reproduce? I'm  testing with the 3.1.0 release version.

**Comment by sgratzl** [comment]
can't reproduce it on my windows system.

**Comment by alexsb** [comment]
Confirmed on Marc's Linux. 

In addition add "Caleydo _Qualifier_ - Project Wizard" to the project wizard title.
