### ISSUE TITLE
Reconsider Naming and SWT Tabs for various LineUp Instances. 

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1718]
I know we've discussed this in the past, but now that we use similar interfaces also for Entourage we should think about it again:
- Do we want a single LineUp SWT window for Entourage and StratomeX? These actually have quite a different function.
- Do we want to rename the "Other Lineup" for StratomeX to "Unstratified Data"? Other Lineup is essentially meaningless. 
- We could rename "Stratification LineUp" to "Stratified Datasets" for StratomeX
- We could rename "Stratification LineUp" to "Datasets and Stratifications" for Entourage
- For Entourage there is no difference between stratified and unstratified data for selections. The "Other Lineup" could be "Non-Genetic data", since everything else in Entourage is gene-centric?

**Comment by cpartl** [comment]
ad 1) I am not entirely sure. On the one hand it somewhat makes sense to use the same window, as in both cases some data is assigned to views. On the other hand, the way data is assigned differs quite siginificantly.
ad 2 - 3) Agreed that "other lineup" is not a good title. If we agree on this, we should make sure to unify the titles (use "data" or "datasets" for both)
ad 4 - 5) Basically the same as for 2-3. I just want to throw in that it might make sense to only use one lineup for entourage and use a special compartment for the non-genetic data. But I guess we should see how the 2 lineup solution works out.

**Comment by alexsb** [comment]
Stratifications - LineUp
Dependent Pathways - LineUp
Dependent Variables - LineUp

**Comment by sgratzl** [comment]
current strategy:
1. custom View instances per View Type -> split of Entourage and StratomeX LineUp views
2. icon of the LineUp views should be an annotated version of the corresponding "parent" view
3. like it is now, if the active view isn't handled by the LineUp instance -> "disable" it

Entourage Names: Stratifications, Non-Genetic
