### ISSUE TITLE
Add anotation and tool tip to pop-up button for enRoute

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1719]
If path is empty we should show an annotation that the enRoute view can be made visible with the button. We should always show a tool tip. 

@ngehlenborg  - you were stuck on that, right?

**Comment by ngehlenborg** [comment]
Tool tip might help a bit, but I think people don't expect to see a completely new view when they click a little arrow button that typically is used to close panels.

**Comment by alexsb** [comment]
Yea, so should we do aggregated visualization of the experimental data somehow? We should be able to make space for that.

**Comment by ngehlenborg** [comment]
Aggregated data shown as box plots?

**Comment by alexsb** [comment]
You're really into box plots these days ;).
