### ISSUE TITLE
Add generic mechanism for adding first time usage overlays

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#1722]
It would be nice to only specify a position and an overlay text. The rest should by handled by an generic overlay mechanism.

**Comment by sgratzl** [comment]
regarding position -> difficult to be reactive, ie. handle different screen sizes

using GLElements -> maybe attach to a specific element instance, and use its absolute position as reference. 

implementation: using GLElement layers -> mouse layer, popup layer, ...

another idea: implement a robot -> can simulate clicks. "inline tutorial"
