### ISSUE TITLE
Behavior for not-found entries in search in LineUp

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1724]
Currently there is no feedback if a search in LineUp has no result. Maybe we should follow the chrome approach - show 0 of 0 in red and also provide navigation buttons for multiple search results.

**Comment by sgratzl** [comment]
> multiple search results. 

just press enter / find again to search the next matching entry. If you click the `backward` button, it will look for the previous matching result.

**Comment by alexsb** [comment]
Yea, I'm aware of that, but you don't get any cue on whether this is the only result or one of hundreds.

**Comment by sgratzl** [comment]
rfc for 102c9f9
