### ISSUE TITLE
Path Selection Issues

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1726]
In this case, in the acute myeloyid leukemia pathway I wanted to select the lower path, but it wouldn't let me. 

![path](https://f.cloud.github.com/assets/2039375/1545168/ff70b50e-4d71-11e3-8e2f-32f9fb44b3d4.png)

Consulting the help, extending a path along a line should be done using Shift-Click, but Shift-Click now forces paths. If I do that it does work, but there is some bubble set bug:

![path_no_bubble](https://f.cloud.github.com/assets/2039375/1545359/32eaf43c-4d75-11e3-8366-deb61360bea7.png)

The traditional way of selecting an alternative path is also broken (see #1727).

**Comment by cpartl** [comment]
I can not remember why we dropped the picking of the alternative paths, but it think @dkalkofen did that on purpose. Maybe because of selection issues together with stubs? 
However, you can still switch to alternative paths using up and down keys.

**Comment by cpartl** [comment]
Btw: Shift + click does force a path only if there is none, otherwise it is an ordinary path extension (already visible when hovering over a node + shift).

**Comment by cpartl** [comment]
@alexsb Is this sufficiently fixed?

**Comment by alexsb** [comment]
Here, I wanted to play around with the path selections, and get now two paths with the same node:

![image](https://f.cloud.github.com/assets/2039375/1625660/f310f0dc-56d4-11e3-964b-450369e7c8b0.png)

**Comment by cpartl** [comment]
@alexsb Can you tell me what you did?

**Comment by alexsb** [comment]
Just use the force mode and click around - it's not hard to get ;).

**Comment by cpartl** [comment]
Clicking around in force mode like crazy, can't get it.

**Comment by alexsb** [comment]
![image](https://f.cloud.github.com/assets/2039375/1640266/d8185e62-5834-11e3-8cf9-83176612da5a.png)

Problem when adding node multiple times.

**Comment by alexsb** [comment]
Problem when adding node in the middle of a path again: 

![image](https://f.cloud.github.com/assets/2039375/1640285/4b2126aa-5835-11e3-874f-e6a19803933a.png)

**Comment by alexsb** [comment]
In the future, we have to decide, whether we want to allow duplicate node selections, and how we want to handle this in terms of bubble sets.
