### ISSUE TITLE
Dealing with variable sizes and groups in enRoute

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1729]
We currently have a couple of problems in enRoute, which are aggravated if we give only little space to enRoute:

We are in trouble if we have very many groups:
![many_groups](https://f.cloud.github.com/assets/2039375/1573344/2c358de8-512e-11e3-8fbc-083d46bf05a6.png)

Which is even worse if we have static sizes:
![many_groups1](https://f.cloud.github.com/assets/2039375/1573346/2c36318a-512e-11e3-8fa2-d4be28d8a662.png)

Static sizes also cause a cosmetic problem when we have only static elements:
![few_groups](https://f.cloud.github.com/assets/2039375/1573345/2c35f382-512e-11e3-9968-39bcff859b29.png)

A thing we could fix easily would be to remove the summary button that is currently always visible and make it pop-up like in LineUp.

The other issues are harder to fix. I would seriously consider defining a minimum size for a group and add scroll bars? One pixel per bar would make sense? Opinions?

**Comment by cpartl** [comment]
@alexsb Did that, you can now choose to fit enroute into the available space, or to use 1px per bar. Toggle using the new button above the gene names. RFC.

**Comment by alexsb** [comment]
Static spacing works, rest extracted to separate tickets.
