### ISSUE TITLE
State problems with LineUp / Entourage

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1730]
Once Entourage closes and is reopened it does not reflect the LineUp state, but is in the inital defaults. 

![lineup_entourage_states](https://f.cloud.github.com/assets/2039375/1573418/56a34f10-512f-11e3-9e12-e199dde73141.png)

**Comment by sgratzl** [comment]
lineup should be resetted not entourage

-> lineup is the slave view

**Comment by alexsb** [comment]
Maybe. We could even consider closing the views when the masters are closed?

**Comment by cpartl** [comment]
I agree, having an entourage lineup without entourage makes no sense.

**Comment by sgratzl** [comment]
I you have multiple entourage instances (is that possible?), you can't really decide, whether you should close LineUp or not

**Comment by alexsb** [comment]
Well, assuming that you have a completely oblivious LineUp, yes, but why must it be completely oblivious? It needs to track the view it is associated with, and it could check how many instances there are left. 

However, I start to wonder what the point of all this is - In the case of StratomeX and Entourage the LineUp views are extremely tightly coupled with the views. I wonder whether it still makes sense for them to be in separate top level windows that can exist independent from them, or whether it wouldn't make sense to integrate this into the respective parent view.

**Comment by alexsb** [comment]
I guess the main drawback will be that this breaks the way RCP handles views and that it's technically challenging.

**Comment by sgratzl** [comment]
1. it is currently not possible to technically integrate LineUp into StratomeX, Entourage (GLElements,...)
2. RCP views gives you more, e.g. you can move them to a separate window,...
3. I don't want to implement a multi view behavior over and over again in every view with all the logic behind.

what should be possible using RCP views: 
- open/close (we already do that)
- minimize / maximize (I read some blog post how one can do that)
