### ISSUE TITLE
Open Entourage by default in Caleydo

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1746]
One issue we have to think about: should we also open the lineup views by default for Entourage, as we do now, or should we do that only when, e.g., opening enRoute?

**Comment by sgratzl** [comment]
what about the sample projects -> doesn't ccle project open entourage by default?

**Comment by alexsb** [comment]
It makes sense to open a specific view for a specific sample project, yes, but this ticket is about the default behavior. 

CCLE does not open it by default ATM, but we can consider that.

**Comment by sgratzl** [comment]
when will you get the default behavior?

**Comment by alexsb** [comment]
When no view information is specified in a project. E.g.:
- somebody loads his/her own data
- using the TCGA projects other than sample

**Comment by cpartl** [comment]
Opening entourage when no view info is specified in projects. Currently the lineup views are no more opened when opening entourage, but opened, when enroute is visible the first time.

**Comment by alexsb** [comment]
That's ideal!
