### ISSUE TITLE
Views/Plugins must contribute their shortcuts to the global shortcut manager

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1747]
Currently, only global shortcuts are registered.

**Comment by sgratzl** [comment]
could be done via context:
- http://help.eclipse.org/indigo/topic/org.eclipse.platform.doc.isv/guide/workbench_cmd_bindings.htm
- http://javawiki.sowas.com/doku.php?id=en:eclipse-rcp:activatecontext

will require a handler per shortcut
