### ISSUE TITLE
Box Plots should show outliers

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1755]
For both, enRoute - @cpartl and StratomeX - @sgratzl.

**Comment by cpartl** [comment]
Points vs Lines to show outliers. Points (or stars) seem to be more common.
![box_plots_outliers_1](https://f.cloud.github.com/assets/4134949/1722761/56a8cbf8-624a-11e3-8288-e12cdb248f80.png)
![box_plots_outliers_2](https://f.cloud.github.com/assets/4134949/1722763/5ad62806-624a-11e3-851b-a5fa9ac103c2.png)

**Comment by mstreit** [comment]
yes, points are way more common. let's stick to them.

**Comment by mstreit** [comment]
In the point example from above you mark the min and max with lines. Shouldn't we use points only?

**Comment by cpartl** [comment]
We can do so.
