### ISSUE TITLE
Create new Lineup-Based Search View

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1761]
The current search view is completely obsolete, since we can't interact with it at all. 

I suggest we replace it with a lineup based search view, but we could also consider improving the functionality of the search view. 

We could also just replace the table with lineup, potentially with one table per ID Category?

Here is a list of features we'd like to have in the search view, on top of what is already there: 
- Adding a found entry (cell) to stratomex. Obvious for categorical datasets, for numericals I'd just add it as one block with one gene. 
- Finding pathways for a found entry
- Adding a found entry to enRoute

Please help think about this and expand this list!

**Comment by mstreit** [comment]
I agree that we need more functionality. However, I am also not sure if we should replace it with LineUp. Technically it would be possible I guess. But what would be the benefit? We would not use many of the LineUp features. Most of the extra features could be realized using the context menu or standard GUI elements.

**Comment by alexsb** [comment]
Yes, I'm not sure about whether we should use lineup either. What Lineup, however, is good at is when we think of the search view more as an ID browser. We could let users switch between the different IDs (patients, genes, pathways etc.) and show all of them before even typing a search term. There, LineUp could show attributes of the data associated with the entries, such as copy number status, mutation and box plots of datasets.

**Comment by mstreit** [comment]
I agree - this would be very useful.
@sgratzl Any technical issues that speak against it?

**Comment by sgratzl** [comment]
> @sgratzl Any technical issues that speak against it?

box plots won't scale that well. The rest should be possible.

**Comment by mstreit** [comment]
The new LineUp based ID browser is great - good job!
If you add pathways and context menu actions (such as "Add <element> to <view>") it can already replace the SWT-based search view.

**Comment by sgratzl** [comment]
> Adding a found entry (cell) to stratomex. Obvious for categorical datasets, for numericals I'd just add it as one block with one gene. 

see #1405

**Comment by alexsb** [comment]
Awesome! I'm adding wishlist stuff to separate tickets :).
