### ISSUE TITLE
Add a gene directly to the path

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1762]
Using e.g., the search interface, as discussed in #1761 we'd like to add genes directly to the path.

**Comment by cpartl** [comment]
We need to discuss how we should add them as this violates basic principles of enRoute: All genes that we see now have an associated pathway node. We do not have this for contextual data, but at the moment this is per definition non-genetic data.

**Comment by cpartl** [comment]
Add to the end of the path.
