### ISSUE TITLE
Find paths connecting two genes

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1763]
Given two genes, search for and list pathways and paths that connect these genes. 
These paths and their pathway should then be added to Entourage and the path should be highlighted in them.

**Comment by cpartl** [comment]
I guess we need some discussion on how the search/results presentation should look like.

**Comment by alexsb** [comment]
List with
- Length
- Nr Pathways
- Names of Pathways

**Comment by cpartl** [comment]
The KShortestPaths algorithm by JGraphT is currently not efficient enough for our purposes (i have not seen it terminating yet). According to the javadoc, it is a bellman-ford derivate that has a runtime complexity of O(k_n_(m^2)) (n= num nodes, m = num edges)
The graph we are operating on has 43092 nodes and 47429 edges.

The DijkstraShortestPath is efficient enough, but of course only gets one shortest path. Runtime complexity is O(n^2), but using a Fibonacci heap it takes O(m+nlogn).

Yen's algorithm for k shortest paths is more efficient than the bellman-ford, it takes O(kn(m+nlogn)). I found a Java implementation for this here: https://code.google.com/p/k-shortest-paths/downloads/detail?name=KShortestPaths_JavaVersion_v2.0.zip&can=2&q=
but it uses its own (extremely unhandy) graph data structure.
