### ISSUE TITLE
Finish button not active in initial screen on Windows

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1767]
See: 
![image](https://f.cloud.github.com/assets/2039375/1687379/1eb19030-5df5-11e3-8911-dd145aba699d.png)

Reproduced on two different Windows Machines with 3.1.1 release

**Comment by cpartl** [comment]
Could only reproduce and fix a disabled finish button at the start, but it was enabled when changing the selection. This does not seem to be the case in the screenshot. Please check again.
