### ISSUE TITLE
Associate observations with statistical significance

### ISSUE THREAD

**Issue by wassermai** [Caleydo/caleydo#1769]
E.g. correlate cell line sensitivity to a compound with mutation or expression status of a specific gene
For mutation status, Fisher's exact test could be applied; for gene expression data we could rather think of a Kolmogorov-Smirnov Test or divide gene expression data into two categories (normally expressed vs. over/underexpressed) to uniformly apply the same test for all data.

Here is an example for how the interface for selecting a threshold could look like:

![problemdescription](https://f.cloud.github.com/assets/2039375/1694107/15635094-5e9b-11e3-924c-d12c6374547b.png)

**Comment by alexsb** [comment]
For the interface - we also discussed to use a slider in Y direction or specific numerical values. That would be independent of sorting, and would be visually similar to the above sketch.

**Comment by alexsb** [comment]
We do want to have multiple categories: sensitive, in between, and not sensitive
