### ISSUE TITLE
Have a global search across all visible columns as an SWT Toolbar

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1771]
Searching in all ID Types

**Comment by sgratzl** [comment]
search or filter?

**Comment by alexsb** [comment]
Hmm, filter might make more sense!

**Comment by sgratzl** [comment]
requires: or filter, instead of and (currently)

**Comment by sgratzl** [comment]
see Caleydo/org.caleydo.view.lineup#6

workaround: create a "fat" column, containing all ids (at least virtually, it could just show the primary) and use that for filtering

**Comment by alexsb** [comment]
The disadvantage of a fat column would be that we couldn't highlight the cell where the entry was found.
