### ISSUE TITLE
Sorting for compound data types

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1773]
Right now sorting obviously works only for simple things like numbers and text. It would be cool if we could define some measures to sort other, compound columns, such as copy number mutations, etc. 

Some suggestions:
- Sort numerical data by magnitude of standard deviation

For categorical data it's tough, but 
- for those that have a defined "normal" type, we could sort by the nr of elements that have a non-normal type. 
- We could let users define a category to sort by

RFC!

**Comment by sgratzl** [comment]
> for those that have a defined "normal" type, we could sort by the nr of elements that have a non-normal type. 

"normal" type, there is no formal description of that semantic -> hack

**Comment by alexsb** [comment]
There should be one, and I thought there already was. We do know it from the data, and we apply it in CategoricalClassDescription: 

```
public void applyColorScheme(ColorBrewer colorScheme, CATEGORY_TYPE neutralCategory, boolean reverseColorScheme)
```

So that wouldn't be hard to store.
