### ISSUE TITLE
Actions triggered through ID Browser

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1776]
The ID Browser is great, but it doesn't let you do anything right now. We should think about what actions we want to enable based on it. Generally we want to use regular selections based on it (showing up in the selection manager). 

For **Genes** we might want to:
- Choose Pathways and enable the pathway actions (see pathways)
- Add them directly to a path in enRoute (see #1762 )

The next question is, do we want to enable cell selections. If we do that, we could say "add the copy number of gene CCNY to StratomeX", or "Add the (unstratified) gene expression of gene CCNY to StratomeX". 

For **Pathways** adding it to Entourage already works. Do we also want to allow adding to StratomeX? Here, the reference column will be the problem. 

Also, we should be able to show the pathway on the source database, but that's an action that would be helpful also as a context menu action for pathways (see #1775 ). 

This should be discussed - some of these actions are redundant with the data assignment lineups.

**Comment by sgratzl** [comment]
requires: cell based context menus (not yet implemented)

see Caleydo/org.caleydo.view.lineup#7
