### ISSUE TITLE
Mouse-wheel scrolling is broken

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1777]
It seems to be broken consistently for all GL Views.

**Comment by sgratzl** [comment]
old GLViews or new GLElementViews or both?

**Comment by alexsb** [comment]
As far as I can tell it's both.

**Comment by sgratzl** [comment]
I can use the mouse wheel to
- StratomeX: zoom (ctrl+mouse wheel)
- LineUp: scroll

**Comment by cpartl** [comment]
Scrolling also works for me in lineup views, enroute/entourage, stratomex zoom etc. The focus has to be on that view though (click into the view). However, it does not seem to work for scrolling the pathway list in entourage and in the entourage stratification lineup, the stratification list is the only one that can be scrolled via mouse wheel. Can we maybe change that behaviour to scroll the GLElement that is currently hovered by the mouse?

**Comment by sgratzl** [comment]
> However, it does not seem to work for scrolling the pathway list in entourage and in the entourage stratification lineup, the stratification list is the only one that can be scrolled via mouse wheel. Can we maybe change that behavior to scroll the GLElement that is currently hovered by the mouse?

scrolling via the scrollbars should always work. 

regarding current GLElement: I can change that. 
A related problem is that we don't currently have the notion of "focus" in the GLElements, so there is no way to have GLElement specific key listeners. (as you can use the arrow keys, page up, page down,...,too)

**Comment by cpartl** [comment]
> scrolling via the scrollbars should always work. 

Yes, i meant scrolling via mouse wheel.

**Comment by sgratzl** [comment]
> pathway list in entourage

can't fix it -> old picking listener doesn't support `PickingMode.MOUSE_WHEEL`

others should be fixed

**Comment by cpartl** [comment]
> pathway list in entourage

fixed that

**Comment by alexsb** [comment]
Much better. Open Issues: 

Mouse-wheel scrolling of zoomed views (broken off into #1780)
Mouse-wheel scrolling of dataset lists in Entourage's lineup
