### ISSUE TITLE
closing narrow (categorical) columns in StratomeX almost impossible

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1785]
The problem is that the click area for the  "X" button does not line up with the button. One has to click to the very right of the button in order to trigger the event. I think this has to do with the additional button in that toolbar.

![screen shot 2013-12-17 at 11 19 22 am](https://f.cloud.github.com/assets/1216518/1765525/3db8bde6-6737-11e3-8d22-fa7f469d9c80.png)

**Comment by sgratzl** [comment]
I removed the box plot vis for categorical data, since it doesn't make any sense. It won't solve the cause but removes the symptom.
