### ISSUE TITLE
do not allow insertion of new independent column between independent column and existing dependent column

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1792]
In this case it is possible to query using the wizard, but the preview or insertion don't work at all. We should simply not show the wizard button between independent and their dependent columns.

**Comment by ngehlenborg** [comment]
Interestingly, it is possible to insert an independent column between existing indep/dep pair if it is inserted using the "Select stratification from list" option.

**Comment by ngehlenborg** [comment]
Strange: sometimes it seems to be possible to insert between a indep/dep pair using a query and sometimes it doesn't work. There are no errors or warnings in the log.

**Comment by ngehlenborg** [comment]
It seems to depend on the query: "Based on similarity to the displayed stratification" doesn't work (currently not even between an indep/indep pair) and "Based on overlap with displayed set" does work.

**Comment by sgratzl** [comment]
the "Based on similarity to the displayed stratification" should be fixed. 

regarding adding something between an independent/dependent pair: this is not that easy, since there is no real connection between the two items. e.g. you can drag the columns arbitrarily.

**Comment by sgratzl** [comment]
> regarding adding something between an independent/dependent pair: this is not that easy, since there is no real connection between the two items. e.g. you can drag the columns arbitrarily. 

waiting for comments...
