### ISSUE TITLE
Flickering of new pathway thumbnails in entourage

### ISSUE THREAD

**Issue by cpartl** [Caleydo/caleydo#1797]
The thumbnail that uses the new pathway sometimes disappears in entourage and is only visible when you hover the window of that thumbnail. Might be an issue with the shader, as non-shaded elements are always visible. Could also be a problem with adapting form GLElement to ALayoutRenderer and back again.

How to reproduce: Add pathway "Adherens junction" -> Add pathway "Adrenergic signaling in cardiomyocytes" -> switch "Adherens junction" back into focus

**Comment by sgratzl** [comment]
I can't reproduce it

**Comment by cpartl** [comment]
As alex could also not reproduce it, it might be a problem with my setup/hardware.

**Comment by cpartl** [comment]
Flickering does not occur when the shader is disabled
