### ISSUE TITLE
Integrate attributes for mappings

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1799]
For the compound gene mapping we also have properties describing the type of the mapping (e.g., inhibition, activation). This is not specific to a compound, but specific to a mapping. Therefore we need to store this information with the mapping. 

We have 2 alternatives:
1. Store this directly in the mapping manager with a new meta-data object.
2. Create an "artificial" dataset containing this information.

@cpartl  and I think option 1 would be preferable. Opinions?

**Comment by mstreit** [comment]
Option 2 seems to fit better to our current way of mapping IDs as we store the mappings in hash maps.

**Comment by mstreit** [comment]
We agreed to create a new ID type INTERACTION_ID for which we load mappings to genes and compounds. 
We load the attributes from a dataset file that uses the INTERACTION_ID.
