### ISSUE TITLE
column selection frame is sometimes inverted

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1808]
I haven't been been able to reliably reproduce this, but occasionally I get an inverted column selection frame. The "Add new dependent column" button doesn't show up either in that situation.

![screen shot 2014-02-21 at 9 40 40 am](https://f.cloud.github.com/assets/1216518/2231258/15560498-9b0e-11e3-9c1e-c95a0b89cf73.png)

**Comment by ngehlenborg** [comment]
This problem seems to occur in particular when the "ungrouped" column is split (I also change the order of the blocks after the split). After closing the StratomeX view and re-adding the previously split columns (which are still split), the frame and the "add dependent column" button are rendered correctly.

**Comment by ngehlenborg** [comment]
But after working with the re-created view for a while, the selection frames start showing up inverted again. I only added and removed a few pathways that I had found using GSEA and PAGE.

**Comment by ngehlenborg** [comment]
To reproduce:
1. Add two columns.
2. Swap order of columns using drag and drop.

![screen shot 2014-02-28 at 1 27 41 am](https://f.cloud.github.com/assets/1216518/2291577/b2eb1e2c-a041-11e3-8442-895a32bc3c8e.png)
![screen shot 2014-02-28 at 1 27 49 am](https://f.cloud.github.com/assets/1216518/2291578/b2eb3844-a041-11e3-8a48-36d0507576ce.png)

**Comment by sgratzl** [comment]
part of  8d3fde1

**Comment by ngehlenborg** [comment]
Still happening unfortunately (the selected column is a single gene homogeneous matrix):
![screen shot 2014-03-17 at 2 54 05 am](https://f.cloud.github.com/assets/1216518/2433870/4817bc3c-ada1-11e3-9d73-f1b4977c6b1c.png)
