### ISSUE TITLE
pathway image quality very poor

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1809]
Sometimes I get these extremely pixelated pathway images. It seems to depend one the data type mapped to the pathway (e.g. looks great for RPPA, looks awful for mRNA-seq).

![screen shot 2014-02-21 at 11 03 47 am](https://f.cloud.github.com/assets/1216518/2231610/e7c03f2c-9b11-11e3-845a-80a005c6b4f6.png)

**Comment by ngehlenborg** [comment]
Another example (RPPA left, mRNA-seq right):

![screen shot 2014-02-21 at 11 18 39 am](https://f.cloud.github.com/assets/1216518/2231775/de0f6352-9b13-11e3-82f6-7383cfda5f41.png)

**Comment by cpartl** [comment]
Hm, I can not reproduce this issue
![no_bug_with_overlay](https://f.cloud.github.com/assets/4134949/2233324/af6246ea-9b28-11e3-9f49-145c33636614.png)

**Comment by ngehlenborg** [comment]
@mstreit: Can you reproduce this on your Mac?

**Comment by mstreit** [comment]
No, it looks fine on my machine. I've tried to reproduce it with same data and pathway.

**Comment by cpartl** [comment]
Is this still an issue?

**Comment by ngehlenborg** [comment]
Yes, but apparently only on my machine. Closing for now.
