### ISSUE TITLE
Firehose data loading for full raw data matrices includes normals

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1812]
This should only include tumor samples.

Solution: load sampled data from analysis run first and use the sample list from there as filter on data from standard data run.

**Comment by sgratzl** [comment]
possible alternative: regex filter (filter all `.*-11`) or vice versa: just allow all (`.*-01`)

**Comment by ngehlenborg** [comment]
Unfortunately not all tumor sets in Firehose are solid tumors (i.e. they might be blood derived tumors, which is -03) or they might be metastatic samples (which are -06): https://tcga-data.nci.nih.gov/datareports/codeTablesReport.htm?codeTable=Sample%20type

In order to get the samples matching the analysis run data, we need to use that sample list as a filter.
