### ISSUE TITLE
GSEA score for binary stratification not identical

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1814]
in a binary stratification, if you click on one group you will get a different result, when you click the opposite one.

**Comment by sgratzl** [comment]
I don't understand it:

mRNA and mRNA-seq -> results have inverted signs and the results are in the range -1/+1
RPPA -> results are the same, if you know that the range is -unbound / + unbound (I got values of ~ 107)

**Comment by sgratzl** [comment]
it has something to do with the normalization. 

If I take the log before computing the correlation in the mRNA case, I will get the same behavior (=same ranking for each group) as in the RPPA case

**Comment by sgratzl** [comment]
@ngehlenborg any ideas how we can fix this?

**Comment by ngehlenborg** [comment]
No idea yet, I need to better understand how the results are computed. 

How are you computing the correlation? 

a = (a1,a2,a3)
b = (b1,b2,b3)

cor(a,b) = ?

**Comment by sgratzl** [comment]
you are misinterpreting the GSEA:

input is always just a single group and its stratifications, there are no two stratifications.

```
input: stratification s and selected group a, f(row, gene) -> expressionvalue
b = s \ a //s without a
a, b ... sets of samples


for g in genes -> compute its signal2noise ratio using the samples:
 a_n = length(a)
 a_m = (sum of f(a_i, g)) / a_n
 a_s = (sum of f(a_i,g)^2) / a_n - (a_m*a_m)
 a_s = sqrt(abs(a_n / (a_n-1) * a_s))

 b_n = ... same for b

 m = a_m - b_m
 s = a_s - b_s
 signal2noise =  m / s

Afterwards, this signal2noise(gene) list will be used to compute the enrichment score for the pathway gene set.
```

> a = (a1,a2,a3)
> b = (b1,b2,b3)
> 
> cor(a,b) = ?

**Comment by ngehlenborg** [comment]
Can we re-do the analysis done in #1492 for this case? Does the original implementation yield the same asymmetric results with our data?

**Comment by sgratzl** [comment]
in the original implementation the signs are inverted in a binary case.

problems: 
- rppa has duplicated genes in it + some unmappable ones -> from 166 to 123
- mapping: for comparison the genes are mapped to their primary counterpart, for some genes in mRNA, RPPA, we have no counterpart -> have to filter it out in R
- there are some precision errors, which I can't overcome, in the area after the third position 

the computation of the signal2noise values is correct, however there was a bug within the enrichment score, which applies especially to small gene sets. the original implementation seem to preprocess the gene sets such that only the intersection is tested. 

btw. R Studio has a quite useful debugger.

![2014-03-05 14_06_24-caleydo - 2013_05_23_kirc_no_sample_duplicates_no_rppa_gene_duplicates cal](https://f.cloud.github.com/assets/4129778/2333671/1f0740b4-a46f-11e3-8c8b-8afdad84a9f3.png)
![2014-03-05 15_02_37-caleydo - 2013_05_23_kirc_no_sample_duplicates_no_rppa_gene_duplicates cal](https://f.cloud.github.com/assets/4129778/2333672/20401fe6-a46f-11e3-9cd4-3b102b8b59c4.png)

**Comment by ngehlenborg** [comment]
How did you remove the duplicate genes in the RPPA matrix? We should probably compute the average across duplicates, removing some "at random" would be hard to justify.
