### ISSUE TITLE
Loading large heterogeneous tables as data sets leads to LineUp performance degradation

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1815]
LineUp (and Caleydo in general) becomes extremely slow due to high CPU load. 

To reproduce:
- download http://gdac.broadinstitute.org/runs/stddata__2013_05_23/data/KIRC/20130523/gdac.broadinstitute.org_KIRC.Merge_Clinical.Level_1.2013052300.0.0.tar.gz
- extract
- load KIRC.clin.merged.txt as heterogeneous data matrix with all default settings

**Comment by sgratzl** [comment]
I think the problem is the DVI. I loaded the transposed version of the file and when I close the DVI the performance is as usual.

**Comment by sgratzl** [comment]
I improved the performance of the DVI but it is easier to just close the DVI before you import this dataset.

background: we have around 500 categorical columns. For all of them table perspectives are automatically created = 500 record & dimension perspectives = 250.000 cells within the node

**Comment by sgratzl** [comment]
extract refactoring of DVI for this to #1819
