### ISSUE TITLE
Install issue 

### ISSUE THREAD

**Issue by HendrikStrobelt** [Caleydo/caleydo#1818]
When following the Wiki procedure for developer install I still cannot resolve all dependencies. The timestamp issue\* seems to prevent the installation of plugins from the two p2 directories:

1) http://dev.caleydo.org/nexus/content/groups/public-p2/

2) http://dev.caleydo.org/nexus/content/repositories/thirdparty/.meta/p2
#### What I tried for diagnostics:

I can install the components from the meta-repo (1) by hand (means "update eclipse") in eclipse and this solves the related issues. For repo (2) this procedure does not work, since the packages are at least not visible.

I guess the problem is related to recent changes server-side. It does not occur where dependencies are already resolved 

![screenshot 2014-03-01 20 20 32](https://f.cloud.github.com/assets/950990/2303205/2be555be-a1a9-11e3-871b-5e1a2e6d1cc7.png)

*when changing and reloading the target -- for the each of the p2 repos an error occurs:
"Cannot remove the current profile timestamp"

**Comment by alexsb** [comment]
I have the same problems with the target definition, but it doesn't result in the failure to include external libraries for me. 

I can confirm that it's not a setup or legacy configuration issue - we did a completely clean install following the instructions by letter multiple times.

**Comment by sgratzl** [comment]
@HendrikStrobelt can you test it again, please?
