### ISSUE TITLE
box plot axis labels and margins

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1820]
- [x] labels on x axes are overplotted
- [ ] there should be some margins in the detail view, right now some of the whiskers are plotted on top of the frame for the block

![screen shot 2014-03-03 at 7 11 27 am](https://f.cloud.github.com/assets/1216518/2309182/34477e10-a2cd-11e3-8fe4-0c6bae2d3596.png)

**Comment by sgratzl** [comment]
see also #1788
