### ISSUE TITLE
changing the gene view changes the histogram

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1825]
left: ungrouped, right: tree clusterer (dragged over from different data matrix - mRNA-seq, which is the same data type as the one shown). Note that data loading already caused #1824.

![screen shot 2014-03-11 at 10 17 21 pm](https://f.cloud.github.com/assets/1216518/2393265/9f0322ac-a98c-11e3-879a-5c0649a6c665.png)

**Comment by ngehlenborg** [comment]
It turns out that this is caused by a gene view with much fewer genes on the right. 

Could we plot a small n = XXX into the top right or left corner of the histogram to avoid such confusion in the future?

**Comment by sgratzl** [comment]
> Could we plot a small n = XXX into the top right or left corner of the histogram to avoid such confusion in the future?

isn't it part of the dataset info? -> within Persp. ... item
