### ISSUE TITLE
order of boxes in box plot column header does not reflect order of blocks

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1827]
The boxes should have the same order as the blocks in the column. Right now this is not the case if the blocks have been reordered.

This is somewhat related to #1821. 

![screen shot 2014-03-12 at 8 46 07 am](https://f.cloud.github.com/assets/1216518/2397060/61348d5a-a9e4-11e3-861f-8e91f4e04016.png)

**Comment by sgratzl** [comment]
also related to #1822 

the order of the groups within the box plot is extracted from the perspective, so order changes should update the underlying the perspective.
