### ISSUE TITLE
Offer gradient variants of GLGraphics primitives

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1836]
GLGraphics is very convenient for drawing simple shapes. However, if you want to do gradients, you have to fall back to drawing vertices in gl - which is annoying. 

Gradients are very common for situations where you want both a mouse over and a selection, like here: 

![image](https://f.cloud.github.com/assets/2039375/2427472/cc2ab464-abeb-11e3-837d-d2144c446f4a.png)

A possible solution would be a gradient state flag, alternative to parameters.

**Comment by alexsb** [comment]
This could either be state based, such as this 
`GLGraphics.gradientColor(topColor, bottomColor)`
Or it could be overloaded to the rectangle and fillRect (the most imporant candidates)
`GLGraphics drawRect(float x, float y, float w, float h, topColor, bottomColor)`

**Comment by sgratzl** [comment]
from my point of view, the `GLGraphics` should have a rather small public api

alternative (without direct gl calls)

```
g.drawPath(new ColoredVec2f(0,0,topColor),new ColoredVec2f(w,0,topColor),new ColoredVec2f(w,h,bottomColor),new ColoredVec2f(0,h,bottomColor))
```

or using the new PathBuilder

```
PathBuilder.empty().rect(0,0,w,h, topColor, bottomColor).drawLoop(g)
```
