### ISSUE TITLE
cannot switch single column homogeneous numerical matrix to box plot view

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1839]
Only heatmap (regular blocks) or histogram (header) are available.

![screen shot 2014-03-17 at 3 03 22 am](https://f.cloud.github.com/assets/1216518/2433900/45d97b30-ada2-11e3-8d8e-5302bfd789bb.png)

**Comment by sgratzl** [comment]
It seems to be that the specific column has been identified as a categorical one. This happens when the underlying table is a categorical table (e.g. copy number) or the column is categorical in a inhomogeneous table.
