### ISSUE TITLE
ScrollingDecorator + Scissor test

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#1842]
the scissor test should only be applied to the direction, in which the `ScrollingDecorator` is defined, i.e if it is just used to scroll horizontally only the horizontal part should be culled away.

reason: 
 In Lineup I use the standard horizontal clipping, but a custom vertical one. The problem is that some popup menus disappear, since the are now culled away.

**Comment by cpartl** [comment]
i think this can be closed.
