### ISSUE TITLE
How to use StratomeX using two classifications

### ISSUE THREAD

**Issue by fbrundu** [Caleydo/caleydo#1849]
Hi,
I am trying to use StratomeX to relate two classifications but unfortunately I am not understanding if it is possible and how to achieve it.

For example, I have two classifications, defined each as:

```
Name        Class
sample1         1
sample2         1
sample3         3
sample4         2
```

Using the first column (sample name) is it possible to use StratomeX to relate the two classifications?

Thanks

**Comment by alexsb** [comment]
Hi,

the easiest way to achieve this is to load your classification as categorical data. You can do that using two separate classifications or in one file, like that: 

```
    Name        Class1     Class2
    sample1         1          1
    sample2         1          2
    sample3         3          2
    sample4         2          1
```

You can do that by choosing "categorical" on the second page of the data import wizard. 

If you're having troubles you can also send us a file and we'll check it out and send you a project.
