### ISSUE TITLE
Caleydo doesn't seem to honor proxy settings

### ISSUE THREAD

**Issue by serverhorror** [Caleydo/caleydo#1854]
Hi,

Running `./Caleydo` doesn't seem to honor the proxy settings. From all I can tell the only way to get to a running state is to actually download the `` file (which is actually rather hard to find) and start Caleydo then.

It may be that I have to wait longer but I gave up after 10 minutes, there should be a reasonable timeout in any case

``` shell
$ env | grep _proxy
http_proxy=http://localhost:3128/
ftp_proxy=http://localhost:3128/
https_proxy=http://localhost:3128/
no_proxy=localhost,127.0.0.0/8,::1
```

**Comment by sgratzl** [comment]
I started to integrate the network proxy settings preference page from eclipse, following  http://blog.vogella.com/2009/12/08/eclipse-rcp-proxy-preference/

In the meanwhile you can try to set your proxy settings directly by manipulating the `Caleydo.ini` file. Just append new lines like:

```
-Djava.net.useSystemProxies=true
```

According to http://docs.oracle.com/javase/6/docs/technotes/guides/net/properties.html
the relevant system properties are: 

```
java.net.useSystemProxies (default: false) ... if set to true it should detect your system settings
http.proxyHost (default: <none>)
http.proxyPort (default: 80 if http.proxyHost specified)
http.nonProxyHosts (default: <none>)
```

**Comment by sgratzl** [comment]
see also 2cf8d74ce5be1db9265cc337373a35ba71939f69, b52bbc4b5f23318a04b5df5b128c3e843318bcd2, and 0d5006250341fde06d1497ec0c44eb8d74cd0d59

**Comment by sgratzl** [comment]
I created a system property: `org.caleydo.cache.offline` if set to `true`, via `-Dorg.caleydo.cache.offline=true` within `caleydo.ini` then it forces that just the current cache is used, without checking for updates or download new stuff

**Comment by serverhorror** [comment]
Hi,

Thanks I will try it again next week. I'm not in a place where I can
replicate the situation right now

On Thu, Sep 25, 2014 at 12:47 PM, Samuel Gratzl notifications@github.com
wrote:

> I created a system property: org.caleydo.cache.offline if set to true,
> via -Dorg.caleydo.cache.offline=true within caleydo.ini then it forces
> that just the current cache is used, without checking for updates or
> download new stuff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Caleydo/caleydo/issues/1854#issuecomment-56802206.

## 

http://www.xing.com/profile/Martin_Marcher
http://www.linkedin.com/in/martinmarcher
Mobil: +43 / 660 / 62 45 103
UID: ATU68801424

**Comment by serverhorror** [comment]
No that was some laag.

This is what I currently see.

`org.caleydo.cache.offline` -- seems to work as expected. Upon startup it's caching pathways and Caleydo comes up

The jvm proxy settings do not seem to work. The environment here is an authenticating proxy (NTLM and/or Basic). Caleydo seems to just hang there and has no feedback
