### ISSUE TITLE
allow import of data from SQL databases

### ISSUE THREAD

**Issue by HendrikStrobelt** [Caleydo/caleydo#1855]
In the discussion with companies it turned out to be a very useful feature to import data from databases like MySQL, Oracle, postgres, Vertica... all of them should have a ODBC connector library. The database type information could already be used for the prediction of data types.

**Comment by sgratzl** [comment]
are we talking about a real jdbc - odbc bridge or using "native" jdbc drivers? - providing jdbc drivers for all possible databases isn't that easy
