### ISSUE TITLE
Statistical test: Wilcoxon rank sum test

### ISSUE THREAD

**Issue by wassermai** [Caleydo/caleydo#1860]
Implement Wilcoxon rank sum test in addition to Fisher's exact test. 
Test explanation: http://en.wikipedia.org/wiki/Mann%E2%80%93Whitney_U_test

Fisher's exact test is better for categorical data (mutation status), whereas the Wilcoxon rank sum test is better for continuous data (expression levels, copy numbers).

**Comment by cpartl** [comment]
I do have 2 basic questions regarding this test:
- How would this test be applied to our problem? The only way I can imagine at the moment is to select two groups like in the fishers test. As the data of these groups can be different (e.g. copy number vs expression) it would need to be normalized between 0 and 1 to make it comparable for calculating the ranks, but I am not sure if that's a good idea.
- If I understood the test correctly, it compares two distributions. But is that enough to detect correlations?

**Comment by wassermai** [comment]
The test would be applied to two groups of cell lines - those that are sensitive and those that are insensitive to a drug. The cell lines can be partitioned into two groups by setting an AC50 threshold of 8 uM for the CCLE data set. Then, for these two groups, you get distributions of either copy numbers or expression levels of a selected gene. No normalization is needed as gene expression is compared to gene expression and copy numbers are compared to copy numbers. The test then detects differences in the distribution and can tell us whether the sensitive cell lines have a significantly higher or lower expression of the selected gene or, when applied to copy numbers, significantly more or fewer copies of a gene are present.

**Comment by cpartl** [comment]
Ah, this makes much more sense now :-)
