### ISSUE TITLE
What is the idea behind the dynamic connection highlight focus?

### ISSUE THREAD

**Issue by fbrundu** [Caleydo/caleydo#1861]
Hi,
I have searched a lot but did not find a description about which is the threshold behind the "Dynamic Connection Highlight Focus" and how the color of the band is chosen. Can you explain?

Thanks

**Comment by alexsb** [comment]
You're right, that's missing from the documentation. We will add it.

It is described in a paper: 

http://data.caleydo.org/papers/2011_infovis_visbricks.pdf

And shown here in a video: 
http://caleydo.org/publications/2011_infovis_visbricks/

(note that this is an old precursory version of stratomex)

The idea is that you can emphasize either "strong" connections omitting the weak connections and cleaning up the clutter, or focusing on the weak connections, i.e., the outliers, and again reducing clutter.  This is mainly relevant if you have a lot of clusters.

I hope that helps.

**Comment by fbrundu** [comment]
Thank you for the quick answer!

May I ask you how the color of the band is chosen? Because sometimes I saw multiple bands with the same size but with different colors and I need to explain it. Thanks

## Edit

Reading the paper you passed me it is written: [Searching for outliers (therefore for smaller bands)] The wider the connection band is, the lighter it is drawn

But in my experience I found that it seems unrelated to band size. If needed I attach some images. Thanks

**Comment by alexsb** [comment]
By color you mean opacity? Could you send me a screenshot?

**Comment by fbrundu** [comment]
Yes opacity. I have 3 screenshots:

## Dynamic connection. Focus on the first and the second connection bands

![dynamic](https://cloud.githubusercontent.com/assets/697622/4253320/71cd67b8-3a9e-11e4-870c-ca2cf897d425.png)

## By selecting you can see that the first connection is weaker than the second if I got it correct

![dynamic1](https://cloud.githubusercontent.com/assets/697622/4253332/93349246-3a9e-11e4-9aa0-c1e7ca518f66.png)

![dynamic2](https://cloud.githubusercontent.com/assets/697622/4253334/969b378c-3a9e-11e4-8179-0e4d0c660c86.png)

Thanks

**Comment by alexsb** [comment]
OK, I see that problem. For the first image the top band is darker then the second band because of the larger overlap percentage wise. It looks like block 0 of data 2 is almost 100% in block 0 of data 1.

The third band (the black one) is clearly a bug. That should be much lighter. 

This is an old feature and nowadays I'd improve it by using e.g., a jaccard  index as the driving value for the opacity. 

The respective code is here: 

https://github.com/Caleydo/caleydo/blob/develop/org.caleydo.view.stratomex/src/org/caleydo/view/stratomex/column/BrickColumnSpacingRenderer.java#L670

Does it look very cluttered if you don't use the dynamic highlight feature? We will fix that with our next release, but this might take a while.

**Comment by fbrundu** [comment]
Ok, maybe I got it. One more question, the percentage considered is uni- or bi-directional? I mean, block 0 of data 2 is almost 100% in block 0 of data 1. Could be in the opposite direction? Opacity driven by a block of data 1 that is almost 100% in data 1? Or is it unidirectional?

Indeed, sometimes it can be very cluttered. However, I think I can just select the brick I want so I can also ignore the dynamic feature for my results.

Moreover, the band that is black is reproducible selecting the band when using the dynamic feature. When you release it, it is like this.

Thanks for your time

**Comment by alexsb** [comment]
Yes, the current algorithm takes the mathematical maximum of a similarity ratio: 

``` Java
float maxRatio = Math.max(subGroupMatch.getLeftSimilarityRatio(), subGroupMatch.getRightSimilarityRatio());
```

Thanks for the hint with the black band!

**Comment by fbrundu** [comment]
You're welcome!

Have a nice weekend :)
