### ISSUE TITLE
Caleydo application icon is not fully retina display compliant

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#1872]
The icon looks pixelated in the app switcher (Alt+Tab).

**Comment by sgratzl** [comment]
you need a mac for creating the icns file. 

following: https://developer.apple.com/library/mac/documentation/GraphicsAnimation/Conceptual/HighResolutionOSX/Optimizing/Optimizing.html

I created the iconset package: 

https://drive.google.com/open?id=0B7lah7E3BqlASWNsWWV4MjVmVlk&authuser=0

someone just have to enter:

`iconutil -c icns <iconset filename>`

**Comment by mstreit** [comment]
https://drive.google.com/file/d/0B7lah7E3BqlASWNsWWV4MjVmVlk/view?usp=sharing

**Comment by sgratzl** [comment]
> https://drive.google.com/file/d/0B7lah7E3BqlASWNsWWV4MjVmVlk/view?usp=sharing

this just links again to the iconset package not the icns file
