### ISSUE TITLE
Stratifications loaded from csv do not appear in LineUp

### ISSUE THREAD

**Issue by oneillkza** [Caleydo/caleydo#1878]
I'm currently trying to get some basic StratomeX plots to visualise some clusterings I've done on different data types from the same data set. I load up the raw data from a CSV file (identifying the columns as "SAMPLE" type), click through to the "Add Groupings" dialogue, open up my grouping CSV file (identifying rows as "SAMPLE" type), and load it up. It shows my two groupings in the dialogue, and loads everything in. But when I go to LineUp, it shows the data as being ungrouped.

This happens on multiple platforms. I'd be happy to send minimal example data to verify.

**Comment by sgratzl** [comment]
could you send the small example to: sgratzl@seas.harvard.edu, please

**Comment by sgratzl** [comment]
As far as I understood, you loaded groupings for the columns. Unfortunately, StratomeX is currently not smart enough to transpose tables by its own. A simple solution is to either transpose your data outside or within the import dialog (2nd page: Swap Rows and Columns), ensuring that the samples are the rows. And then load groupings for the rows.

**Comment by oneillkza** [comment]
Thanks, that does seem to fix it.
