### ISSUE TITLE
Problem with URL to download datasets and annotation

### ISSUE THREAD

**Issue by lpantano** [Caleydo/caleydo#1881]
Hi,

First, thanks and congratulation for this awesome tool.

I am trying to learn a little bit and play around, but I found a problem when I want to load any of the 3 example data set that you have included with the tool.

I am having different errors I think all related to the same problem (files that try to be downloaded are not in the expected URL)

The first error showed to me was that the /Users/lpantano/.caleydo_3.1/cache/caleydo/download/3.1/samples/ccle.cal is not compatible with this version of caleydo.

when I looked at this file:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://data.icg.tugraz.at/caleydo/download/3.1/samples/ccle.cal">here</a>.</p>
<hr>
<address>Apache Server at data.icg.tugraz.at Port 80</address>
</body></html>
```

I just addressed this downloading the file and uploading as a existing project, but then I had the same issue with `homo_sapiends.zip` and `wikipathways_homo_sapiens.zip`. When I downloaded manually both of them and extracted, then I got everything working.

I downloaded the last caleydo version from the web.

I just thought that may help, let me know if I can fix this from the user side.

thanks a lot in advance!

**Comment by ngehlenborg** [comment]
Thanks a lot @lpantano for pointing this out. We've been moving data to different URLs recently and we might have missed updating these.

@sgratzl and @mstreit - do you know what happened to these data at those URLs?

**Comment by sgratzl** [comment]
it is the same url but a different protocol: http -> https

http://stackoverflow.com/questions/1884230/urlconnection-doesnt-follow-redirect 

> Yes, it only applies to redirects to the same protocol. An HttpURLConnection won't automatically follow redirects to a different protocol, even if the redirect flag is set.

**Comment by GhostLyrics** [comment]
@sgratzl I was asked to revert the redirect to HTTPS for Caleydo data - That is everything belonging to Caleydo will not be redirected to HTTPS. Do you need that commit switching to HTTPS considering newer releases don't use said URL at all?

**Comment by sgratzl** [comment]
it is mainly about the next release. However, we have to decide first, which other url we are using. In the meanwhile it is better to have `https` in the code than `http`.

**Comment by sgratzl** [comment]
@lpantano try again and don't forget to remove the cache directory first.

**Comment by lpantano** [comment]
It worked! Thanks a lot!
