### ISSUE TITLE
rendering of views is broken

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#208]
os: windows
the rendering of views doesnt work unless window-focus is changed by e.g. set a focus to non-caleydo window and then set focus to caleydo window again.

**Comment by mstreit** [comment]
Not the rendering was broken. The picking was disabled. 
Reason: Picking mode was switched on after busy mode fade out in the renderBusyMode method finished. This does not work when the bucket is in the background and therefore is not rendered.
Solution: Turn on picking the same time when the SWITCH_OFF flag is set.
