### ISSUE TITLE
Store PickingID to picked object ID (hash map + reverse) mapping in picking manager

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#31]

**Comment by mstreit** [comment]
Remove view ID from picking ID.

Therefore picking IDs are completely encapsulated in the picking manager. 
Also the problem of overflowing picking IDs will be solved.

**Comment by alexsb** [comment]
Done :) - implemented double hashmaps for Picking ID and external ID, including several convenience functions.
