### ISSUE TITLE
Feature for unregistering EventListeners for ToolbarItems required

### ISSUE THREAD

**Issue by cpartl** [Caleydo/caleydo#320]
Since some toolbar items listen to events coming from the view (e.g. DepthSlider from radial layout), some method for unregistering the listeners has to be provided and called when the item is destroyed.

**Comment by sgratzl** [comment]
[puff] - added manual dispose of ToolbarManager when removing toolbar-groups (by puff)
- added dispose to DepthSlider for unregistering the listener (by partl)
