### ISSUE TITLE
Loading of external categorial mappings with group labels

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#507]
It would be extremely helpful if it was possible to load arbitrary groupings of samples and to be able to assign human-readable labels to the groups.

Example use case: I would like to load subtype information for breast cancer samples and compare this to the Firehose clustering.

**Comment by alexsb** [comment]
Fixed for manually specified groupings in TCGAImporter
Implemented generic parser, but doesn't have a GUI
