### ISSUE TITLE
color mapping for heatmaps

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#509]
The default color mapping should be centered on 0 (if data both negative and positive) and the range should be symmetric, ie. minimum color should be mapped to -max(abs(datavalues)) and the maximum color should be mapped to max(abs(datavalues)). Alternatively we could map to 75% of the min/max to reduce the influence of outliers.

If there are no negative or no positive values we should made to a sequential rather than a diverging color map to avoid confusion.

**Comment by ngehlenborg** [comment]
"If there are no negative or no positive values we should made to a sequential rather than a diverging color map to avoid confusion."

-->

If there are no negative or no positive values we should '''map''' to a sequential rather than a diverging color map to avoid confusion.

**Comment by alexsb** [comment]
Color mapping is set in the configurations, I will set this manually for now. 

Statistical optimal color mapping should be implemented in the future though.

**Comment by alexsb** [comment]
I think the current solution works for now?
