### ISSUE TITLE
Modify vertical alignment of bricks with more than 3 dimension groups

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#511]
Once I have opened more than 3 dimension group it is no longer possible to change the vertical alignment of the rightmost dimension group.

**Comment by alexsb** [comment]
Confirmed on linux, reason is the z-value of the bands relative to the drag handles.

Use more than 2 dimension groups and try to drag one of the two left dimension groups when bands connect the brick.
