### ISSUE TITLE
order of bricks for copy number data is non-deterministic

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#512]
The order of the bricks for the copy number data should be -2, -1, 0, +1, +2, but this is not always the case (see screenshot).

**Comment by ngehlenborg** [comment]
Unfortunately I can't add the screenshot (error in TRAC). It's here for now: http://dl.dropbox.com/u/1041348/Screen%20Shot%202011-11-14%20at%201.58.30%20PM.png

**Comment by alexsb** [comment]
Yes, needs to be checked for all kinds of bricks.

**Comment by alexsb** [comment]
Works for me - might be fixed with the removal of the center bricks
