### ISSUE TITLE
Improved mapping of expression data on Pathway

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#525]
When ticket 510 is done we will have a mapping of the average expression value on the pathways. This leaves two issues:

1) The pathway textures in the small multiples are likely very small, and the mapping is hard to see.

For 1) one solution would be to enlarge the mapping disproportionally so far that it stands out even in the thumbnail version. As this might introduce a lot of occlusion when we do that for all nodes, we thought about what a user is interested in. As it's mainly the change between the multiples of the pathways, we can analyze the differences and enlarge only those that differ significantly. Therby the user would be pointed to obvious differences even in the small multiples.

**Comment by ngehlenborg** [comment]
Yes, the main thing that biologists will be interested in are differences between the groups that they are mapping on the pathway.

So we could do what you suggested, i.e. scale the markers in the thumbnail view relative to the size of the mean/median expression value or relative to the inverse of the variance. The latter is probably the better option.

**Comment by alexsb** [comment]
Deviation issues previously part of this ticket solved
