### ISSUE TITLE
Redesign of "Arch"

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#536]
The Arch should be modified so that it

  a. remains static on top of the window
  a. has a constant height across all dimension groups
  a. so that bricks can be moved under it (i.e the cluster bricks are moved without the center brick)
  a. the bricks should adapt their content on the available height.

**Comment by ngehlenborg** [comment]
e) For aesthetic reasons it would be nice to have a couple of pixels of space above the center bricks.

Regarding c): Is this really desired or necessary? Under which circumstances would this be applied? I think it would make sense if we could zoom into the VisBricks view, but as far as I know this is not possible at this point.

**Comment by alexsb** [comment]
@e - agree

@c - what I mean here is the vertical dragging of dimension groups. The thing is, that if you can drag them around you can compare two bricks next to each other which are otherwise on opposite ends. Also, for a more general case, where we don't scale the height of the bricks according to the amount of the data, it might be necessary to see them all.

**Comment by ngehlenborg** [comment]
@c - How about adding support for manual reordering of the bricks instead? That is something that I would find quite useful, e.g. to resolve cases where there is edge crossing that could be easily resolved.

**Comment by alexsb** [comment]
a) fixed
b) fixed

**Comment by alexsb** [comment]
other issues have a separate ticket now
