### ISSUE TITLE
Integrate BioCarta abstract

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#54]
Monika Schuller mentioned that this piece of information that is provided by the BioCarta pathway authors contains helpful and important information. We should make this info available to the user. A proper way of presentation needs to be found.

**Comment by alexsb** [comment]
Should be solved by showing the pathway info page in browser?

Or write it to an info area.

**Comment by mstreit** [comment]
Due to the loading of the pathway source webpage of KEGG and BioCarta this request is solved.
