### ISSUE TITLE
Order of data containers in visbricks node should be the same as order in visbricks

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#540]
Is there some ordering in the view node of the data container at the moment? 

Most intuitive would be if we could make the ordering the same as in visbricks (or more generally the view).

**Comment by cpartl** [comment]
Yes, the ordering of the data containers in the visbrick node is the same as in the data nodes.

**Comment by alexsb** [comment]
The current order is a hybrid of time and data domain relationship (those of same data domain are placed next to each other irrespective of time they were added, the others are in the order of when they were added)

As discussed this should be one of two things:
1. the order of the perspectives in the data container (globally)
2. the order used in visbricks

Christian, please chose whichever one you prefer ;) - both can be argued for.
