### ISSUE TITLE
it is impossible to deselect a brick or band in StratomeX without selecting something else

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#553]
The selection should be cleared when the user clicks on the background.

**Comment by alexsb** [comment]
This is a conceptional problem we have with the way we handle clicks of a mouse (save a state which can be only read once)

**Comment by alexsb** [comment]
We should at least listen to the clear selection command however.

**Comment by cpartl** [comment]
listens to this command as side-effect of changes for multiple brick selections (baf6b2) -> fixed
