### ISSUE TITLE
Cannot change RCP workspace location in webstart version

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#571]
changeWorkspaceLocation causes an exception.
this makes problems for the way how we handle project save/restore.

solution:
the home folder in the jnlp file was set to .caleydo_2.0.X instead of only .caleydo_2.0

**Comment by alexsb** [comment]
marc, how do we reproduce this? don't get the problem

**Comment by mstreit** [comment]
Replying to [comment:2 lex1]:

> marc, how do we reproduce this? don't get the problem

the problem only occurs in the webstart version.
