### ISSUE TITLE
change drag-and-drop grab point for bricks

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#591]
The drag-and-drop grab point is currently the content area of the brick but in most windowing systems windows are moved by grabbing their title bar. We check if we can change the drag-and-drop behavior of bricks to follow this established behavior.

**Comment by cpartl** [comment]
For header bricks this is already implemented that way. What if there is no title bar? (e.g., pathways or km plots)

**Comment by ngehlenborg** [comment]
If there is no title bar we can use the frame.
