### ISSUE TITLE
opening the histogram view requires choice of data set

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#592]
The dialog presented when opening the histogram view (and some others) still asks users to select the data set _and_ stratification for which the histogram should be opened. At least the question for the stratification needs to be removed because this is very confusing.

**Comment by alexsb** [comment]
Well, that's kind-of necessary. We could use default stratifications.

**Comment by alexsb** [comment]
I checked, default stratifications are chosen anyway. I reccomend we close this bug!
