### ISSUE TITLE
missing bands when loading different gene stratifications for the same patient stratification

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#593]
No bands are shown when two different gene stratifications are selected for the same patient stratification.

Only two stratifications were loaded when this problem occured. 

In the current sample project this problem cannot be reproduced due to the fact that there is only one gene stratification available.

**Comment by alexsb** [comment]
I can't reproduce this, Nils please explain

**Comment by alexsb** [comment]
Not relevant as long as we only have one dimension stratification (due to not-implemented clustering).
