### ISSUE TITLE
add "open project" menu item to load an existing cal file (and replace current)

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#609]
Currently it is not possible to switch to another cal file, i.e. to another project from a running caleydo instance.

An "open project" menu item should be added. If the user has a project open, he should be asked if he wants to save its current state or discard it. Then the new project will be loaded.

**Comment by alexsb** [comment]
Not sure whether we want that - currently restarting is the default

**Comment by mstreit** [comment]
This can now be implemented using the new workbench restart command.
