### ISSUE TITLE
Remove data from org.caleydo.data

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#625]
Genetic mapping data should go to org.caleydo.datadomain.genetic
Resources should go to resources plug-in
Data should be removed from the repository in general

**Comment by sgratzl** [comment]
start with moving sample project to http://data.icg.tugraz.at/caleydo/download/3.0/samples/

**Comment by sgratzl** [comment]
> Genetic mapping data should go to org.caleydo.datadomain.genetic

via #963 the data can be removed

> Resources should go to resources plug-in

modern views have their resources by them, the question is where to put shared resources and a convinced way for specifying the resource loader to load view / plugin specific files

**Comment by sgratzl** [comment]
regarding resource location and resource loaders: 

The texture manager now supports URL resources that means everything except the icons referenced in the `Manifest.MF` files can be put in the classpath of the plugins. So for textures, we don't need to use the ResourceLoader anymore and can pass URL objects across plugins without any problem. e.g. they can be used as an alternative to the `EIconTextures`

crossword, bicluster and lineup are already converted.
