### ISSUE TITLE
Pathway color mapping broken in small multiples

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#637]
The color coding in the small multiples (sample project) is only grey, only if the pathway is enlarged is the mapping visible.

**Comment by alexsb** [comment]
Occurs again in my latest version.

**Comment by alexsb** [comment]
Example:

![on-node](https://f.cloud.github.com/assets/2039375/986333/d9236494-08d6-11e3-8518-81c1ad8aabd4.png)

**Comment by sgratzl** [comment]
I think it is because of GLPathwayAugmentationRenderer line 555 -> 

``` java
if (pixelGLConverter.getPixelWidthForGLWidth(glPathwayView.getViewFrustum().getWidth()) < 300
                        || pixelGLConverter.getPixelHeightForGLHeight(glPathwayView.getViewFrustum().getHeight()) < 300) {
                    return;
                }
```

which abort the rect rendering as the size is about 128x120

**Comment by mstreit** [comment]
The if statement was introduced to turn off the on-node mapping for small pathways (<300px) in entourage. However, this also turns it off in StratomeX.
@cpartl Is there a general way to handle this?

**Comment by mstreit** [comment]
@alexsb and @cpartl: Maybe we can add a switch to the pathway bricks so that the layout mechanism in Entourage can turn the mapping off if the pathways are smaller than a certain threshold. Would there be any side effects?

**Comment by sgratzl** [comment]
the problem is how to transport that information from Entourage to the GLPathway view as in between is the multi form renderer abstraction

you could do some hacks of course

**Comment by alexsb** [comment]
A clean solution would be to use a detail mode flag. StartomeX could use medium detail mode for the small multiples, Entourage low.
