### ISSUE TITLE
adding data container to StratomeX view from DVI misbehaving

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#656]
When adding the first data container to the StratomeX view from the DVI neither the edge is drawn between the data type matrix and the view container, nor the marker in the StratomeX view box. Only after switching to the StratomeX view (possibly other views work, too) and back to the DVI the edge and marker appear. Everything works fine after this.

**Comment by alexsb** [comment]
Most likely a symptom of incorrect activation on MAC
