### ISSUE TITLE
Switching to detail mode and back should preserve setup of columns

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#664]

**Comment by ngehlenborg** [comment]
Moved to 3.0.

**Comment by alexsb** [comment]
That requires some work which will be obsolete with StratomeX 2.0. Therefore we didn't want to do that. It's definitely desirable though.

**Comment by ngehlenborg** [comment]
I tried this with three methylation columns from the TCGA test data set and after opening one brick in detail mode and closing it again, only two columns are in the view and one is in the "leg". Wasn't this supposed to bring all three columns back?

**Comment by cpartl** [comment]
Yes, that is what should be happening. I just tried it again with 3 methylation columns and it works...

**Comment by cpartl** [comment]
Hm, my commit somehow got "lost". Maybe someone discarded this change? :-(
