### ISSUE TITLE
Use external browsers and remove internal browser

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#666]
Also add a menu item to the general tool-bar on whether selections should be triggered or not.

**Comment by mstreit** [comment]
Preference page
General toolbar switch

**Comment by ngehlenborg** [comment]
Isn't #666 about web browsers and #912 about genome browsers?

**Comment by alexsb** [comment]
Yes, but both is an URL isn't it? Or do you want to start the application on a local machine?

**Comment by ngehlenborg** [comment]
Yes, both are URLs. It wasn't obvious to me that this is the connection between the two tickets.

**Comment by mstreit** [comment]
users should be able to define and change the search string via the prefs page
we should store the tuples (id category, search string) in the caleydo prefs file.
we need to add default search strings for genes.

**Comment by mstreit** [comment]
open issue: multi mappings -> we can load the first resolved id

**Comment by mstreit** [comment]
Sam, can you please take care of it as well?

**Comment by sgratzl** [comment]
> Sam, can you please take care of it as well?

is this ticket about moving internal web browser to external or about the search engines for genes

**Comment by mstreit** [comment]
Both. The primary purpose of the web browser is to get details on the genes. However, creating external links for other entities would make sense as well (e.g., proteins). So the user needs a way to specify the mapping between ID categories and the external search query where we then can just append the selected ID. 

For instance, if the user selects a heat map row, he should be able to trigger the external web browser by using the context menu. 
For now, I suggest to query genes on http://www.genecards.org/. Any other opinions on that?

**Comment by sgratzl** [comment]
then this are two different tickets from my point of view, one for the external / internal stuff and one for the gene search

**Comment by mstreit** [comment]
i agree

**Comment by sgratzl** [comment]
splitted in #1221 and #1222 to avoid confusion
