### ISSUE TITLE
Calculate and show statistics for brick-relationships.

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#691]
Statistics:
- Size of a ribbon
- deviations from expected correlation in ribbons.

We need to calculate the expected correlation value of two bricks and its deviation from the expected correlation. 
- This should be shown numerically (tool tip)
- This should be visualized (e.g., ribbon turns red for higher then expected correlation, blue for lower then expected)

**Comment by cpartl** [comment]
how to calculate this? should this always be shown?

**Comment by cpartl** [comment]
And how to show that if there is no connection between bricks?

**Comment by alexsb** [comment]
As a first step, I'd say we put this in tool tips for the ribbons. Later we might want to visually encode this somehow or at least show it for all ribbons of a brick at the same time. 

Also, as a first step I'd show the number of elements of a sub-ribbon, plus the percentages. 

Next you'll have to look for some meaningful statistic. I'm sure that there is statistics that can tell you that two subsets a and b of n respectively m should share x% of their elements if chose at random

**Comment by ngehlenborg** [comment]
This is sufficient for 3.0 (we can deal with the statistics for "expected" overlap in 3.1 or 3.2):

![image03](https://f.cloud.github.com/assets/1216518/668980/65f820c0-d822-11e2-97a4-8466f54f3e41.jpg)

I agree that we should only show this on hover - tooltip is ok even though integration into the vis would be desirable at some point (e.g. 3.1 or 3.2 when we deal with expected overlap vs. actual overlap).
