### ISSUE TITLE
Heat Map Texture renderer fails for large number of dimensions

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#716]
It is only intelligent in one direction, consequently fails if more than 1500 dimensions are displayed - shows only a yellow texture

**Comment by mstreit** [comment]
@alexsb and @ngehlenborg 
Do we plan to load all genes for release 3.0? That would also mean to reopen #802.

**Comment by ngehlenborg** [comment]
It would be very useful - at least to have the genes in the background for pathway maps, i think for the cluster heatmaps its not going to be very interesting to have all 20K genes.

**Comment by alexsb** [comment]
This was moved to 3.1 See #1216 - which is a duplicate of #802 
This bug is independent of that, however. CCLE, for example, contains more than 1500.

**Comment by mstreit** [comment]
![screenshot_20130621_132229](https://f.cloud.github.com/assets/4129755/686775/3f31e828-da65-11e2-873a-122dc5c332b0.png)

**Comment by mstreit** [comment]
@alexsb Please test with CCLE and close ticket if it works.

**Comment by alexsb** [comment]
Works, not very fast, but works ;)
