### ISSUE TITLE
Mac: Register caleydo file to start with caleydo in installations

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#726]

**Comment by sgratzl** [comment]
in line with #1143 or by fixing the jnlp

**Comment by sgratzl** [comment]
see also http://forum.lazarus.freepascal.org/index.php?topic=15429.0

-> If I understood it right, we would just need to hack the Info.plist within the app folder

**Comment by sgratzl** [comment]
or to be more precise: 

https://bugs.eclipse.org/bugs/show_bug.cgi?id=201154

and http://help.eclipse.org/juno/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Fproduct_open_file.htm

**Comment by sgratzl** [comment]
@ngehlenborg could you please test the latest build, it worked on my mac.

see http://dev.caleydo.org/jenkins/job/caleydo.super/

**Comment by ngehlenborg** [comment]
This works for me, too. Very nice, thank you!
