### ISSUE TITLE
Open Firehose report in browser in TCGA projects

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#739]
We need to think about a mechanism how to do this.

**Comment by alexsb** [comment]
What's the goal of this? How deep should the integration be? Should it just point at the report? This could be realized using an "meta-info" field in the dataset description containing a dataset url - which would make a lot of sense.

**Comment by ngehlenborg** [comment]
A simple link is sufficient.

**Comment by sgratzl** [comment]
the question is how to trigger that action? as we only want to use the external browser, we can't open the view by default

**Comment by alexsb** [comment]
I'd say it should just be a link to the report which must be manually triggered. The question is where do we put the link? In the dataset info view is probably the best place, although it's not dataset specific but project specific.

**Comment by sgratzl** [comment]
for #1156 metadata are needed, therefore I added them: ProjectMetaData including the version as well as custom meta data fields

All of them are rendered within the DataSet Info view, if the meta data aren't trivial
