### ISSUE TITLE
Discuss and introduce build ID for every export

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#755]
...and document what works for which build

Our version numbers are too rough for that

**Comment by alexsb** [comment]
Agreed procedure: when building we create a version.txt file using

svn info https://svn.icg.tugraz.at/svn/org.caleydo/trunk/ | grep Revision

The content of  version.txt is displayed in the about diaolg

**Comment by alexsb** [comment]
This should be in line with the planned build process (#1126)

**Comment by sgratzl** [comment]
version convention: 
 bundles: <major>.<minor>.<patch>.<qualifier>
 maven: <major>.<minor>.<patch>-<qualifier>

qualifier: locally .qualifier / -SNAPSHOT but the build automatically converts in the the build timestamp, e.g. 20130814-2348
