### ISSUE TITLE
Dynamic connection highlight slider is gone in StratomeX view toolbar

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#757]

**Comment by alexsb** [comment]
Platform specific for
- Unity/ATI

No problem:
- KDE/NVidida
- Windows/ATI
- Windows/NVidia

Unknown: 
- Mac

**Comment by alexsb** [comment]
We should confirm this for mac

**Comment by sgratzl** [comment]
I think we should avoid sliders and more complex widgets than buttons within the view toolbar. As it just don't work all the time. 

depending on the view type, I would suggest a dedicated line / area within the view for the main userinferface or someting like a popup toolbar as it will be done currently in the bicluster visualization
