### ISSUE TITLE
Screenshot feature does not work under Windows

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#779]
GL areas are blank

**Comment by alexsb** [comment]
Fix or remove

**Comment by sgratzl** [comment]
It works on my system (Win7 64-Bit NVidea)

![screenshot_20130425_095321](https://f.cloud.github.com/assets/4129778/424114/8ad6e180-ad7d-11e2-9cc3-1378f2f09ece.png)

**Comment by sgratzl** [comment]
-> @cpartl can you verify this on your windows systems and if it works close the ticket please

**Comment by mstreit** [comment]
Does not work for me on Win 64-bit with ATI card.

**Comment by sgratzl** [comment]
> Does not work for me on Win 64-bit with ATI card.

via VM wrapper or direct

**Comment by cpartl** [comment]
Implemented some workaround for windows systems. It requires awt not to be in headless mode, therefore I disabled headless mode for win systems now. There is still a strange problem wit this workaround: You have to make the screenshot twice to get what you want.

**Comment by cpartl** [comment]
removed this feature for win systems as discussed with @alexsb We should implement a more useful screenshot feature that only contains the canvas of a view.
