### ISSUE TITLE
Update to Eclipse 4.2 (Juno)

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#787]

**Comment by sgratzl** [comment]
problems: 
- internally eclipse moved to e4 (intro e.g. http://www.vogella.com/articles/EclipseRCP/article.html), which is a total new paradigm for programming eclipse, ... it is based on EMF Models for defining the views, perspectives, windows, and the whole application. 
- biggest problems is that the place where the workbench spezification is stored, is not longer valid, i.e. it doesn't exist, see also: https://bugs.eclipse.org/bugs/show_bug.cgi?id=378811
- which means that the perspectives/... stored in saved projects can't get restored in eclipse juno

**Comment by sgratzl** [comment]
r5396

-> persist and restore workbench.xmi instead of workbench.xml
