### ISSUE TITLE
Scrollbars in DVI and pathways broken on MacOS X Lion

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#789]
Sometime KEGG pathways don’t fit the screen and I tried to use the scrolls but they don’t work. To replicate this problem you can use Hematopoietic cell lineage (KEGG). 

scroll bars are present but they don't work. The vertical one is scrolled to the top but the figure is stuck to the bottom.

**Comment by ngehlenborg** [comment]
On a screen resolution of 1024x768 (projectors ...) this bug is a blocker for TCGA tumors with large number of data types.

The same problem described for pathways exists for the DVI. The view does not move with the scrollbars (view is stuck in the bottom left corner) and mouse events are offset relative to the amount of scrollbar shift.

**Comment by sgratzl** [comment]
jogl forum post: http://forum.jogamp.org/SWT-ScrolledComposite-not-working-under-Mac-Mountain-Lion-td4027271.html

**Comment by mstreit** [comment]
Sam, could we use the new scrollbars from TourGuide instead of the native SWT scrolling to circumvent the problem?

**Comment by ngehlenborg** [comment]
Could we do the same for the DVI? The scrollbars in the Tour Guide seem to work really well.

**Comment by sgratzl** [comment]
Replying to [comment:6 gehlenborg]:

> Could we do the same for the DVI? The scrollbars in the Tour Guide seem to work really well.
> the scrollbars in tour guide are implemented by hand, e.g. one ElementLayout will be scrollable, within DVI the whole GLCanvas is scrollable. 

I don't know the internals of DVI to give a profound answer, whether and how easy this would be possible.

**Comment by cpartl** [comment]
The DVI as a whole does not use any layouts (just internally for the nodes). Same thing with the pathway view. Btw: Does this issue also occur for enRoute? It also uses the SWT ScrolledComposite. Adapting all these views to use the scrollbars implemented by hand sound like some work. But I am just speculating, as I do not know how the scrollbars work. Also, there could be side-effects for remote rendering.

**Comment by alexsb** [comment]
@ngehlenborg - is this still an issue

**Comment by ngehlenborg** [comment]
Yes, in the DVI I have the same issues as in the past. The within-brick pathways in StratomeX do scroll.

**Comment by mstreit** [comment]
JOGL bug ticket has not been addressed yet
https://jogamp.org/bugzilla/show_bug.cgi?id=647

**Comment by cpartl** [comment]
@ngehlenborg Can you check whether this problem still occurs? If so, please try to uncomment the code in AGLView.onScrolled() and hope for the best ;-)

**Comment by ngehlenborg** [comment]
@cpartl Canvas is scrolling but you need to update the mouse position accordingly. Right now clicks and hovering are offset.

**Comment by cpartl** [comment]
@ngehlenborg This is actually weird, as the picking should be affected by this change. However, I've committed an attempt to solve the offset issue. Please try. As I cannot test it on my machine, I don't know the direction the offset. You maybe have to play with the signs of the translate in PickingManager line 396. Let's hope for the best again ;-)

**Comment by cpartl** [comment]
@sgratzl The basic idea of the workaround is the following: Detect whenever there is some scrolling and translate the view accordingly in GL. A ViewScrollEvent is sent whenever there is some scrolling going on, see MinimumSizeComposite. This event is handled in AGLView.onScrolled, which sets the members scrollX and scrollY, which again are used for view translation in AGLView.display. 

I can't explain why that is, but for some reason there is an offset in the picking and the actual display on mac (there is no offset on windows when enabling the translation). Therefore there is some manual counter-translation in the PickingManager line 393. (horrible hack) This solves the offset issue in x direction, but not in y direction...

**Comment by sgratzl** [comment]
@ngehlenborg I'm commiting a new bugfix, please test it. It worked on my mac

**Comment by mstreit** [comment]
@ngehlenborg Please test and report.

**Comment by ngehlenborg** [comment]
Vertical: It works when I scroll to the bottom. It does not work when I don't scroll but the view is larger than the window.

Horizontal: It works when I don't scroll, even when the view is wider than the window. It does not work when I scroll to the right.

**Comment by sgratzl** [comment]
@ngehlenborg once more, please
- if it doesn't work, screenshots + whether its the rendering part or the picking one

**Comment by ngehlenborg** [comment]
[7/9/13 12:02:27 PM] Nils Gehlenborg: what did you do in the end to make it happen?
[7/9/13 1:10:15 PM] Samuel Gratzl: several things:
[7/9/13 1:12:47 PM] Samuel Gratzl: 1. you need an non-shifted picking, as the mouse coordinates are already correctly shifted by SWT
2. you have to keep in mind, that in our coordinate system the lower left corner is 0,0 -> relevant for vertical scrolling
3. use the client size instead of the size of the parent to avoid taking the scrollbars into account
4. however, it is not perfect. I had some rare cases, where the DVI was too far below. I don't know why, it seems to be some problems with the SWT, JOGL, stuff
