### ISSUE TITLE
Key listener issue under Linux

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#810]
The key listener only works when the view is active. However, sometimes it is necessary to inactivate the view (by clicking on another one) and then active it again in order to make the key listener work.

**Comment by alexsb** [comment]
Specify how to reproduce. Which view is affected?

**Comment by mstreit** [comment]
Seems to work in TourGuide. 
I guess I had the problem with the heatmap fisheye inside the StratomeX detail mode. But as this is not possible anymore, I close this issue until the problem reoccurs.
