### ISSUE TITLE
Batch add mode for DC in DVI

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#818]
In the quality control use case we usually want to compare all clustering results with the same number of clusters over time. In order to save the user much time, we should have a special mode, where all data containers can be added to StratomeX in a batch manner.

**Comment by sgratzl** [comment]
@mstreit 
is this still relevant, as we have LineUp know. This would be select all database, filter on your target cluster + double click on every row

**Comment by mstreit** [comment]
Yes, this is much more effective now compared to the workflow in DVI.
