### ISSUE TITLE
Adapt QC cal generator for internal usage on Broad server

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#819]
directory structure on server:
analyses/<rundate>00/<tumor>/<rundate>/*.tar.gz
where <rundate> = yyyymmdd
/xchip/gdac_data/for_submission/  contains the archives submitted to DCC either
- all in one directory (pre-submission)
  or
- partitioned into tumor types (post-submission)

**Comment by mstreit** [comment]
@ngehlenborg Is that still relevant or can we close the issue (and milestone)?

**Comment by ngehlenborg** [comment]
Wontfix.
