### ISSUE TITLE
Nodes in pathways sometimes indicate no mapping although there is one

### ISSUE THREAD

**Issue by cpartl** [Caleydo/caleydo#823]
See for example node Shc in Glioma pathway with all genes loaded -> The exp data can be seen in enRoute

**Comment by mstreit** [comment]
This is a multi-mapping issue. In the pathway view we currently can only color code one of the mappings. For now, we take the first valid data value and map it. On the long run we need to think of a better solution.

**Comment by mstreit** [comment]
We need a mouse over on pathway nodes.

**Comment by alexsb** [comment]
for mrna seq there is one of four genes that has a mapping, so that should be shown.

**Comment by cpartl** [comment]
@alexsb I can not reproduce this. It also looks good from the code side... What project did you load? I tried it with both tcga projects, for the sampled one there is no mapping for mrna seq (and also no mapping in enroute), and the large one has full mappings for Shc...

**Comment by alexsb** [comment]
Can't reproduce either. I assume I had an other dataset selected.
