### ISSUE TITLE
View resize does not always result in a reshape call

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#829]
The view's content is not updated sometimes.
Seems to be a general problem under Linux.

**Comment by mstreit** [comment]
I still have the issue when a view (for instance StratomeX) is in full screen mode after startup - it's just gray. I need to leave the fullscreen mode to see the view's content.

**Comment by mstreit** [comment]
Seems to be a driver issue with ATI.

**Comment by alexsb** [comment]
Full-screen means hiding all other views and window titles? Only in full-screen?

**Comment by mstreit** [comment]
Only the StratomeX render area is grey. Rest is fine. If I force the view to get a reshape, by for instance changing it's size, then the content appears. This only happens right after the startup.

**Comment by mstreit** [comment]
Could be related to that issue, which has already been fixed in the JOGL HEAD version:
https://jogamp.org/bugzilla/show_bug.cgi?id=673
However, the new release of JOGL is not available yet.
As only I have the problem, I will move the ticket to post 3.0 release.

**Comment by alexsb** [comment]
Is this still an issue?

**Comment by mstreit** [comment]
Since I switched to KDE it's gone. It seems to be related to Unity.
