### ISSUE TITLE
Scale StratomeX columns proportionally

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#834]
In order to get a better feeling for the number of (overlapping) items across data sets it would be extremely useful to be able to switch between two types of column scaling:

(1) all columns are scaled to 100% of the window height (currently implemented)
(2) columns are scaled proportionally to the number of items in the column with the largest number of item

**Comment by alexsb** [comment]
How would you like to switch that? Button/Check-box in the tool bar?
