### ISSUE TITLE
mix data types in a single column to create mosaic plots

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#835]
See e.g. Verhaak paper and all the main TCGA papers.

**Comment by alexsb** [comment]
Is that something we want to do?
I feel like that works only for the very small set of selected genes they have in their papers and I think this is a completely different visualization approach - it should probably be a separate view

What you could do right now is to use the same stratification for all datasets.

**Comment by alexsb** [comment]
Re-defined the problem in #1140
