### ISSUE TITLE
Integrate CNV clustering and other pipelines

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#836]
-  New Pipelines:
  
  Aggregate_Gene_Status
  CopyNumber_Clustering_CNMF
  CopyNumber_Gistic2_Postprocess_Focal
  Correlate_Clinical_vs_Methylation
  Correlate_Clinical_vs_RPPA
  Correlate_Clinical_vs_mRNAseq
  Correlate_Clinical_vs_miRseq

**Comment by ngehlenborg** [comment]
Cnv clustering is probably copy and paste of existing clustering algorithms.

The correlation pipeline results are only useful as filters or potentially as rankings.

I don't know what the gene aggregation pipeline is doing.
