### ISSUE TITLE
Replace self-made tabular view with NatTable

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#838]
http://www.eclipse.org/nattable/

**Comment by sgratzl** [comment]
features that we want:
- selection (cell, row, column) with corresponding selection events
- groupings? (as we have a table perspective we could show the groups)
- filters?
- types: 
  - float
  - integer
  - categorical -> show colors?

open issues: 
- which values should be shown: normalized, raw, log, log10, or selection based (e.g. combo box or menu within the view toolbar)
- transposed -> rows can be categorical -> no filters possible

**Comment by sgratzl** [comment]
r6463 continue with marcs work, 

simple tables can be shown, advanced features are missing

**Comment by mstreit** [comment]
Let's leave out filters for now.
Combo box for choosing value types sounds good.

**Comment by sgratzl** [comment]
r6475

view now part of the dvi + switching data representation (raw - normalized)

**Comment by sgratzl** [comment]
r6476

selection (both directions) + increase / decrase formatting precision

want more?

**Comment by mstreit** [comment]
I guess that's enough for now.

An exception occurs when selecting a group in the table view:
!ENTRY org.eclipse.ui 4 0 2013-04-11 16:43:29.672
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.ArrayList.elementData(ArrayList.java:371)
    at java.util.ArrayList.get(ArrayList.java:384)
    at org.caleydo.core.data.virtualarray.VirtualArray.get(VirtualArray.java:136)
    at org.caleydo.view.table.DataProvider.getRowObject(DataProvider.java:94)
    at org.caleydo.view.table.TableView.select(TableView.java:152)
    at org.caleydo.view.table.TableView.handleLayerEvent(TableView.java:139)

**Comment by sgratzl** [comment]
regarding the selection problem, 

I have no problem with it

**Comment by mstreit** [comment]
When the table is in "show only selected items" mode, then the selection in the table is not triggered. I guess this is on purpose.

**Comment by sgratzl** [comment]
the table works for me, if there any remaining problems create a new issue
