### ISSUE TITLE
Toolbars behave weird in Juno

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#857]
In pathway view for example, they only appear after deactivating and re-activating the view.

Tool-bars should be brought back to the standard implementation.

**Comment by mstreit** [comment]
Also observed on Ubuntu Unity 64-bit

**Comment by mstreit** [comment]
Fixed after toolbar mechanism refactoring.
Was probably caused by dynamic toolbar add/remove mechanism.
