### ISSUE TITLE
Views are not unregistered when closed

### ISSUE THREAD

**Issue by cpartl** [Caleydo/caleydo#863]
When closing a view it does not get unregistered and properly destroyed. This might be due to the switch to SWT canvases, as the method AGLView.dispose() does not seem to be called. We maybe have to investigate whether the deletion of display lists to when closing views is actually necessary right now.

**Comment by sgratzl** [comment]
r5553

notes: 
 glcanvas of the swt implementation uses the {{{dispose}}} method to check if the widget was disposed. 

 Unfortunately if the element is not the root widget only {{{release}}} will be called. Therefore a dispose listener was registered and an explizit dispose is performed.
