### ISSUE TITLE
New views opened by the user via the menu show up in the right side pane instead of the main area

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#864]
This is probably connected to the tour guide perspective definition.
In order to make this happen, tour guide does not even need to be present as a view in the current workbench window arrangement.

**Comment by sgratzl** [comment]
r5551

set via a dedicated extension the targeted positions of the view, instead of the "last" one

**Comment by mstreit** [comment]
Works.

**Comment by sgratzl** [comment]
duplicate to #1133
