### ISSUE TITLE
selection info doesn't update when header brick is selected

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#870]
When a header brick is selected, the selection info should show all items in the selected column. Currently clicking on a header brick has no effect at all on the selection info view.

**Comment by alexsb** [comment]
Is this really something we want? That's essentially selecting all samples for many cases. What would be the point?

**Comment by ngehlenborg** [comment]
Here are a couple of scenarios in which this might be useful:
- the resulting band selection would help to see how many of the samples in the selected column are in the other columns
- if one could copy the identifiers from the selection info one could copy all samples ids in a column
- it would be a way (the only one right now) to see how many samples there are in a given data matrix (but this would be better handled with some stats views)

**Comment by alexsb** [comment]
- band selections - that would only help if we have more than two columns, i.e., 

A - B - C and by selecting all in A we would see the overlap of A and C. The overlap for A and B is obvious anyways. 
- yes, but that could equally be possible for the stratification itself 
- yes, this should be addressed trough #772

**Comment by alexsb** [comment]
@ngehlenborg - I think all of the points you mention are "hacks" to other, unrelated problems, so maybe we should address them differently.

**Comment by ngehlenborg** [comment]
The issues and use cases described here have been addressed.
