### ISSUE TITLE
Set Name / Rename dialog for bricks incorrectly shows "brick" as label

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#871]
There is also a layout problem with the text field in the dialog on my Mac (no bezel, not padding around text, only a wide as initial text.

**Comment by ngehlenborg** [comment]
The label is only incorrect the first time, i.e. when the brick label is the default label.

**Comment by sgratzl** [comment]
r5592 (21), r5591 - better rename dialog
