### ISSUE TITLE
Pathway augmentations vary in 1 pxl in width and height depending on the aspect ratio of the current window

### ISSUE THREAD

**Issue by dkalkofen** [Caleydo/caleydo#874]

**Comment by dkalkofen** [comment]
This ticket was 'StdDevBar is offset depending on the current display resolution'. However, the problem is more fundamental addressing all renderings on top a pathway map. All pathway augmentations vary in 1 pxl in width and height depending on the aspect ratio of the current window.

**Comment by alexsb** [comment]
Fixed as good as it gets
