### ISSUE TITLE
in labels data type should come after the name of stratification

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#878]
Instead of "mRNA - 4 Hierchical Clustering/K-Means 5" it should say "4 Hierchical Clustering/K-Means 5 mRNA". The data type can be derived from the brick color or from the data set info view.

**Comment by alexsb** [comment]
I disagree. I assume that in most cases people don't have multiple stratifications of the same dataset. The number of clusters is also obvious from the cluster bricks, which leaves only the type of the clustering algorithm as relevant, but that's visible anyways. If you have the DVI hidden you don't see the color of the dataset.

**Comment by ngehlenborg** [comment]
I think this has since been addressed with tool tips. If not, we need a ticket for tool tips with labels of the column headers.

**Comment by alexsb** [comment]
Yes, this works with tool-tips. Closing
