### ISSUE TITLE
Think of using faster map/list implementations for native types

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#888]
see e.g http://b010.blogspot.co.at/2009/05/speed-comparison-of-1-javas-built-in.html

http://trove.starlight-systems.com/

or 

http://acs.lbl.gov/software/colt/

or

...

**Comment by alexsb** [comment]
I would follow the mantra of optimize performance only after profiling for bottlenecks. If it turns out to be a bottleneck then yes, we should do it. Adding additional libraries has disadvantages too.

**Comment by sgratzl** [comment]
the idea was mainly to use those implementation for things like the internal structure of tables and the idmappingmanager. 

But I agree as it works up to now, we don't need to change it

wontifx
