### ISSUE TITLE
Scoring method that is based on absolute number of shared entities

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#890]
Currently, with Jaccard, small clusters result in a high score for mutation data. When scoring all clusters in a column this obscures the more interesting correspondences.

**Comment by mstreit** [comment]
Should be solved by query based filtering of groups

**Comment by sgratzl** [comment]
Replying to [comment:2 mstreit]:

> Should be solved by query based filtering of groups
> based on the group size -> e.g. an extra possible column: size with a filter option
