### ISSUE TITLE
Highlight contained scored groups and stratifications if user selects a ranking row

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#894]

**Comment by sgratzl** [comment]
done in r5682

{{{TourGuideRenderStyle.STRATOMEX_*}}} to specify colors

**Comment by mstreit** [comment]
If a concrete group is suggested in the ranking result, only the group should be highlighted using a halo.

**Comment by sgratzl** [comment]
Replying to [comment:2 mstreit]:

> If a concrete group is suggested in the ranking result, only the group should be highlighted using a halo.
> r5686
