### ISSUE TITLE
Add mutual exclusivity query

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#897]

**Comment by sgratzl** [comment]
scenario: 
 score indicating whether a gene group A ist just in one another group B_i of stratification B. i.e score: = {{{ A x B_i - mean(A x B_j, for all j \ i) }}}

**Comment by sgratzl** [comment]
simple implementation based on this approach in r5649

**Comment by sgratzl** [comment]
r5671 dedicated triggering via !BrickColumn->Context Menu

**Comment by sgratzl** [comment]
> @mutual exclusivity: \
> nur um sicher zu gehen, ob wirs richtig verstanden haben angenommen man rechnet mutual excl >in CNV dann triggert man die suche auf einem bestimmten gen
> sucht man dann nach:
> a) allen hohen correlations zwischen gruppen die nicht meine eigene ist
> oder
> b) nach einem möglichst geringen jaccard innerhalb der gleichen gruppe (zB aplified)
> 
> Caleydo Alexander Lex: a)

**Comment by sgratzl** [comment]
r5690
flag in jaccard index, definining whether the "same" group should have a score of NaN: 

"same": if the same datadomain, the datadomain is categorical and the group index are identical

**Comment by sgratzl** [comment]
@marc: is it now correct?

**Comment by mstreit** [comment]
looks good. see attached screenshot.
