### ISSUE TITLE
Represent loaded external rankings

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#899]

**Comment by sgratzl** [comment]
> Think about way how to represent loaded external rankings
> a more detailed description, please

**Comment by alexsb** [comment]
@mstreit  do you mean in the DVI, the integration of non-dataset virtual arrays? Do you  have an example again?

**Comment by mstreit** [comment]
An example is a gene list with a p-value score for each gene. Currently, that would only show up in TourGuide as a new column. As we have the memo pad to manage them (to a certain extent), that could be ok for now.

**Comment by alexsb** [comment]
Do we have this kind of data available as part of the firehose runs?

**Comment by ngehlenborg** [comment]
Yes, plenty, e.g. from MutSig or many of the correlation analyses. Sometimes we  don't have a p-value but other scores.

**Comment by alexsb** [comment]
OK, then we need to make it part of a project file. I'm not up-to-date on what tour-guide related functionality is now part of the serialization?

**Comment by sgratzl** [comment]
> OK, then we need to make it part of a project file. I'm not up-to-date on what tour-guide related functionality is now part of the serialization? 

the loaded external scores are already serialized within the project file using an extension point technique.

However they are not currenlty represented e.g. in the DVI but just in the memo-pad of tourguide

**Comment by sgratzl** [comment]
is this still an issue?
