### ISSUE TITLE
Jaccard index should handle elements that are not shared between queried stratifications

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#907]
See attached screenshot
In this case the score should be 1 instead of 0.16.

**Comment by mstreit** [comment]
let user change if the jaccard should be calculated on the union or the intersection

**Comment by sgratzl** [comment]
Replying to [ticket:994 mstreit]:

> See attached screenshot
> In this case the score should be 1 instead of 0.16.
> original feature in r5670
