### ISSUE TITLE
integrate gene-based column with IGV and Firehose Standard Data run data

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#912]
The header brick menu should have an entry "View Gene in IGV > ...", e.g. to see a copy number change in the context of genomic location. Great example: there is high correlation between copy number status of EGFR and SEC61G in GBM - but that is because they are right next to each other.

**Comment by alexsb** [comment]
Is that something we want to do for 3.0? 

Relates to #666

**Comment by ngehlenborg** [comment]
IGV has to be launched locally through Java Web Start but Caleydo can then communicate directly with IGV through an HTTP port: http://www.broadinstitute.org/igv/PortCommands
