### ISSUE TITLE
Include group size in combined scores

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#916]
atm the size can be added as ranking column but cannot be incorporated in the combined score calculation.

**Comment by mstreit** [comment]
this is tricky because we don't have a unique reference max sample number for normalizing the size value.

**Comment by sgratzl** [comment]
r5681 size can be naively used within combined score

**Comment by sgratzl** [comment]
r5684 weights for combined scores

**Comment by sgratzl** [comment]
r5709

-> during combine dialog one can specify a factor, tothepowerof and shift: f \* x^p + s

using this most of the simple transformations should be possible: 1/size -> p=-1
