### ISSUE TITLE
Gene Set Enrichment Analysis

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#920]
Java and R implementation available

http://www.broadinstitute.org/gsea/index.jsp
http://www.bioconductor.org/help/course-materials/2009/SeattleApr09/gsea/

**Comment by sgratzl** [comment]
scenario: \
match: pathway (i.e. the mapped genes) -> see #1029\
query: a group of a stratification (only from mRNA, mRNA-sig) \
score: the GSEA + p-value for the gene set defined by the pathway for the correlations between the expression levels of the group vs the rest of the same stratification. 

where the correlation for the ranked gene list is computed by: 
 mean of the expressions level of the samples for the given gen.

**Comment by sgratzl** [comment]
@somebody else: there is somehow a bug in my ranked list computation code: 

current pseudo code:

ranked list: 

```
A ... current selected sample group
table ... the underlying normalized expression values

genevalues = for (gene g) {
 as = [table(s,g) for (sample s in A)]
 bs = [table(s,g) for (sample s not in A)]
 g_correlation = mean(as) - mean(bs)
 (g, g_correlation)
}

rankedList = genevalues.sortBy(_2.descreasing)
```

any idea?

**Comment by ngehlenborg** [comment]
Your pseudo code looks ok to me but it might fail depending on the range of the data. Are there negative numbers? 

Unless your data is guaranteed to be log-transformed I would probably prefer to compute the ratio of the means (not the difference).

**Comment by sgratzl** [comment]
Replying to [comment:4 gehlenborg]:

> Unless your data is guaranteed to be log-transformed I would probably prefer to compute the ratio of the means (not the difference).

r5729 mean ratio

**Comment by sgratzl** [comment]
r5740

implementation (to my best knowledge) of PAGE (Parametric Analysis of Gene Set Enrichment), based on http://www.biomedcentral.com/1471-2105/6/144

big pro: fast

**Comment by mstreit** [comment]
@sgratzl Can this issue be closed?

**Comment by sgratzl** [comment]
p values are still missing, so not yet

btw. I think the correct abbrevation is PAGE and not PGSEA
