### ISSUE TITLE
Add invert score feature

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#921]
This could be either realized via the loading dialog or as a column-based setting. The second option is probably better.

**Comment by sgratzl** [comment]
duplicate: #1025: 

When combining size of a group (here: bigger = better) with the p-value (here: smaller = better) it would be useful I the combined filter could be created as 1/size \* p-value = combined score.

**Comment by sgratzl** [comment]
r5709

-> during combine dialog one can specify a factor, tothepowerof and shift: {{{f \* x^p + s}}}

using this most of the simple transformations should be possible: 1/size -> p=-1
