### ISSUE TITLE
Dedicated "add mode" tour guide

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#922]
A tour guide instance dedicated for adding stratifications to StratomeX would be useful. This can be realized as a second tab on the right side. It should be made clear to the user that the two instances serve different purposes (e.g., different name, special background color).

**Comment by sgratzl** [comment]
r5720 - clone view button -> clones the view and the underyling query

**Comment by alexsb** [comment]
does this solve the issue?

**Comment by sgratzl** [comment]
I think we agreed that we don't want a dedicated tour guide mode for adding as this is just the simplest scoring case

wontfix
