### ISSUE TITLE
Mark group or stratification where score is triggered

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#926]
Halo with a different color would be possibility.
We somehow also need to visually connect it to the corresponding query column in Tour Guide.

**Comment by alexsb** [comment]
Rectangle instead of halo - see #1176

**Comment by sgratzl** [comment]
is this still an issue, as you can't directly trigger a score any longer, see #1201

**Comment by sgratzl** [comment]
> is this still an issue, as you can't directly trigger a score any longer, see #1201

-> invalid
