### ISSUE TITLE
Column replacement when selecting a ranked row in TourGuide causes buggy column in StratomeX

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#930]
When genes and groups are mixed in the ranked list, a switch from a group row to a gene row causes a strange state in StratomeX where the column has the group stratification header brick with the gene stratification content (see screenshot).

**Comment by mstreit** [comment]
the header is the one from the first volatile added column (the yellow highlighted column)

**Comment by sgratzl** [comment]
seems to be stratomex related, there is a function / event: {{{replaceTablePerspective}}}, which uses somehow the assumption, that only a tableperspective within the same datadomain is used. 

This can either be solved within stratomex or within tour guide by not updating the brick column but instead remove and create a new one. 

r5696 (is currently the simpler second solution)

**Comment by sgratzl** [comment]
applies also for updating of the kaplan maier plots

**Comment by sgratzl** [comment]
Replying to [comment:4 gratzl]:

> applies also for updating of the kaplan maier plots
> r5739 same workaround as before
