### ISSUE TITLE
Transpose grouping matrix in import dialog

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#939]
Sometimes the matrix needs to be transposed (because rows are attributes, columns are samples).

**Comment by alexsb** [comment]
Why is the current transpose feature insufficient?

**Comment by ngehlenborg** [comment]
You can only select individual columns but not individual rows in the matrix view in the import dialog, i.e. it doesn't help to apply the transpose feature if you want to select a subset of rows. Ideally, the filter operations on rows and columns in that matrix view should be the same.

**Comment by alexsb** [comment]
Good point. Consequence: 
- we should transpose in the initial dialog
- we should allow to select/deselect rows and columns

**Comment by cpartl** [comment]
What is the initial dialog? You can load groupings afterwards. Also, this seems to also have severe consequences on parsing and data structure, where @alexsb is probably more knowledgeable.

**Comment by alexsb** [comment]
I think what we could do easily is to really transpose the file on demand. We're not going to adapt the parser. @ngehlenborg  - how important is this?

**Comment by ngehlenborg** [comment]
@alexsb: what do you mean by transpose on demand? I think it is important to be able to select rows, eg. if columns are samples and rows are individual variables, which is the case for TCGA clinical data. But there are probably more important things to fix first.

**Comment by alexsb** [comment]
This ticket is about grouping information. The question is whether we need to be able to load groupings that reference to a known ID by it's row identifier instead of it's column Identifier. Something like

```
                      TCGA-13-124   TCGA-14-122  TCGA-11-152
Cluster Algo           1              2                  1
Cluster Algo 2        2              1                  1
```

**Comment by ngehlenborg** [comment]
Some of the clinical data are in fact categorical/for grouping, e.g. histological type, gender or tumor stage:

```
Hybridization REF   tcga-a1-a0sb    tcga-a1-a0sd    tcga-a1-a0se    tcga-a1-a0sf
gender  female  female  female  female
histologicaltype    other  specify  infiltrating ductal carcinoma   mixed histology (please specify)    infiltrating ductal carcinoma
tumor.stagecode t1c t2  t1c t2
neoplasm.diseasestage   stage i stage iia   stage i stage iia
```

**Comment by alexsb** [comment]
ok, but we'll probably treat this as data not as groupings. so we might want to add a transpose step optionally. @cpartl, kann you investigate whether there is a platform independent way to transpose a text file we could use. If this is simple we should include it. Otherwise we'll move it to 3.1.

**Comment by ngehlenborg** [comment]
Hm - maybe transposing is not the only way to solve the problem. Why don't we simply add checkboxes to the rows and let the user limit the row selection (instead of transposing)?

**Comment by alexsb** [comment]
We decided against that in the past with the argument that we allow a header but the rest should be continuous. Might make sense for few rows, but of course is useless for many.

**Comment by ngehlenborg** [comment]
But the same argument would hold for files that have many columns, right?

**Comment by alexsb** [comment]
Yes, but usually the of the columns is less, but that's a convention only.

**Comment by alexsb** [comment]
Oh, and we also decided that we definitely don't want to do inhomogeneous rows. That's simply not possible with the architecture right now, and this is also desirable. Only one variable (columns or rows) can be inhomogeneous, both is useless. You always want to know which  one is inhomogeneous, and it's much much simpler to have a convention on which it is. So we can do row selection, but we cant and won't do it for inhomogeneous rows. If you have inhomogeneous rows you need to transpose them.

**Comment by ngehlenborg** [comment]
If we go by TCGA data, we have a pretty good mix of files with many rows/few columns and few rows/many columns.

If we can live without this convention I could load the data that I wanted to load for a long time. We'd just have to add checkboxes to the rows. I guess we could even allow selection on both rows and columns at the same time ...

**Comment by ngehlenborg** [comment]
Whatever it is - we need a solution to load the data from the TCGA clinical data files for Release 3.0.

**Comment by alexsb** [comment]
You said "there are probably more important things to fix fist" ;). For TCGA that's not an issue since we provide it pre-packaged. Let's wait for @cpartl  to investigate as discussed above. I think the transpose function would be the cleanest solution.

**Comment by ngehlenborg** [comment]
I didn't mean that it is not important enough to be fixed for 3.0, but there are plenty of bugs that all should be fixed more urgently than addressing this problem.

**Comment by cpartl** [comment]
The problem is that its not just a matter of adding checkboxes to the rows.The parser that creates the groupings takes the file and "row deselection" is not supported in the parser (correct me if I am wrong). Btw: At least the clinical dataset I am using (which should be from the sample project) has inhomogeneous columns, not inhomogeneous rows. 

For 3.1 we could think about rewriting the parser and using the matrix that is created anyway for the preview at the moment instead of parsing the file (again). But I guess this change is not realistic for 3.0.

**Comment by cpartl** [comment]
I just realized that simple transposition of the file will not work due to header rows.

**Comment by alexsb** [comment]
Nils, please attach an example of a file we need to support.

**Comment by ngehlenborg** [comment]
Here are some examples:
- http://gdac.broadinstitute.org/runs/stddata__2013_05_23/data/BRCA/20130523/gdac.broadinstitute.org_BRCA.Clinical_Pick_Tier1.Level_4.2013052300.0.0.tar.gz
  - file: _BRCA.clin.merged.picked.txt_
- http://gdac.broadinstitute.org/runs/stddata__2013_05_23/data/BRCA/20130523/gdac.broadinstitute.org_BRCA.Merge_Clinical.Level_1.2013052300.0.0.tar.gz
  - file: _BRCA.clin.merged.txt_

**Comment by ngehlenborg** [comment]
Btw, whatever parser we are using, it must be able to read (selected?) rows from such files, because we package them into the TCGA packages.

**Comment by alexsb** [comment]
I assume that @sgratzl transposes them?

**Comment by ngehlenborg** [comment]
See `TCGADataSetBuilder.java` line 326: `setUpClinicalData(...)`. There is a `transposeCSV(...)` method that transposes the file (by re-writing it to another file that is then used for parsing).

**Comment by alexsb** [comment]
Yes. Let's go with that. @cpartl - please add a button to the import table which transposes the file, writes a new file source_name-transposed.txt and automatically load the new file into the import dialog.

If there are headers they can be excluded by excluding the resulting columns later.
