### ISSUE TITLE
Load Gene Sets from MSigDB

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo#940]
http://www.broadinstitute.org/gsea/msigdb/index.jsp

e.g. as an selection of gene #1007 Gene Set Enrichment Analysis in constrast to Mapped Pathway Genes.

**Comment by sgratzl** [comment]
download: http://www.broadinstitute.org/gsea/downloads.jsp

e.g. http://www.broadinstitute.org/gsea/msigdb/download_file.jsp?filePath=/resources/msigdb/3.1/msigdb.v3.1.symbols.gmt

format: one gene set per line with `<name>"\t"<url>("\t"<gene>)+`

**Comment by alexsb** [comment]
What's the status of this? Do we want that in 3.0?

**Comment by sgratzl** [comment]
after we have loaded the gene sets, want could we do with them?

**Comment by ngehlenborg** [comment]
We want to use the gene sets to create new perspectives, similar to the sampling based on most variable genes. 

But this would also require that we can create heatmaps with individual genes, small lists of genes, etc. The MSigDB gene lists would just a simple way to select such lists.
