### ISSUE TITLE
Choose Dimension Clustering/Stratification via context-menu in tour-guide and on header brick

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#943]
Currently a default is chosen.

This needs to be updated in DVI as well

**Comment by sgratzl** [comment]
r5724 now part of tour guide -> context menu of the add icon let you select which gene clustering should be used

default: first not "ungrouped" entry

**Comment by sgratzl** [comment]
Replying to [ticket:1030 lex1]:

> Choose Dimension Clustering/Stratification via context-menu in tour-guide 
> done see comment above
> and on header brick

header brick on Stratomex -> to change what: the dimension stratification for the actual visible table perspective or ???

> Currently a default is chosen.
> 
> This needs to be updated in DVI as well
> the current implementation of DVI is not able to automatically create new DataContainer entries (highlighted matrix entries between record and dimension perspectives), and I have no clue how to fix this

**Comment by alexsb** [comment]
I suggest the following solution:
- [ ] Default stratification is higlighted in DVI. 
- [ ] Default stratification can be changed in DVI. 
- [x] Default stratification for dataset can be changed by right-clicking dataset icon in tour-guide - this opens up a gui with a radio selection for all possible startifications
- [x] Stratification of columns can be changed via context menu of existing stratification

Please comment. I'll create tickets for 3.0 for each of those soon.

**Comment by sgratzl** [comment]
1. I doubt the effectiveness of task lists in comments
2. Default stratification for dataset can be changed by right-clicking dataset icon in tour-guide - this opens up a gui with a radio selection for all possible startifications
   
   should already be possible, check out the context menu

**Comment by alexsb** [comment]
1. yea, I'm planning to create tickets once we agree anyways 
2. cool, didn't know that

**Comment by sgratzl** [comment]
> Default stratification is higlighted in DVI.
> Default stratification can be changed in DVI. 

in DVI there is no need for a default stratification, as you always have to select the record as well as the dimension stratification to create a table perspective. Therefore it would only be a support for other views, like tour guide, which may confuse the users

**Comment by alexsb** [comment]
The DVI is by definition always support for other views ;). It does make sense though to define and show a default stratification also in DVI, mainly for user education and consistency.

**Comment by sgratzl** [comment]
> yea, I'm planning to create tickets once we agree anyways 

do we already have an agreement?

**Comment by sgratzl** [comment]
> Stratification of columns can be changed via context menu of existing stratification

part of b933d8e98e7c145e02fd9bb5b57f34fcc1e72307 for numerical tables only

**Comment by alexsb** [comment]
Outsourced DVI related stuff to #1370 
Rest is fixed, closing.
