### ISSUE TITLE
Include copy number clusterings from Firehose

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#945]
This has actually two parts: 
- [ ] Load copy number clusterings by default 
- [ ] Present them in the interface

**Comment by alexsb** [comment]
This could be addressed using multiple dataset instances in LineUp for Copy Number, but that's not very elegant.

**Comment by sgratzl** [comment]
see also #1448 in this case groupings of categorical data are automatically added as metrics to LineUp

**Comment by mstreit** [comment]
@ngehlenborg Should we add them by default to our TCGA packages?
