### ISSUE TITLE
preview and test regex'ed IDs

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#948]
Preview:
When applying a regex to an ID immediate preview should be available that shows the converted IDs. This should be in the same dialog as the regex editor. The regex should also be applied to the ID column in the tabular preview once the user has selected a regex.

Test:
The user should be able to test how many IDs will be mapped before loading the data set or grouping.

**Comment by mstreit** [comment]
@cpartl You already implemented that, right? Is there a reason why the issue is still open?

**Comment by cpartl** [comment]
Implemented preview in regex dialog, but the ids are not adapted in the table and there is no mapping test. We should discuss this point.

**Comment by alexsb** [comment]
Concerning your comment:  #1235 
The preview with the -> is a little confusing. It should be:

Preview (Header)
Original ID: TCGA-01-002
Converted ID: 01-002
