### ISSUE TITLE
Error message upon loading of matrices or tables with duplicate ids

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#949]
There should be an error message if a duplicate id is encountered. The user should be given the option to skip the second and further instances of the id or to cancel loading altogether.

**Comment by sgratzl** [comment]
@cpartl same here

**Comment by ngehlenborg** [comment]
> The user should be given the option to skip the second and further instances of the id or to cancel loading altogether.

... or to continue loading at their own risk.

**Comment by ngehlenborg** [comment]
This should also apply to data loaded from cal files - there needs to be some kind of warning that there are duplicates.

**Comment by ngehlenborg** [comment]
We urgently need this feature, without an indicator of whether or not duplicates were encountered during loading it is hard to trust any results.

![screen shot 2014-03-17 at 1 07 47 am](https://f.cloud.github.com/assets/1216518/2433496/2130bb28-ad92-11e3-9da4-783ac80a3977.png)
