### ISSUE TITLE
allow closing/removal of data sets in DVI & Tour Guide

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#951]
Currently there is no way to get rid of unwanted data sets (loaded incorrectly, etc.)

**Comment by sgratzl** [comment]
r5735

i can't guarantee that a removed data set will also be garbage collection, as there might be too many unknown references, but in the simple cases it should work. 

example of such a (nice) reference: !StartupProcessor (static singleton) -> !SerializationStartupProcedure -> !SerializationData -> !DataDomainSerializationData -> !DataDomain

where A->B means: A has a field/refernce to an object of type B
