### ISSUE TITLE
TCGAImporter hangs on Mac when calling EDataSetType.values()

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#952]
The problem is in line 60 of TCGAXMLGenerator. 

Apparently this is not a problem on other platforms.

**Comment by sgratzl** [comment]
to be more precise it hangs at: {{{Color.getColorWithSpecificBrighness}}} during the AWT initialization. 

solution: 
 b. add -Djava.awt.headless=true to the vm arguments
 a. or implement the RGB2HSB and HSB2RGB without the use of java.awt.Color

**Comment by ngehlenborg** [comment]
Option b. did the trick. Thanks!
