### ISSUE TITLE
Replace DAVID

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#954]
http://mygene.info/
Pros: brand new
Cons: brand new :)

**Comment by sgratzl** [comment]
plan: 
1. batch download the data from mygene.info and store them locally in zips per species in a generic way
2. put the zips on the caleydo website
3. during the initial selection of the organism, download and cache the mapping zips from the server at runtime
4. load just the primary mappings (GENE_NAME,...) as well as the list of existing mappings
5. lazy loading of the remaining mappings, to save memory

subtasks: 
- batch download mechanism
- lazy loading of mapping zips -> #964 
- lazy loading of mapping files -> see #963

**Comment by alexsb** [comment]
See also #364

**Comment by ngehlenborg** [comment]
Ensembl BioMart might be another option: http://useast.ensembl.org/info/index.html
