### ISSUE TITLE
Load new mutation files for Firehose runs

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#956]
Use old files as fallback if no new ones are available

new format: [https://wiki.nci.nih.gov/display/TCGA/Mutation+Annotation+Format+%28MAF%29+Specification MAF] 

located in 
e.g. 
http://gdac.broadinstitute.org/runs/analyses__2012_12_21/data/BRCA/20121221/gdac.broadinstitute.org_BRCA.MutSigNozzleReport2.0.Level_4.2012122100.0.0.tar.gz

named: BRCA-TP.final_analysis_set.maf

**Comment by sgratzl** [comment]
how I understood it: 
 MAF file contains only the mutated genes in the form
{{{
    <gene>TAB<patient>TAB<data>
}}} 
(more or less) without preprocessing not directly loadable to caleydo

**Comment by sgratzl** [comment]
r5791

parse MAF file back to table containing: 
gene x sample -> isMutated
