### ISSUE TITLE
For the sample expression dataset the sample and gene ID types are no longer set in the import dialog

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#959]
This makes it hard for a novel user to find the correct settings to start Caleydo with the sample expression dataset.

**Comment by alexsb** [comment]
Also ID guessing seems to be dead.

**Comment by sgratzl** [comment]
will become invalid as soon as the sample expression dataset will be removed

**Comment by alexsb** [comment]
Updated the description to describe the underlying problem - which is still valid - if @cpartl  didn't fix it in the meantime when working on the importer.
