### ISSUE TITLE
Load ZIP files containing mapping data from our server on demand

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#963]
The new mapping files from mygene.info should be bundled in a ZIP - one for each organism. 
The appropriate ZIP file should be loaded on demand after the user has determined the organism to use.

**Comment by alexsb** [comment]
Related to #954

**Comment by sgratzl** [comment]
not really a must-have for 3.0

**Comment by sgratzl** [comment]
base url: http://data.icg.tugraz.at/caleydo/download/3.0/mappings/

notation: `<organism in lowercase>.zip`
content: depending, see source code
