### ISSUE TITLE
Automatically create organism specific ZIP files containing all mappings

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#965]
Fetch mapping data from mygene.info
Parse mappings from JSON files
Create single mapping files
Create ZIP bundles - one for each organism
Put ZIP file on our server (there is no need anymore to commit mapping files to SVN repository)

**Comment by alexsb** [comment]
Related to #954

**Comment by sgratzl** [comment]
not really a must-have for 3.0
