### ISSUE TITLE
Generate cal packages for December and Jan runs

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#968]
Jan is not available yet.
We need the packages to work with release 2.2.

**Comment by sgratzl** [comment]
preparations in r5814, r5813, r5812

notes:
the december run runs with no unexpected errors, but it takes time to download all the data

**Comment by sgratzl** [comment]
r5850, r5855, r5860

notes: data packages created, missing: upload jnlp from jan and .json from jan update

missing: merge with trunk

**Comment by sgratzl** [comment]
r5867 merge
