### ISSUE TITLE
Add categorical data columns

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#971]
Compact: just color of categories
Normal: color as background and maybe label

The user should be able to define filters.

**Comment by sgratzl** [comment]
start in r5968

**Comment by sgratzl** [comment]
r5982

notes: 
- up to now the summary just shows the filter status (None vs x out of y)
- no mapping yet -> needed ?

**Comment by sgratzl** [comment]
r6002, r6009

current strategy: 
 if more than CategoricalRankColumnModel.MAX_CATEGORY_COLORS = 8 categories are there, then just the label is shown otherwise the label + color + a simple histogram of the values as summary
