### ISSUE TITLE
Import University ranking data

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#972]
http://mup.asu.edu/research_data.html

world university ranking: http://www.timeshighereducation.co.uk/world-university-rankings/2012/reputation-ranking/methodology

the 100 under 50: http://www.timeshighereducation.co.uk/story.asp?storycode=420090

the 100 under 50, detailed results: (as image) http://europe.nxtbook.com/nxteu/tsl/100under50/index.php#/8

**Comment by sgratzl** [comment]
r5961 simple 100 under 50 dataset -> class University

**Comment by sgratzl** [comment]
r5982

university now supports
- string filtering correctly
- country categorical (filtering)
- key listener UP/DOWN for changing the selected row

MISSING: for the 32 countries a color -> see countries.txt

**Comment by alexsb** [comment]
Hanspeter strongly suggested the News and World ranking as it is the de-facto standard. 

http://www.usnews.com/education/worlds-best-universities-rankings/top-400-universities-in-the-world

Doesn't look like they make the data available easily though. 

There are also articles discussing alternative weights, which might be interesting to discuss in the paper. 

Will get link to article.

**Comment by alexsb** [comment]
Accoridng to wikipedia: 
The QS World University Rankings is regarded as one of the three most influential and widely observed international university rankings, along with the Times Higher Education World University Rankings and the Academic Ranking of World Universities.

QS ranking: 
http://www.topuniversities.com/university-rankings/world-university-rankings/

Times higher education world university rankings: 
http://en.wikipedia.org/wiki/Times_Higher_Education_World_University_Rankings

Academic Ranking of World Universities
http://www.arwu.org/

**Comment by sgratzl** [comment]
Replying to [ticket:1059 mstreit]:

> http://mup.asu.edu/research_data.html
> imported see university.mup

Replying to [comment:4 lex1]:

> QS ranking: 
> http://www.topuniversities.com/university-rankings/world-university-rankings/
> imported see university.wur
> Academic Ranking of World Universities
> http://www.arwu.org/
> imported see university.arwu package

**Comment by sgratzl** [comment]
r6212

top 100 under 50

new based on 
http://www.guardian.co.uk/news/datablog/2012/may/31/top-100-universities-under-50#data
