### ISSUE TITLE
Add pre-defined standard operations to mapping visualization

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#974]
Examples: invert, log
Maybe this can be part of a general mapping function definition dialog.

**Comment by alexsb** [comment]
I'd strongly advocate this if its technically feasible at all. If I had to choose a feature, this would be right after #1065 (except of course for the base functionality).

**Comment by sgratzl** [comment]
r6124

current items:
- INVERT: "linear(0, 1, value, 1, 0)"
- ABS: "linear(0, abs(value_min, value_max), abs(value), 0, 1)"
- Z_SCORE: "((value - data.mean) / data.sd) + 0.5"
- LINEAR_LOG: "linear(0, log(value_max), log(value), 0, 1)"

-> defined in {{{EStandardMappings.java}}}
