### ISSUE TITLE
Create exported runnable version with University dataset for Reviewers

### ISSUE THREAD

**Issue by mstreit** [Caleydo/caleydo#977]

**Comment by sgratzl** [comment]
r5981 draft

-> run the build.xml ant script and it should create target/University.jar for your system windows 64 or linux 64 - mac not yet tested

**Comment by sgratzl** [comment]
r6027

more intelligent jar in jar loader -> can include platform specific libraries (swt)

open issue: {{{-XStartOnFirstThread}}}
