### ISSUE TITLE
Text rendering issues when bubble sets active

### ISSUE THREAD

**Issue by cpartl** [Caleydo/caleydo#997]
When a bubbleset is shown in subgraph view, there are severe text rendering issues in the tourguide pathway list.

**Comment by cpartl** [comment]
Apparently this only occurs on my machine and seems to have to do something with the paths' text rendered in display lists.

**Comment by alexsb** [comment]
Related to #931

This is confirmed independent of the platform.

**Comment by sgratzl** [comment]
> Apparently this only occurs on my machine and seems to have to do something with the paths' text rendered in display lists.

see comments in #931 which supports your assumption. Up to now it should me unlikely that it will happen again.

So @cpartl can you verify this issue again?

**Comment by alexsb** [comment]
@cpartl - still an issue?

**Comment by cpartl** [comment]
This was fixed previously.
